import TraceEuclideanKernel

/-!
# Kernel-only boundary audit

The declarations below are the proof-bearing endpoints used to distinguish
the formal main-result path from archival finite-data replays.  CI checks both
their transitive imports and their reported axiom sets.
-/

#check TraceEuclidean.no_totallyRealQuinticField_discriminant_lt_14641
#check TraceEuclidean.coded_degree_five_discriminant_ge_14641
#check TraceEuclidean.degreeSevenMinimum_hunterBall_numerical
#check TraceEuclidean.exists_degreeSevenMinimum_hunterFieldCandidate
#check TraceEuclidean.degreeSevenMinimum_candidate_mem_box
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_stageThree_frontier_complete
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_stageFour_frontier_complete
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_root_centered_sq_le
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_root_lagrange_strict_bounds
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a2_mem_of_valid
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a2_mem_of_valid_dyadic
#check TraceEuclidean.degreeSevenStageFiveMultipleRootWitness_not_separable
#check TraceEuclidean.degreeSevenStageFiveCriticalSignWitness_not_splits_and_separable
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_stageFive_complete
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a2_mem
#check TraceEuclidean.degreeSeven_firstDerivativeStage_eq
#check TraceEuclidean.degreeSeven_sextic_derivative_eq
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem_of_valid
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem_of_stageFive_valid
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a0_mem_of_stageFive
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_allCoefficients_mem
#check TraceEuclidean.degreeSevenStageSixStrongCompactCoverages_valid
#check TraceEuclidean.degreeSevenStageSixStrongCompactCoverages_parents
#check TraceEuclidean.degreeSevenStageSixStrongCompactCoverage_count
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_complete
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_complete_with_top
#check TraceEuclidean.DegreeSevenStageSixPiecewiseCoverage.hunter_a1_mem
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_piecewise_complete
#check TraceEuclidean.DegreeSevenStageSixScaledFamily.a1Candidates_eq_scaledA1Candidates
#check TraceEuclidean.DegreeSevenStageSixPiecewiseCoverage.pieces_forall_arithmeticValid
#check TraceEuclidean.mem_integerIccList_iff_mem_integerIcc
#check TraceEuclidean.DegreeSevenStageSevenEntry.a0Candidates
#check TraceEuclidean.DegreeSevenStageSevenScaledEntry.valid_of_arithmeticValid
#check TraceEuclidean.DegreeSevenStageSevenScaledEntry.a0Candidates_eq_scaledA0Candidates
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a0_mem_of_stageSeven
#check TraceEuclidean.degreeSeven_firstDerivativeStage_separable
#check TraceEuclidean.degreeSeven_stageSevenMultipleRootWitness_not_hunter
#check TraceEuclidean.DegreeSevenStageSevenCriticalSignWitness.not_splits_and_separable
#check TraceEuclidean.degreeSeven_stageSevenCriticalSignWitness_not_hunter
#check TraceEuclidean.DegreeSevenStageSevenScaledCriticalSignWitness.ArithmeticValid
#check TraceEuclidean.DegreeSevenStageSevenScaledCriticalSignWitness.valid_of_arithmeticValid
#check TraceEuclidean.degreeSevenStageSevenClassification_prefixes_toFinset
#check TraceEuclidean.mem_sexticTranslationCandidates_of_signs
#check TraceEuclidean.mem_septicTranslationCandidates_of_signs
#check TraceEuclidean.odlyzko_discriminant_log_lower_bound
#check TraceEuclidean.odlyzkoTable4DescriptionInput_closed
#check TraceEuclidean.degreeFiveToNineMinimumInput_of_sixToNine
#check TraceEuclidean.sectionFourDiscriminantInput_of_voightEnumerationSixToTen_closed
#check TraceEuclidean.classic_pair_mem_of_voightEnumerationSixToTen_poitou
#check TraceEuclidean.integral_pair_mem_of_voightEnumerationSixToTen_poitou
#check TraceEuclidean.PoitouDegreeElevenClosed.poitouL1_upper_certificate
#check TraceEuclidean.PoitouKernel.poitouFullKernel_boundedVariation
#check TraceEuclidean.PoitouKernel.poitouDifferenceQuotient_boundedVariation
#check TraceEuclidean.PoitouKernel.poitouY_admissible
#check TraceEuclidean.PoitouKernel.poitouPhi_re_nonneg_of_mem_open_strip
#check TraceEuclidean.PoitouKernel.poitouPhi_zero_tsum_re_nonneg

#print axioms TraceEuclidean.no_totallyRealQuinticField_discriminant_lt_14641
#print axioms TraceEuclidean.coded_degree_five_discriminant_ge_14641
#print axioms TraceEuclidean.exists_degreeSevenMinimum_hunterFieldCandidate
#print axioms TraceEuclidean.degreeSevenMinimum_candidate_mem_box
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_stageThree_frontier_complete
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_stageFour_frontier_complete
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_root_centered_sq_le
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_root_lagrange_strict_bounds
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a2_mem_of_valid
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a2_mem_of_valid_dyadic
#print axioms TraceEuclidean.degreeSevenStageFiveMultipleRootWitness_not_separable
#print axioms TraceEuclidean.degreeSevenStageFiveCriticalSignWitness_not_splits_and_separable
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_stageFive_complete
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a2_mem
#print axioms TraceEuclidean.degreeSeven_firstDerivativeStage_eq
#print axioms TraceEuclidean.degreeSeven_sextic_derivative_eq
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem_of_valid
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem_of_stageFive_valid
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a0_mem_of_stageFive
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_allCoefficients_mem
#print axioms TraceEuclidean.degreeSevenStageSixStrongCompactCoverages_valid
#print axioms TraceEuclidean.degreeSevenStageSixStrongCompactCoverages_parents
#print axioms TraceEuclidean.degreeSevenStageSixStrongCompactCoverage_count
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_complete
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_complete_with_top
#print axioms TraceEuclidean.DegreeSevenStageSixPiecewiseCoverage.hunter_a1_mem
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_piecewise_complete
#print axioms TraceEuclidean.DegreeSevenStageSixScaledFamily.a1Candidates_eq_scaledA1Candidates
#print axioms TraceEuclidean.DegreeSevenStageSixPiecewiseCoverage.pieces_forall_arithmeticValid
#print axioms TraceEuclidean.mem_integerIccList_iff_mem_integerIcc
#print axioms TraceEuclidean.DegreeSevenStageSevenScaledEntry.valid_of_arithmeticValid
#print axioms TraceEuclidean.DegreeSevenStageSevenScaledEntry.a0Candidates_eq_scaledA0Candidates
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a0_mem_of_stageSeven
#print axioms TraceEuclidean.degreeSeven_firstDerivativeStage_separable
#print axioms TraceEuclidean.degreeSeven_stageSevenMultipleRootWitness_not_hunter
#print axioms TraceEuclidean.DegreeSevenStageSevenCriticalSignWitness.not_splits_and_separable
#print axioms TraceEuclidean.degreeSeven_stageSevenCriticalSignWitness_not_hunter
#print axioms TraceEuclidean.DegreeSevenStageSevenScaledCriticalSignWitness.valid_of_arithmeticValid
#print axioms TraceEuclidean.degreeSevenStageSevenClassification_prefixes_toFinset
#print axioms TraceEuclidean.mem_sexticTranslationCandidates_of_signs
#print axioms TraceEuclidean.mem_septicTranslationCandidates_of_signs
#print axioms TraceEuclidean.odlyzko_discriminant_log_lower_bound
#print axioms TraceEuclidean.odlyzkoTable4DescriptionInput_closed
#print axioms TraceEuclidean.degreeFiveToNineMinimumInput_of_sixToNine
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_voightEnumerationSixToTen_closed
#print axioms TraceEuclidean.classic_pair_mem_of_voightEnumerationSixToTen_poitou
#print axioms TraceEuclidean.integral_pair_mem_of_voightEnumerationSixToTen_poitou
#print axioms TraceEuclidean.PoitouDegreeElevenClosed.poitouL1_upper_certificate
#print axioms TraceEuclidean.PoitouKernel.poitouFullKernel_boundedVariation
#print axioms TraceEuclidean.PoitouKernel.poitouDifferenceQuotient_boundedVariation
#print axioms TraceEuclidean.PoitouKernel.poitouY_admissible
#print axioms TraceEuclidean.PoitouKernel.poitouPhi_re_nonneg_of_mem_open_strip
#print axioms TraceEuclidean.PoitouKernel.poitouPhi_zero_tsum_re_nonneg
