import TraceEuclidean

/-! Public signature and transitive-axiom audit for the formalized endpoints. -/

#check TraceEuclidean.strictEuclidean_of_radius_lt
#check TraceEuclidean.radius_le_of_strictEuclidean
#check TraceEuclidean.pNormEuclidean_imp_traceEuclidean
#check TraceEuclidean.two_scaled_isometric_iff
#check TraceEuclidean.criticalPoint_hessian_negative
#check TraceEuclidean.finite_positive_of_tendsto_atTop_atBot
#check TraceEuclidean.voronoiVertexNorm_formula
#check TraceEuclidean.caseII_vertexNorm_first
#check TraceEuclidean.caseII_vertexNorm_middle
#check TraceEuclidean.caseI_closed_candidates
#check TraceEuclidean.caseII_closed_candidates
#check TraceEuclidean.mThree_midpoint_obstruction
#check TraceEuclidean.candidateRadii_strictlyBelowTwo
#check TraceEuclidean.isTraceEuclidean_iff_strictEuclidean
#check TraceEuclidean.isClosedTraceEuclidean_iff_closedEuclidean
#check TraceEuclidean.fieldTwoTraceEuclideanRat_iff_real
#check TraceEuclidean.realQuadratic_coveringRadiusSq_caseI
#check TraceEuclidean.realQuadratic_coveringRadiusSq_caseII
#check TraceEuclidean.coordinate_two_trace_euclidean_iff
#check TraceEuclidean.RealQuadraticCoordinateModel.field_two_trace_euclidean_iff
#check TraceEuclidean.realQuadratic_two_trace_euclidean_iff
#check TraceEuclidean.gClassicNat_degree_tail
#check TraceEuclidean.gIntegralNat_degree_tail
#check TraceEuclidean.gClassicNat_rank_tail
#check TraceEuclidean.gIntegralNat_rank_tail
#check TraceEuclidean.gClassicEnvelopeNat_tail
#check TraceEuclidean.gIntegralEnvelopeNat_tail
#check TraceEuclidean.finite_numberFieldCodes_of_discriminant_le
#check TraceEuclidean.finite_objects_of_bounded_field_discriminant
#check TraceEuclidean.NumberFieldLatticeModule.exists_pseudoBasis
#check TraceEuclidean.GlobalLatticePresentation.euclideanCovolume_sq_eq_discr_pow_absNorm_pseudo
#check TraceEuclidean.GlobalLatticePresentation.discriminant_pow_le_euclideanCovolume_sq_of_classic
#check TraceEuclidean.GlobalLatticePresentation.discriminant_pow_le_two_pow_mul_euclideanCovolume_sq
#check TraceEuclidean.GlobalLatticeClass.finite_fixedField_rank_classic_traceEuclidean
#check TraceEuclidean.GlobalLatticeClass.finite_fixedField_rank_integral_traceEuclidean
#check TraceEuclidean.GlobalFiniteness.classic_discriminant_pow_le_trace
#check TraceEuclidean.GlobalFiniteness.integral_discriminant_pow_le_trace
#check TraceEuclidean.GlobalFiniteness.classic_fixed_pair
#check TraceEuclidean.GlobalFiniteness.integral_fixed_pair
#check TraceEuclidean.GlobalFiniteness.finiteness_classic_fixed_degree_low_rank
#check TraceEuclidean.GlobalFiniteness.finiteness_classic_fixed_high_rank
#check TraceEuclidean.GlobalFiniteness.finiteness_classic_fixed_degree
#check TraceEuclidean.GlobalFiniteness.finiteness_classic_global
#check TraceEuclidean.GlobalFiniteness.finiteness_integral_fixed_degree_low_rank
#check TraceEuclidean.GlobalFiniteness.finiteness_integral_fixed_high_rank
#check TraceEuclidean.GlobalFiniteness.finiteness_integral_fixed_degree
#check TraceEuclidean.GlobalFiniteness.finiteness_integral_global
#check TraceEuclidean.GlobalLatticeClass.rank_pos
#check TraceEuclidean.exp_classicTraceVolumeExponent_eq_paperTraceVolumeBound
#check TraceEuclidean.exp_integralTraceVolumeExponent_eq

#print axioms TraceEuclidean.strictEuclidean_of_radius_lt
#print axioms TraceEuclidean.radius_le_of_strictEuclidean
#print axioms TraceEuclidean.pNormEuclidean_imp_traceEuclidean
#print axioms TraceEuclidean.two_scaled_isometric_iff
#print axioms TraceEuclidean.criticalPoint_hessian_negative
#print axioms TraceEuclidean.finite_positive_of_tendsto_atTop_atBot
#print axioms TraceEuclidean.voronoiVertexNorm_formula
#print axioms TraceEuclidean.caseII_vertexNorm_first
#print axioms TraceEuclidean.caseII_vertexNorm_middle
#print axioms TraceEuclidean.caseI_closed_candidates
#print axioms TraceEuclidean.caseII_closed_candidates
#print axioms TraceEuclidean.mThree_midpoint_obstruction
#print axioms TraceEuclidean.candidateRadii_strictlyBelowTwo
#print axioms TraceEuclidean.isTraceEuclidean_iff_strictEuclidean
#print axioms TraceEuclidean.isClosedTraceEuclidean_iff_closedEuclidean
#print axioms TraceEuclidean.fieldTwoTraceEuclideanRat_iff_real
#print axioms TraceEuclidean.realQuadratic_coveringRadiusSq_caseI
#print axioms TraceEuclidean.realQuadratic_coveringRadiusSq_caseII
#print axioms TraceEuclidean.coordinate_two_trace_euclidean_iff
#print axioms TraceEuclidean.RealQuadraticCoordinateModel.field_two_trace_euclidean_iff
#print axioms TraceEuclidean.realQuadratic_two_trace_euclidean_iff
#print axioms TraceEuclidean.gClassicNat_degree_tail
#print axioms TraceEuclidean.gIntegralNat_degree_tail
#print axioms TraceEuclidean.gClassicNat_rank_tail
#print axioms TraceEuclidean.gIntegralNat_rank_tail
#print axioms TraceEuclidean.gClassicEnvelopeNat_tail
#print axioms TraceEuclidean.gIntegralEnvelopeNat_tail
#print axioms TraceEuclidean.finite_numberFieldCodes_of_discriminant_le
#print axioms TraceEuclidean.finite_objects_of_bounded_field_discriminant
#print axioms TraceEuclidean.NumberFieldLatticeModule.exists_pseudoBasis
#print axioms TraceEuclidean.GlobalLatticePresentation.euclideanCovolume_sq_eq_discr_pow_absNorm_pseudo
#print axioms TraceEuclidean.GlobalLatticePresentation.discriminant_pow_le_euclideanCovolume_sq_of_classic
#print axioms TraceEuclidean.GlobalLatticePresentation.discriminant_pow_le_two_pow_mul_euclideanCovolume_sq
#print axioms TraceEuclidean.GlobalLatticeClass.finite_fixedField_rank_classic_traceEuclidean
#print axioms TraceEuclidean.GlobalLatticeClass.finite_fixedField_rank_integral_traceEuclidean
#print axioms TraceEuclidean.GlobalFiniteness.classic_discriminant_pow_le_trace
#print axioms TraceEuclidean.GlobalFiniteness.integral_discriminant_pow_le_trace
#print axioms TraceEuclidean.GlobalFiniteness.classic_fixed_pair
#print axioms TraceEuclidean.GlobalFiniteness.integral_fixed_pair
#print axioms TraceEuclidean.GlobalFiniteness.finiteness_classic_fixed_degree_low_rank
#print axioms TraceEuclidean.GlobalFiniteness.finiteness_classic_fixed_high_rank
#print axioms TraceEuclidean.GlobalFiniteness.finiteness_classic_fixed_degree
#print axioms TraceEuclidean.GlobalFiniteness.finiteness_classic_global
#print axioms TraceEuclidean.GlobalFiniteness.finiteness_integral_fixed_degree_low_rank
#print axioms TraceEuclidean.GlobalFiniteness.finiteness_integral_fixed_high_rank
#print axioms TraceEuclidean.GlobalFiniteness.finiteness_integral_fixed_degree
#print axioms TraceEuclidean.GlobalFiniteness.finiteness_integral_global
#print axioms TraceEuclidean.GlobalLatticeClass.rank_pos
#print axioms TraceEuclidean.exp_classicTraceVolumeExponent_eq_paperTraceVolumeBound
#print axioms TraceEuclidean.exp_integralTraceVolumeExponent_eq

-- V15-specific declarations and their transitive trust dependencies.
#check TraceEuclidean.v15_admissible_gram_iff_mem
#check TraceEuclidean.v15_quadratic_candidate_mem
#check TraceEuclidean.v15_quadratic_candidate_six_rows
#check TraceEuclidean.v15_survivor_first_index_one_except_three
#check TraceEuclidean.v15_m_three_trace_norm_solutions
#check TraceEuclidean.v15_six_radius_values
#check TraceEuclidean.v15_integral_rank_le_34
#check TraceEuclidean.v15_classic_finite_of_degree_bound
#check TraceEuclidean.v15_integral_finite_of_degree_bound
#check TraceEuclidean.V15OdlyzkoDegreeInput
#check TraceEuclidean.V15RankOneClassicInput
#check TraceEuclidean.v15_classic_finite_of_odlyzko
#check TraceEuclidean.v15_integral_finite_of_odlyzko
#print axioms TraceEuclidean.v15_admissible_gram_iff_mem
#print axioms TraceEuclidean.v15_quadratic_candidate_mem
#print axioms TraceEuclidean.v15_quadratic_candidate_six_rows
#print axioms TraceEuclidean.v15_survivor_first_index_one_except_three
#print axioms TraceEuclidean.v15_m_three_trace_norm_solutions
#print axioms TraceEuclidean.v15_six_radius_values
#print axioms TraceEuclidean.v15_integral_rank_le_34
#print axioms TraceEuclidean.v15_classic_finite_of_degree_bound
#print axioms TraceEuclidean.v15_integral_finite_of_degree_bound
#print axioms TraceEuclidean.v15_classic_finite_of_odlyzko
#print axioms TraceEuclidean.v15_integral_finite_of_odlyzko
