import TraceEuclidean

/-! Public signature and transitive-axiom audit for the formalized endpoints. -/

#check TraceEuclidean.strictEuclidean_of_radius_lt
#check TraceEuclidean.radius_le_of_strictEuclidean
#check TraceEuclidean.pNormEuclidean_imp_traceEuclidean
#check TraceEuclidean.two_scaled_isometric_iff
#check TraceEuclidean.criticalPoint_hessian_negative
#check TraceEuclidean.finite_positive_of_tendsto_atTop_atBot
#check TraceEuclidean.voronoiVertexNorm_formula
#check TraceEuclidean.caseII_vertexNorm_first
#check TraceEuclidean.caseII_vertexNorm_middle
#check TraceEuclidean.caseI_closed_candidates
#check TraceEuclidean.caseII_closed_candidates
#check TraceEuclidean.mThree_midpoint_obstruction
#check TraceEuclidean.candidateRadii_strictlyBelowTwo
#check TraceEuclidean.isTraceEuclidean_iff_strictEuclidean
#check TraceEuclidean.isClosedTraceEuclidean_iff_closedEuclidean
#check TraceEuclidean.fieldTwoTraceEuclideanRat_iff_real
#check TraceEuclidean.realQuadratic_coveringRadiusSq_caseI
#check TraceEuclidean.realQuadratic_coveringRadiusSq_caseII
#check TraceEuclidean.coordinate_two_trace_euclidean_iff
#check TraceEuclidean.RealQuadraticCoordinateModel.field_two_trace_euclidean_iff
#check TraceEuclidean.realQuadratic_two_trace_euclidean_iff
#check TraceEuclidean.gClassicNat_degree_tail
#check TraceEuclidean.gIntegralNat_degree_tail
#check TraceEuclidean.gClassicNat_rank_tail
#check TraceEuclidean.gIntegralNat_rank_tail
#check TraceEuclidean.gClassicEnvelopeNat_tail
#check TraceEuclidean.gIntegralEnvelopeNat_tail
#check TraceEuclidean.finite_numberFieldCodes_of_discriminant_le
#check TraceEuclidean.finite_objects_of_bounded_volumeIdeal
#check TraceEuclidean.bounded_discriminant_volume_finiteness
#check TraceEuclidean.MainFinitenessFramework.classic_fixed_pair
#check TraceEuclidean.MainFinitenessFramework.integral_fixed_pair
#check TraceEuclidean.MainFinitenessFramework.finiteness_classic_fixed_degree_low_rank
#check TraceEuclidean.MainFinitenessFramework.finiteness_classic_fixed_high_rank
#check TraceEuclidean.MainFinitenessFramework.finiteness_classic_fixed_degree
#check TraceEuclidean.MainFinitenessFramework.finiteness_classic_global
#check TraceEuclidean.MainFinitenessFramework.finiteness_integral_fixed_degree_low_rank
#check TraceEuclidean.MainFinitenessFramework.finiteness_integral_fixed_high_rank
#check TraceEuclidean.MainFinitenessFramework.finiteness_integral_fixed_degree
#check TraceEuclidean.MainFinitenessFramework.finiteness_integral_global

#print axioms TraceEuclidean.strictEuclidean_of_radius_lt
#print axioms TraceEuclidean.radius_le_of_strictEuclidean
#print axioms TraceEuclidean.pNormEuclidean_imp_traceEuclidean
#print axioms TraceEuclidean.two_scaled_isometric_iff
#print axioms TraceEuclidean.criticalPoint_hessian_negative
#print axioms TraceEuclidean.finite_positive_of_tendsto_atTop_atBot
#print axioms TraceEuclidean.voronoiVertexNorm_formula
#print axioms TraceEuclidean.caseII_vertexNorm_first
#print axioms TraceEuclidean.caseII_vertexNorm_middle
#print axioms TraceEuclidean.caseI_closed_candidates
#print axioms TraceEuclidean.caseII_closed_candidates
#print axioms TraceEuclidean.mThree_midpoint_obstruction
#print axioms TraceEuclidean.candidateRadii_strictlyBelowTwo
#print axioms TraceEuclidean.isTraceEuclidean_iff_strictEuclidean
#print axioms TraceEuclidean.isClosedTraceEuclidean_iff_closedEuclidean
#print axioms TraceEuclidean.fieldTwoTraceEuclideanRat_iff_real
#print axioms TraceEuclidean.realQuadratic_coveringRadiusSq_caseI
#print axioms TraceEuclidean.realQuadratic_coveringRadiusSq_caseII
#print axioms TraceEuclidean.coordinate_two_trace_euclidean_iff
#print axioms TraceEuclidean.RealQuadraticCoordinateModel.field_two_trace_euclidean_iff
#print axioms TraceEuclidean.realQuadratic_two_trace_euclidean_iff
#print axioms TraceEuclidean.gClassicNat_degree_tail
#print axioms TraceEuclidean.gIntegralNat_degree_tail
#print axioms TraceEuclidean.gClassicNat_rank_tail
#print axioms TraceEuclidean.gIntegralNat_rank_tail
#print axioms TraceEuclidean.gClassicEnvelopeNat_tail
#print axioms TraceEuclidean.gIntegralEnvelopeNat_tail
#print axioms TraceEuclidean.finite_numberFieldCodes_of_discriminant_le
#print axioms TraceEuclidean.finite_objects_of_bounded_volumeIdeal
#print axioms TraceEuclidean.bounded_discriminant_volume_finiteness
#print axioms TraceEuclidean.MainFinitenessFramework.classic_fixed_pair
#print axioms TraceEuclidean.MainFinitenessFramework.integral_fixed_pair
#print axioms TraceEuclidean.MainFinitenessFramework.finiteness_classic_fixed_degree_low_rank
#print axioms TraceEuclidean.MainFinitenessFramework.finiteness_classic_fixed_high_rank
#print axioms TraceEuclidean.MainFinitenessFramework.finiteness_classic_fixed_degree
#print axioms TraceEuclidean.MainFinitenessFramework.finiteness_classic_global
#print axioms TraceEuclidean.MainFinitenessFramework.finiteness_integral_fixed_degree_low_rank
#print axioms TraceEuclidean.MainFinitenessFramework.finiteness_integral_fixed_high_rank
#print axioms TraceEuclidean.MainFinitenessFramework.finiteness_integral_fixed_degree
#print axioms TraceEuclidean.MainFinitenessFramework.finiteness_integral_global
