import TraceEuclidean.V15SectionFourVoightClosed
import TraceEuclidean.V15VoightPolynomialBridge
import TraceEuclidean.V15VoightAllIrreducible
import TraceEuclidean.V15VoightTotalRealityCertificates
import TraceEuclidean.V15VoightNumberFieldBridge

/-! Explicit audit of the native interval-checking trust boundary. -/

#check TraceEuclidean.v15OdlyzkoSinhIntegrand_integrableOn
#check TraceEuclidean.v15OdlyzkoSinhIntegral_zero_hundredth_le
#check TraceEuclidean.v15OdlyzkoSinhIntegral_tail_le
#check TraceEuclidean.v15OdlyzkoCoshIntegral_tail_le
#check TraceEuclidean.V15OdlyzkoNumerical.sinh_core_upper
#check TraceEuclidean.V15OdlyzkoNumerical.cosh_core_upper
#check TraceEuclidean.V15OdlyzkoNumerical.abIntegralCertificate
#check TraceEuclidean.V15MellinGrowth.v15_odlyzkoTable4_of_constructed_explicitFormula
#check TraceEuclidean.v15_odlyzkoTable4ExplicitCorrectionInput_closed
#check TraceEuclidean.v15_odlyzkoTable4DescriptionInput_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_reduced_smallDegreeLiterature
#check TraceEuclidean.v15_classic_pair_mem_of_reduced_smallDegreeLiterature
#check TraceEuclidean.v15_integral_pair_mem_of_reduced_smallDegreeLiterature
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_hunterCertificate_closed
#check TraceEuclidean.v15_classic_pair_mem_of_hunterCertificate_closed
#check TraceEuclidean.v15_integral_pair_mem_of_hunterCertificate_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourToEleven_closed
#check TraceEuclidean.v15_classic_pair_mem_of_degreeFourToEleven_closed
#check TraceEuclidean.v15_integral_pair_mem_of_degreeFourToEleven_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourHunterCertificate_closed
#check TraceEuclidean.v15_classic_pair_mem_of_degreeFourHunterCertificate_closed
#check TraceEuclidean.v15_integral_pair_mem_of_degreeFourHunterCertificate_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourPrimitiveGenerator_closed
#check TraceEuclidean.v15_classic_pair_mem_of_degreeFourPrimitiveGenerator_closed
#check TraceEuclidean.v15_integral_pair_mem_of_degreeFourPrimitiveGenerator_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFiveToEleven_closed
#check TraceEuclidean.v15_classic_pair_mem_of_degreeFiveToEleven_closed
#check TraceEuclidean.v15_integral_pair_mem_of_degreeFiveToEleven_closed
#check TraceEuclidean.v15_voightDiscriminantData_certificate
#check TraceEuclidean.v15_voightPolynomialRowData_certificate
#check TraceEuclidean.v15_degreeFiveToNineMinimumInput_of_voightEnumeration
#check TraceEuclidean.v15_degreeTenRootDiscriminantInput_of_voightEnumeration
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_voightEnumeration_closed
#check TraceEuclidean.v15_classic_pair_mem_of_voightEnumeration_closed
#check TraceEuclidean.v15_integral_pair_mem_of_voightEnumeration_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_publishedVoightBounds_closed
#check TraceEuclidean.v15_classic_pair_mem_of_publishedVoightBounds_closed
#check TraceEuclidean.v15_integral_pair_mem_of_publishedVoightBounds_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_quarticRelativeDifferent_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_relativeDifferentNorm_closed
#check TraceEuclidean.v15_classic_pair_mem_of_quarticRelativeDifferent_closed
#check TraceEuclidean.v15_classic_pair_mem_of_relativeDifferentNorm_closed
#check TraceEuclidean.v15_integral_pair_mem_of_quarticRelativeDifferent_closed
#check TraceEuclidean.v15_integral_pair_mem_of_relativeDifferentNorm_closed
#check TraceEuclidean.v15_voightPolynomialRows_structural_certificate
#check TraceEuclidean.v15_voightPolynomialRows_resultant_certificate
#check TraceEuclidean.v15_voightPolynomialDiscriminantInput
#check TraceEuclidean.v15_voightPolynomialRow_mem_indexedDiscriminantBox_of_valid
#check TraceEuclidean.v15_voightPolynomialRow_mem_indexedDiscriminantBox
#check TraceEuclidean.v15_allVoightPolynomialRows_length
#check TraceEuclidean.v15_voightSpecialEight_no_quartic_divisor
#check TraceEuclidean.v15_voightSpecialEight_irreducible
#check TraceEuclidean.v15_allVoightPolynomialRows_irreducible
#check TraceEuclidean.v15_allVoightPolynomialRows_splits
#check TraceEuclidean.v15_allVoightPolynomialRows_present_totallyRealNumberField

#print axioms TraceEuclidean.v15OdlyzkoSinhIntegrand_integrableOn
#print axioms TraceEuclidean.v15OdlyzkoSinhIntegral_zero_hundredth_le
#print axioms TraceEuclidean.v15OdlyzkoSinhIntegral_tail_le
#print axioms TraceEuclidean.v15OdlyzkoCoshIntegral_tail_le
#print axioms TraceEuclidean.V15OdlyzkoNumerical.sinh_core_upper
#print axioms TraceEuclidean.V15OdlyzkoNumerical.cosh_core_upper
#print axioms TraceEuclidean.V15OdlyzkoNumerical.abIntegralCertificate
#print axioms TraceEuclidean.V15MellinGrowth.v15_odlyzkoTable4_of_constructed_explicitFormula
#print axioms TraceEuclidean.v15_odlyzkoTable4ExplicitCorrectionInput_closed
#print axioms TraceEuclidean.v15_odlyzkoTable4DescriptionInput_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_smallDegreeLiterature
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_reduced_smallDegreeLiterature
#print axioms TraceEuclidean.v15_classic_pair_mem_of_reduced_smallDegreeLiterature
#print axioms TraceEuclidean.v15_integral_pair_mem_of_reduced_smallDegreeLiterature
#print axioms TraceEuclidean.v15_classic_finite_closed
#print axioms TraceEuclidean.v15_integral_finite_closed
#print axioms TraceEuclidean.v15_pnorm_finite_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_hunterCertificate_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_hunterCertificate_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_hunterCertificate_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourToEleven_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_degreeFourToEleven_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_degreeFourToEleven_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourHunterCertificate_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_degreeFourHunterCertificate_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_degreeFourHunterCertificate_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourPrimitiveGenerator_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_degreeFourPrimitiveGenerator_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_degreeFourPrimitiveGenerator_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFiveToEleven_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_degreeFiveToEleven_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_degreeFiveToEleven_closed
#print axioms TraceEuclidean.v15_voightDiscriminantData_certificate
#print axioms TraceEuclidean.v15_voightPolynomialRowData_certificate
#print axioms TraceEuclidean.v15_degreeFiveToNineMinimumInput_of_voightEnumeration
#print axioms TraceEuclidean.v15_degreeTenRootDiscriminantInput_of_voightEnumeration
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_voightEnumeration_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_voightEnumeration_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_voightEnumeration_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_publishedVoightBounds_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_publishedVoightBounds_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_publishedVoightBounds_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_quarticRelativeDifferent_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_relativeDifferentNorm_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_quarticRelativeDifferent_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_relativeDifferentNorm_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_quarticRelativeDifferent_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_relativeDifferentNorm_closed
#print axioms TraceEuclidean.v15_voightPolynomialRows_structural_certificate
#print axioms TraceEuclidean.v15_voightPolynomialRows_resultant_certificate
#print axioms TraceEuclidean.v15_voightPolynomialDiscriminantInput
#print axioms TraceEuclidean.v15_voightPolynomialRow_mem_indexedDiscriminantBox_of_valid
#print axioms TraceEuclidean.v15_voightPolynomialRow_mem_indexedDiscriminantBox
#print axioms TraceEuclidean.v15_allVoightPolynomialRows_length
#print axioms TraceEuclidean.v15_voightSpecialEight_no_quartic_divisor
#print axioms TraceEuclidean.v15_voightSpecialEight_irreducible
#print axioms TraceEuclidean.v15_allVoightPolynomialRows_irreducible
#print axioms TraceEuclidean.v15_allVoightPolynomialRows_splits
#print axioms TraceEuclidean.v15_allVoightPolynomialRows_present_totallyRealNumberField
