import TraceEuclidean.V15SectionFourClosed

/-! Explicit audit of the native interval-checking trust boundary. -/

#check TraceEuclidean.v15OdlyzkoSinhIntegrand_integrableOn
#check TraceEuclidean.v15OdlyzkoSinhIntegral_zero_hundredth_le
#check TraceEuclidean.v15OdlyzkoSinhIntegral_tail_le
#check TraceEuclidean.v15OdlyzkoCoshIntegral_tail_le
#check TraceEuclidean.V15OdlyzkoNumerical.sinh_core_upper
#check TraceEuclidean.V15OdlyzkoNumerical.cosh_core_upper
#check TraceEuclidean.V15OdlyzkoNumerical.abIntegralCertificate
#check TraceEuclidean.V15MellinGrowth.v15_odlyzkoTable4_of_constructed_explicitFormula
#check TraceEuclidean.v15_odlyzkoTable4ExplicitCorrectionInput_closed
#check TraceEuclidean.v15_odlyzkoTable4DescriptionInput_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_reduced_smallDegreeLiterature
#check TraceEuclidean.v15_classic_pair_mem_of_reduced_smallDegreeLiterature
#check TraceEuclidean.v15_integral_pair_mem_of_reduced_smallDegreeLiterature
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_hunterCertificate_closed
#check TraceEuclidean.v15_classic_pair_mem_of_hunterCertificate_closed
#check TraceEuclidean.v15_integral_pair_mem_of_hunterCertificate_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourToEleven_closed
#check TraceEuclidean.v15_classic_pair_mem_of_degreeFourToEleven_closed
#check TraceEuclidean.v15_integral_pair_mem_of_degreeFourToEleven_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourHunterCertificate_closed
#check TraceEuclidean.v15_classic_pair_mem_of_degreeFourHunterCertificate_closed
#check TraceEuclidean.v15_integral_pair_mem_of_degreeFourHunterCertificate_closed
#check TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourPrimitiveGenerator_closed
#check TraceEuclidean.v15_classic_pair_mem_of_degreeFourPrimitiveGenerator_closed
#check TraceEuclidean.v15_integral_pair_mem_of_degreeFourPrimitiveGenerator_closed

#print axioms TraceEuclidean.v15OdlyzkoSinhIntegrand_integrableOn
#print axioms TraceEuclidean.v15OdlyzkoSinhIntegral_zero_hundredth_le
#print axioms TraceEuclidean.v15OdlyzkoSinhIntegral_tail_le
#print axioms TraceEuclidean.v15OdlyzkoCoshIntegral_tail_le
#print axioms TraceEuclidean.V15OdlyzkoNumerical.sinh_core_upper
#print axioms TraceEuclidean.V15OdlyzkoNumerical.cosh_core_upper
#print axioms TraceEuclidean.V15OdlyzkoNumerical.abIntegralCertificate
#print axioms TraceEuclidean.V15MellinGrowth.v15_odlyzkoTable4_of_constructed_explicitFormula
#print axioms TraceEuclidean.v15_odlyzkoTable4ExplicitCorrectionInput_closed
#print axioms TraceEuclidean.v15_odlyzkoTable4DescriptionInput_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_smallDegreeLiterature
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_reduced_smallDegreeLiterature
#print axioms TraceEuclidean.v15_classic_pair_mem_of_reduced_smallDegreeLiterature
#print axioms TraceEuclidean.v15_integral_pair_mem_of_reduced_smallDegreeLiterature
#print axioms TraceEuclidean.v15_classic_finite_closed
#print axioms TraceEuclidean.v15_integral_finite_closed
#print axioms TraceEuclidean.v15_pnorm_finite_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_hunterCertificate_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_hunterCertificate_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_hunterCertificate_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourToEleven_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_degreeFourToEleven_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_degreeFourToEleven_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourHunterCertificate_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_degreeFourHunterCertificate_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_degreeFourHunterCertificate_closed
#print axioms TraceEuclidean.v15_sectionFourDiscriminantInput_of_degreeFourPrimitiveGenerator_closed
#print axioms TraceEuclidean.v15_classic_pair_mem_of_degreeFourPrimitiveGenerator_closed
#print axioms TraceEuclidean.v15_integral_pair_mem_of_degreeFourPrimitiveGenerator_closed
