import TraceEuclidean.SectionFourVoightClosed
import TraceEuclidean.VoightPolynomialBridge
import TraceEuclidean.VoightAllIrreducible
import TraceEuclidean.VoightTotalRealityCertificates
import TraceEuclidean.VoightNumberFieldBridge
import TraceEuclidean.VoightOrderIndexBridge
import TraceEuclidean.VoightSquarefreeIndexOne
import TraceEuclidean.VoightSquarefreeExact
import TraceEuclidean.VoightMaximalOrderExact

/-! Explicit audit of the native interval-checking trust boundary. -/

#check TraceEuclidean.odlyzkoSinhIntegrand_integrableOn
#check TraceEuclidean.odlyzkoSinhIntegral_zero_hundredth_le
#check TraceEuclidean.odlyzkoSinhIntegral_tail_le
#check TraceEuclidean.odlyzkoCoshIntegral_tail_le
#check TraceEuclidean.OdlyzkoNumerical.sinh_core_upper
#check TraceEuclidean.OdlyzkoNumerical.cosh_core_upper
#check TraceEuclidean.OdlyzkoNumerical.abIntegralCertificate
#check TraceEuclidean.MellinGrowth.odlyzkoTable4_of_constructed_explicitFormula
#check TraceEuclidean.odlyzkoTable4ExplicitCorrectionInput_closed
#check TraceEuclidean.odlyzkoTable4DescriptionInput_closed
#check TraceEuclidean.sectionFourDiscriminantInput_of_reduced_smallDegreeLiterature
#check TraceEuclidean.classic_pair_mem_of_reduced_smallDegreeLiterature
#check TraceEuclidean.integral_pair_mem_of_reduced_smallDegreeLiterature
#check TraceEuclidean.sectionFourDiscriminantInput_of_hunterCertificate_closed
#check TraceEuclidean.classic_pair_mem_of_hunterCertificate_closed
#check TraceEuclidean.integral_pair_mem_of_hunterCertificate_closed
#check TraceEuclidean.sectionFourDiscriminantInput_of_degreeFourToEleven_closed
#check TraceEuclidean.classic_pair_mem_of_degreeFourToEleven_closed
#check TraceEuclidean.integral_pair_mem_of_degreeFourToEleven_closed
#check TraceEuclidean.sectionFourDiscriminantInput_of_degreeFourHunterCertificate_closed
#check TraceEuclidean.classic_pair_mem_of_degreeFourHunterCertificate_closed
#check TraceEuclidean.integral_pair_mem_of_degreeFourHunterCertificate_closed
#check TraceEuclidean.sectionFourDiscriminantInput_of_degreeFourPrimitiveGenerator_closed
#check TraceEuclidean.classic_pair_mem_of_degreeFourPrimitiveGenerator_closed
#check TraceEuclidean.integral_pair_mem_of_degreeFourPrimitiveGenerator_closed
#check TraceEuclidean.sectionFourDiscriminantInput_of_degreeFiveToEleven_closed
#check TraceEuclidean.classic_pair_mem_of_degreeFiveToEleven_closed
#check TraceEuclidean.integral_pair_mem_of_degreeFiveToEleven_closed
#check TraceEuclidean.voightDiscriminantData_certificate
#check TraceEuclidean.voightPolynomialRowData_certificate
#check TraceEuclidean.degreeFiveToNineMinimumInput_of_voightEnumeration
#check TraceEuclidean.degreeTenRootDiscriminantInput_of_voightEnumeration
#check TraceEuclidean.sectionFourDiscriminantInput_of_voightEnumeration_closed
#check TraceEuclidean.classic_pair_mem_of_voightEnumeration_closed
#check TraceEuclidean.integral_pair_mem_of_voightEnumeration_closed
#check TraceEuclidean.sectionFourDiscriminantInput_of_publishedVoightBounds_closed
#check TraceEuclidean.classic_pair_mem_of_publishedVoightBounds_closed
#check TraceEuclidean.integral_pair_mem_of_publishedVoightBounds_closed
#check TraceEuclidean.sectionFourDiscriminantInput_of_quarticRelativeDifferent_closed
#check TraceEuclidean.sectionFourDiscriminantInput_of_relativeDifferentNorm_closed
#check TraceEuclidean.classic_pair_mem_of_quarticRelativeDifferent_closed
#check TraceEuclidean.classic_pair_mem_of_relativeDifferentNorm_closed
#check TraceEuclidean.integral_pair_mem_of_quarticRelativeDifferent_closed
#check TraceEuclidean.integral_pair_mem_of_relativeDifferentNorm_closed
#check TraceEuclidean.voightPolynomialRows_structural_certificate
#check TraceEuclidean.voightPolynomialRows_resultant_certificate
#check TraceEuclidean.voightPolynomialDiscriminantInput
#check TraceEuclidean.voightPolynomialRow_mem_indexedDiscriminantBox_of_valid
#check TraceEuclidean.voightPolynomialRow_mem_indexedDiscriminantBox
#check TraceEuclidean.allVoightPolynomialRows_length
#check TraceEuclidean.voightSpecialEight_no_quartic_divisor
#check TraceEuclidean.voightSpecialEight_irreducible
#check TraceEuclidean.allVoightPolynomialRows_irreducible
#check TraceEuclidean.allVoightPolynomialRows_splits
#check TraceEuclidean.allVoightPolynomialRows_present_totallyRealNumberField
#check TraceEuclidean.allVoightPolynomialRows_present_indexedTotallyRealNumberField
#check TraceEuclidean.voightSquarefreeIndexOneRows_length
#check TraceEuclidean.voightSquarefreeIndexOneRows_present_exactTotallyRealNumberField
#check TraceEuclidean.voightSquarefreeNontrivialIndexCertificates_valid
#check TraceEuclidean.voightSquarefreeNontrivialIndexCertificates_complete
#check TraceEuclidean.voightSquarefreeNontrivialIndexRows_length
#check TraceEuclidean.voightSquarefreeNontrivialIndexRows_present_exactTotallyRealNumberField
#check TraceEuclidean.voightSquarefreeFieldDiscriminantRows_length
#check TraceEuclidean.voightSquarefreeFieldDiscriminantRows_present_exactTotallyRealNumberField

#print axioms TraceEuclidean.odlyzkoSinhIntegrand_integrableOn
#print axioms TraceEuclidean.odlyzkoSinhIntegral_zero_hundredth_le
#print axioms TraceEuclidean.odlyzkoSinhIntegral_tail_le
#print axioms TraceEuclidean.odlyzkoCoshIntegral_tail_le
#print axioms TraceEuclidean.OdlyzkoNumerical.sinh_core_upper
#print axioms TraceEuclidean.OdlyzkoNumerical.cosh_core_upper
#print axioms TraceEuclidean.OdlyzkoNumerical.abIntegralCertificate
#print axioms TraceEuclidean.MellinGrowth.odlyzkoTable4_of_constructed_explicitFormula
#print axioms TraceEuclidean.odlyzkoTable4ExplicitCorrectionInput_closed
#print axioms TraceEuclidean.odlyzkoTable4DescriptionInput_closed
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_smallDegreeLiterature
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_reduced_smallDegreeLiterature
#print axioms TraceEuclidean.classic_pair_mem_of_reduced_smallDegreeLiterature
#print axioms TraceEuclidean.integral_pair_mem_of_reduced_smallDegreeLiterature
#print axioms TraceEuclidean.classic_finite_closed
#print axioms TraceEuclidean.integral_finite_closed
#print axioms TraceEuclidean.pnorm_finite_closed
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_hunterCertificate_closed
#print axioms TraceEuclidean.classic_pair_mem_of_hunterCertificate_closed
#print axioms TraceEuclidean.integral_pair_mem_of_hunterCertificate_closed
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_degreeFourToEleven_closed
#print axioms TraceEuclidean.classic_pair_mem_of_degreeFourToEleven_closed
#print axioms TraceEuclidean.integral_pair_mem_of_degreeFourToEleven_closed
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_degreeFourHunterCertificate_closed
#print axioms TraceEuclidean.classic_pair_mem_of_degreeFourHunterCertificate_closed
#print axioms TraceEuclidean.integral_pair_mem_of_degreeFourHunterCertificate_closed
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_degreeFourPrimitiveGenerator_closed
#print axioms TraceEuclidean.classic_pair_mem_of_degreeFourPrimitiveGenerator_closed
#print axioms TraceEuclidean.integral_pair_mem_of_degreeFourPrimitiveGenerator_closed
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_degreeFiveToEleven_closed
#print axioms TraceEuclidean.classic_pair_mem_of_degreeFiveToEleven_closed
#print axioms TraceEuclidean.integral_pair_mem_of_degreeFiveToEleven_closed
#print axioms TraceEuclidean.voightDiscriminantData_certificate
#print axioms TraceEuclidean.voightPolynomialRowData_certificate
#print axioms TraceEuclidean.degreeFiveToNineMinimumInput_of_voightEnumeration
#print axioms TraceEuclidean.degreeTenRootDiscriminantInput_of_voightEnumeration
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_voightEnumeration_closed
#print axioms TraceEuclidean.classic_pair_mem_of_voightEnumeration_closed
#print axioms TraceEuclidean.integral_pair_mem_of_voightEnumeration_closed
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_publishedVoightBounds_closed
#print axioms TraceEuclidean.classic_pair_mem_of_publishedVoightBounds_closed
#print axioms TraceEuclidean.integral_pair_mem_of_publishedVoightBounds_closed
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_quarticRelativeDifferent_closed
#print axioms TraceEuclidean.sectionFourDiscriminantInput_of_relativeDifferentNorm_closed
#print axioms TraceEuclidean.classic_pair_mem_of_quarticRelativeDifferent_closed
#print axioms TraceEuclidean.classic_pair_mem_of_relativeDifferentNorm_closed
#print axioms TraceEuclidean.integral_pair_mem_of_quarticRelativeDifferent_closed
#print axioms TraceEuclidean.integral_pair_mem_of_relativeDifferentNorm_closed
#print axioms TraceEuclidean.voightPolynomialRows_structural_certificate
#print axioms TraceEuclidean.voightPolynomialRows_resultant_certificate
#print axioms TraceEuclidean.voightPolynomialDiscriminantInput
#print axioms TraceEuclidean.voightPolynomialRow_mem_indexedDiscriminantBox_of_valid
#print axioms TraceEuclidean.voightPolynomialRow_mem_indexedDiscriminantBox
#print axioms TraceEuclidean.allVoightPolynomialRows_length
#print axioms TraceEuclidean.voightSpecialEight_no_quartic_divisor
#print axioms TraceEuclidean.voightSpecialEight_irreducible
#print axioms TraceEuclidean.allVoightPolynomialRows_irreducible
#print axioms TraceEuclidean.allVoightPolynomialRows_splits
#print axioms TraceEuclidean.allVoightPolynomialRows_present_totallyRealNumberField
#print axioms TraceEuclidean.allVoightPolynomialRows_present_indexedTotallyRealNumberField
#print axioms TraceEuclidean.voightSquarefreeIndexOneRows_length
#print axioms TraceEuclidean.voightSquarefreeIndexOneRows_present_exactTotallyRealNumberField
#print axioms TraceEuclidean.voightSquarefreeNontrivialIndexCertificates_valid
#print axioms TraceEuclidean.voightSquarefreeNontrivialIndexCertificates_complete
#print axioms TraceEuclidean.voightSquarefreeNontrivialIndexRows_length
#print axioms TraceEuclidean.voightSquarefreeNontrivialIndexRows_present_exactTotallyRealNumberField
#print axioms TraceEuclidean.voightSquarefreeFieldDiscriminantRows_length
#print axioms TraceEuclidean.voightSquarefreeFieldDiscriminantRows_present_exactTotallyRealNumberField
#print axioms TraceEuclidean.voightNonsquarefreeExactFieldCertificates_length
#print axioms TraceEuclidean.voightNonsquarefreeExactFieldCertificates_complete
#print axioms TraceEuclidean.voightNonsquarefreeFieldDiscriminantRows_present_exactTotallyRealNumberField
#print axioms TraceEuclidean.allVoightPolynomialRows_present_exactTotallyRealNumberField
