import TraceEuclidean.DegreeSevenRolleStageSixStrongCompactCompleteness
import TraceEuclidean.DegreeSevenRolleStageSixPiecewise
import TraceEuclidean.DegreeSevenRolleStageSixPiecewiseCompleteness
import TraceEuclidean.DegreeSevenRolleStageSevenScaled
import TraceEuclidean.DegreeSevenRolleStageSevenCompleteness
import TraceEuclidean.DegreeSevenRolleStageSevenRejected
import TraceEuclidean.DegreeSevenRolleStageSevenRejectedScaled
import TraceEuclidean.DegreeSevenRolleStageSevenPilot
import TraceEuclidean.DegreeSevenRolleStageSevenPilotClosure
import TraceEuclidean.DegreeSevenRolleStageSevenPrefix100Reducibility
import TraceEuclidean.DegreeSevenSurvivorDiscriminants
import TraceEuclidean.DegreeSevenRows200To299SurvivorDiscriminants

/-!
# Degree-seven sixth-stage boundary audit

This focused audit checks the data-independent bridge from a valid quintic
root certificate to the exact `a1` interval, the integer root-isolation
certificates, and the complete generated Stage Six family cover.
-/

#check TraceEuclidean.DegreeSevenStageSixEntry
#check TraceEuclidean.DegreeSevenStageSixEntry.Valid
#check TraceEuclidean.DegreeSevenStageSixEntry.a1Candidates
#check TraceEuclidean.degreeSeven_firstDerivativeStage_eq
#check TraceEuclidean.degreeSeven_sextic_derivative_eq
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem_of_valid
#check TraceEuclidean.DegreeSevenStageFiveEntry.a1InterlacingCandidates
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem_of_stageFive_valid
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem
#check TraceEuclidean.DegreeSevenStageFiveEntry.a0GlobalCandidates
#check TraceEuclidean.degreeSeven_realPolynomial_eq_dense
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a0_mem_of_stageFive
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_allCoefficients_mem
#check TraceEuclidean.DegreeSevenStageFiveScaledRoots.ArithmeticValid
#check TraceEuclidean.DegreeSevenStageFiveScaledRoots.valid_of_arithmeticValid
#check TraceEuclidean.DegreeSevenStageSixRefinedCriticalSign.ArithmeticValid
#check TraceEuclidean.DegreeSevenStageSixRefinedCriticalSign.valid_of_arithmeticValid
#check TraceEuclidean.DegreeSevenStageSixStrongCompactCoverage.Valid
#check TraceEuclidean.degreeSevenStageSixStrongCompactCoverages_valid
#check TraceEuclidean.degreeSevenStageSixStrongCompactCoverages_parents
#check TraceEuclidean.degreeSevenStageSixStrongCompactCoverage_count
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_complete
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_complete_with_top
#check TraceEuclidean.DegreeSevenStageSixPiecewiseCoverage.CoversFrom
#check TraceEuclidean.DegreeSevenStageSixPiecewiseCoverage.exists_piece_of_coversFrom
#check TraceEuclidean.DegreeSevenStageSixPiecewiseCoverage.hunter_a1_mem
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_piecewise_complete
#check TraceEuclidean.DegreeSevenStageSevenEntry.Valid
#check TraceEuclidean.DegreeSevenStageSevenEntry.a0Candidates
#check TraceEuclidean.DegreeSevenStageSevenScaledEntry.ArithmeticValid
#check TraceEuclidean.DegreeSevenStageSevenScaledEntry.valid_of_arithmeticValid
#check TraceEuclidean.degreeSeven_minimumHunterCandidate_a0_mem_of_stageSeven
#check TraceEuclidean.degreeSeven_firstDerivativeStage_separable
#check TraceEuclidean.degreeSeven_stageSevenMultipleRootWitness_not_hunter
#check TraceEuclidean.DegreeSevenStageSevenCriticalSignWitness.not_splits_and_separable
#check TraceEuclidean.degreeSeven_stageSevenCriticalSignWitness_not_hunter
#check TraceEuclidean.DegreeSevenStageSevenScaledCriticalSignWitness.ArithmeticValid
#check TraceEuclidean.DegreeSevenStageSevenScaledCriticalSignWitness.valid_of_arithmeticValid
#check TraceEuclidean.degreeSevenStageSevenScaledPilot_valid
#check TraceEuclidean.degreeSevenStageSevenScaledPilot_a0Candidates_empty
#check TraceEuclidean.degreeSevenStageSevenMultipleRootPilot_valid
#check TraceEuclidean.degreeSevenStageSevenCriticalSignPilot_valid
#check TraceEuclidean.degreeSevenStageSevenPilot_a0_mem
#check TraceEuclidean.degreeSevenStageSevenPilot_prefix_complete
#check TraceEuclidean.degreeSevenStageSevenPilot_prefix_classified
#check TraceEuclidean.degreeSevenStageSevenPilot_excludes_firstTen
#check TraceEuclidean.DegreeSevenStageSixScaledFamily.a1Candidates_eq_scaledA1Candidates
#check TraceEuclidean.mem_integerIccList_iff_mem_integerIcc
#check TraceEuclidean.degreeSevenStageSevenClassificationsPrefix100_valid
#check TraceEuclidean.degreeSevenStageSevenClassificationsPrefix100_count
#check TraceEuclidean.degreeSevenStageSevenScaledPrefix100_count
#check TraceEuclidean.degreeSevenStageSevenMultipleRootPrefix100_count
#check TraceEuclidean.degreeSevenStageSevenCriticalSignPrefix100_count
#check TraceEuclidean.degreeSevenStageSevenPrefix100_keyLists_eq
#check TraceEuclidean.degreeSevenStageSevenPrefix100_keyFinsets_eq
#check TraceEuclidean.degreeSevenStageSevenPrefix100_a0_mem
#check TraceEuclidean.degreeSevenStageSevenFactorCertificatesPrefix100_count
#check TraceEuclidean.degreeSevenStageSevenFactorCertificatesPrefix100_complete
#check TraceEuclidean.degreeSevenStageSevenScaledPrefix100_not_hunter
#check TraceEuclidean.degreeSevenStageSevenPrefix100_not_hunter_of_prefix_mem
#check TraceEuclidean.degreeSevenStageSevenPrefix100_excludes_first100
#check TraceEuclidean.degreeSevenSurvivorDiscriminantCertificatesRows100To199_count
#check TraceEuclidean.degreeSevenStageSevenRows100To199_reduces_to_nine
#check TraceEuclidean.degreeSevenRows100To199_fieldDiscriminant_lowerBound_of_survivor
#check TraceEuclidean.degreeSevenStageSevenRows100To199_fieldDiscriminant_lowerBound
#check TraceEuclidean.degreeSevenStageSevenRows100To199_excludes_discriminant_lt
#check TraceEuclidean.degreeSevenStageSevenRows200To299_reduces_to_ninetyFour
#check TraceEuclidean.DegreeSevenRows200To299ExceptionalMaximalOrder.fieldDiscriminant_lowerBound
#check TraceEuclidean.degreeSevenStageSevenRows200To299_fieldDiscriminant_lowerBound
#check TraceEuclidean.degreeSevenStageSevenRows200To299_excludes_discriminant_lt

#print axioms TraceEuclidean.degreeSeven_firstDerivativeStage_eq
#print axioms TraceEuclidean.degreeSeven_sextic_derivative_eq
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem_of_valid
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem_of_stageFive_valid
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a1_mem
#print axioms TraceEuclidean.degreeSeven_realPolynomial_eq_dense
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a0_mem_of_stageFive
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_allCoefficients_mem
#print axioms TraceEuclidean.DegreeSevenStageFiveScaledRoots.valid_of_arithmeticValid
#print axioms TraceEuclidean.DegreeSevenStageSixRefinedCriticalSign.valid_of_arithmeticValid
#print axioms TraceEuclidean.degreeSevenStageSixStrongCompactCoverages_valid
#print axioms TraceEuclidean.degreeSevenStageSixStrongCompactCoverages_parents
#print axioms TraceEuclidean.degreeSevenStageSixStrongCompactCoverage_count
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_complete
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_complete_with_top
#print axioms TraceEuclidean.DegreeSevenStageSixPiecewiseCoverage.exists_piece_of_coversFrom
#print axioms TraceEuclidean.DegreeSevenStageSixPiecewiseCoverage.hunter_a1_mem
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_stageSix_piecewise_complete
#print axioms TraceEuclidean.DegreeSevenStageSevenScaledEntry.valid_of_arithmeticValid
#print axioms TraceEuclidean.degreeSeven_minimumHunterCandidate_a0_mem_of_stageSeven
#print axioms TraceEuclidean.degreeSeven_firstDerivativeStage_separable
#print axioms TraceEuclidean.degreeSeven_stageSevenMultipleRootWitness_not_hunter
#print axioms TraceEuclidean.DegreeSevenStageSevenCriticalSignWitness.not_splits_and_separable
#print axioms TraceEuclidean.degreeSeven_stageSevenCriticalSignWitness_not_hunter
#print axioms TraceEuclidean.DegreeSevenStageSevenScaledCriticalSignWitness.valid_of_arithmeticValid
#print axioms TraceEuclidean.degreeSevenStageSevenScaledPilot_valid
#print axioms TraceEuclidean.degreeSevenStageSevenScaledPilot_a0Candidates_empty
#print axioms TraceEuclidean.degreeSevenStageSevenMultipleRootPilot_valid
#print axioms TraceEuclidean.degreeSevenStageSevenCriticalSignPilot_valid
#print axioms TraceEuclidean.degreeSevenStageSevenPilot_a0_mem
#print axioms TraceEuclidean.degreeSevenStageSevenPilot_prefix_complete
#print axioms TraceEuclidean.degreeSevenStageSevenPilot_prefix_classified
#print axioms TraceEuclidean.degreeSevenStageSevenPilot_excludes_firstTen
#print axioms TraceEuclidean.DegreeSevenStageSixScaledFamily.a1Candidates_eq_scaledA1Candidates
#print axioms TraceEuclidean.mem_integerIccList_iff_mem_integerIcc
#print axioms TraceEuclidean.degreeSevenStageSevenClassificationsPrefix100_valid
#print axioms TraceEuclidean.degreeSevenStageSevenPrefix100_keyLists_eq
#print axioms TraceEuclidean.degreeSevenStageSevenPrefix100_keyFinsets_eq
#print axioms TraceEuclidean.degreeSevenStageSevenPrefix100_a0_mem
#print axioms TraceEuclidean.degreeSevenStageSevenFactorCertificatesPrefix100_complete
#print axioms TraceEuclidean.degreeSevenStageSevenScaledPrefix100_not_hunter
#print axioms TraceEuclidean.degreeSevenStageSevenPrefix100_not_hunter_of_prefix_mem
#print axioms TraceEuclidean.degreeSevenStageSevenPrefix100_excludes_first100
#print axioms TraceEuclidean.degreeSevenStageSevenRows100To199_reduces_to_nine
#print axioms TraceEuclidean.degreeSevenRows100To199_fieldDiscriminant_lowerBound_of_survivor
#print axioms TraceEuclidean.degreeSevenStageSevenRows100To199_fieldDiscriminant_lowerBound
#print axioms TraceEuclidean.degreeSevenStageSevenRows100To199_excludes_discriminant_lt
#print axioms TraceEuclidean.degreeSevenStageSevenRows200To299_reduces_to_ninetyFour
#print axioms TraceEuclidean.DegreeSevenRows200To299ExceptionalMaximalOrder.fieldDiscriminant_lowerBound
#print axioms TraceEuclidean.degreeSevenStageSevenRows200To299_fieldDiscriminant_lowerBound
#print axioms TraceEuclidean.degreeSevenStageSevenRows200To299_excludes_discriminant_lt
