import TraceEuclidean.TraceProductRealization

#print axioms TraceEuclidean.GlobalLatticePresentation.realProductEmbeddingMap_rationalPoint
#print axioms TraceEuclidean.GlobalLatticePresentation.productTraceCost_realProductEmbeddingMap
#print axioms TraceEuclidean.GlobalLatticePresentation.realProductEmbeddingMap_injective
#print axioms TraceEuclidean.GlobalLatticePresentation.realProductSpace_finrank
#print axioms TraceEuclidean.GlobalLatticePresentation.realProductEmbeddingEquiv
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorProductEmbeddingEquiv_rationalPoint
#print axioms TraceEuclidean.GlobalLatticePresentation.productTraceCost_tensorProductEmbeddingEquiv
#print axioms TraceEuclidean.GlobalLatticePresentation.productIntegralLattice_eq_tensorImage
