import TraceEuclidean.TraceTensorCoordinates

#print axioms TraceEuclidean.GlobalLatticePresentation.realIntegralLattice_eq_rational_range
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorIntegralLattice_eq_range
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorCoordinateFin_int_range
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorCoordinateFin_rat_range
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorCoordinateFormFin_apply
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorCoordinateFormFin_posDef
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorCoordinateFormFin_int
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorTraceNearestValue_domain
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorTraceNearestValue_eq_real
#print axioms TraceEuclidean.GlobalLatticePresentation.tensorTraceNearestValue_fin_coordinates
