import TraceEuclidean.TraceCoordinates

-- The coordinate lemmas for the manuscript's trace-lattice proposition.
#print axioms TraceEuclidean.GlobalLatticePresentation.traceCoordinateIndex_card
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinate_int_range
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinateFin_int_range
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinate_rat_range
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinateFin_rat_range
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinateForm_posDef
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinateFormFin_posDef
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinateForm_rat_apply
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinateFormFin_rat_apply
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinateForm_int
#print axioms TraceEuclidean.GlobalLatticePresentation.realCoordinateFormFin_int
#print axioms TraceEuclidean.GlobalLatticePresentation.realTraceNearestValue_domain
#print axioms TraceEuclidean.GlobalLatticePresentation.realTraceNearestValue_coordinates
#print axioms TraceEuclidean.GlobalLatticePresentation.realTraceNearestValue_fin_coordinates
