import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.NumberTheory.NumberField.Discriminant.Basic

/-!
# Transporting an explicit AdjoinRoot discriminant certificate

This module records the general algebraic bridge needed by the finite Voight
enumeration.  A certificate may compute the discriminant of the concrete
`AdjoinRoot` model.  If an algebraic integer generates an arbitrary number
field and has the same integral minimal polynomial, the resulting algebra
equivalence transports that discriminant to the arbitrary field.
-/

namespace TraceEuclidean

open Polynomial

noncomputable section

/-- Transport a discriminant equality from a certified `AdjoinRoot` model to
an arbitrary number field generated by an algebraic integer with the same
integral minimal polynomial. -/
theorem numberField_discr_eq_of_adjoinRoot_model
    {T : ℤ[X]}
    [hirr : Fact (Irreducible (T.map (algebraMap ℤ ℚ)))]
    {d : ℤ}
    (hmodel : NumberField.discr
      (AdjoinRoot (T.map (algebraMap ℤ ℚ))) = d)
    {K : Type*} [Field K] [NumberField K]
    (a : NumberField.RingOfIntegers K)
    (hpoly : T = minpoly ℤ (a : K))
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤) :
    NumberField.discr K = d := by
  have hminQ : T.map (algebraMap ℤ ℚ) = minpoly ℚ (a : K) := by
    calc
      T.map (algebraMap ℤ ℚ) =
          (minpoly ℤ (a : K)).map (algebraMap ℤ ℚ) := by
        rw [hpoly]
      _ = minpoly ℚ (a : K) :=
        (minpoly.isIntegrallyClosed_eq_field_fractions' ℚ
          a.isIntegral_coe).symm
  have haQ : IsIntegral ℚ (a : K) :=
    Algebra.IsIntegral.isIntegral (a : K)
  let e : AdjoinRoot (T.map (algebraMap ℤ ℚ)) ≃ₐ[ℚ] K :=
    (AdjoinRoot.algEquivOfEq ℚ
      (T.map (algebraMap ℤ ℚ)) (minpoly ℚ (a : K)) hminQ).trans
      ((IntermediateField.adjoinRootEquivAdjoin ℚ haQ).trans
        ((IntermediateField.equivOfEq hgen).trans
          IntermediateField.topEquiv))
  calc
    NumberField.discr K =
        NumberField.discr (AdjoinRoot (T.map (algebraMap ℤ ℚ))) :=
      (NumberField.discr_eq_discr_of_algEquiv
        (AdjoinRoot (T.map (algebraMap ℤ ℚ))) e).symm
    _ = d := hmodel

end


end TraceEuclidean
