import TraceEuclidean.DegreeFiveFrontierArithmetic
import TraceEuclidean.DegreeFiveRolleStageFiveCompleteness

/-!
# Proof-bearing classification cases for the degree-five frontier

Each final Rolle-frontier coefficient list is classified by one of three
constructors.  The constructor stores the proof needed by the number-field
argument, so the final completeness theorem does not trust an external tag.
-/

namespace TraceEuclidean

open Polynomial

universe u

/-- The maximal-order certificate for a critical row, transported to every
number field generated by an algebraic integer with that minimal polynomial. -/
def DegreeFiveCriticalTransport
    (row : VoightPolynomialRow) : Prop :=
  ∀ (K : Type*) [Field K] [NumberField K]
    (a : NumberField.RingOfIntegers K),
    row.polynomial = minpoly ℤ (a : K) →
    IntermediateField.adjoin ℚ {(a : K)} = ⊤ →
    NumberField.discr K = (row.fieldDiscriminant : ℤ)

/-- A final quintic coefficient list together with the proof that disposes
of it in the minimum-discriminant argument. -/
inductive DegreeFiveCertifiedCase where
  | reducible (coefficients : List ℤ)
      (notIrreducible :
        ¬Irreducible (polynomialOfCoefficients coefficients))
  | safe (row : VoightPolynomialRow)
      (positive : 0 < row.fieldDiscriminant)
      (properties :
        row.polynomial.discr = (row.fieldDiscriminant : ℤ) ∧
          discriminantQuotientSafe 14641
            row.fieldDiscriminant = true)
  | critical (row : VoightPolynomialRow)
      (lowerBound : 14641 ≤ row.fieldDiscriminant)
      (transport : DegreeFiveCriticalTransport.{u} row)

namespace DegreeFiveCertifiedCase

def coefficients : DegreeFiveCertifiedCase.{u} → List ℤ
  | .reducible values _ => values
  | .safe row _ _ => row.coefficients
  | .critical row _ _ => row.coefficients

theorem row_polynomial_eq_polynomialOfCoefficients
    (row : VoightPolynomialRow) :
    row.polynomial = polynomialOfCoefficients row.coefficients := by
  rfl

/-- Every proof-bearing case forces the degree-five field discriminant to
have absolute value at least `14641`. -/
theorem fieldDiscriminant_lowerBound
    {K : Type u} [Field K] [NumberField K]
    {f : ℤ[X]}
    (hfield : HunterFieldPolynomialCandidate K 5 67 f)
    (certificate : DegreeFiveCertifiedCase.{u})
    (hcoefficients : certificate.coefficients =
      [f.coeff 0, f.coeff 1, f.coeff 2,
        f.coeff 3, f.coeff 4, 1]) :
    14641 ≤ (NumberField.discr K).natAbs := by
  have hf :
      f = polynomialOfCoefficients
        [f.coeff 0, f.coeff 1, f.coeff 2,
          f.coeff 3, f.coeff 4, 1] :=
    degreeFive_eq_polynomialOfCoefficients
      hfield.1.1 hfield.1.2.2.1
  rcases hfield.2 with ⟨a, hgen, hminpoly, index, hindex, hrelation⟩
  cases certificate with
  | reducible coefficients hnot =>
      simp only [DegreeFiveCertifiedCase.coefficients] at hcoefficients
      exfalso
      apply hnot
      have hpoly :
          polynomialOfCoefficients coefficients = f := by
        rw [hcoefficients, ← hf]
      rw [hpoly]
      exact hfield.1.2.1
  | safe row hpositive hproperties =>
      simp only [DegreeFiveCertifiedCase.coefficients] at hcoefficients
      have hrowPolynomial : row.polynomial = f := by
        rw [row_polynomial_eq_polynomialOfCoefficients,
          hcoefficients, ← hf]
      have hsafeRelation :
          (row.fieldDiscriminant : ℤ) =
            (index : ℤ) ^ 2 * NumberField.discr K := by
        rw [← hproperties.1, hrowPolynomial]
        exact hrelation
      exact lower_bound_of_discriminantQuotientSafe
        hpositive hproperties.2 hindex hsafeRelation
  | critical row hlower htransport =>
      simp only [DegreeFiveCertifiedCase.coefficients] at hcoefficients
      have hrowPolynomial : row.polynomial = f := by
        rw [row_polynomial_eq_polynomialOfCoefficients,
          hcoefficients, ← hf]
      have hdisc :
          NumberField.discr K = (row.fieldDiscriminant : ℤ) :=
        htransport K a (hrowPolynomial.trans hminpoly) hgen
      rw [hdisc]
      simpa using hlower

end DegreeFiveCertifiedCase
end TraceEuclidean
