import TraceEuclidean.VoightCoefficientPruning

/-!
# Generated degree-seven Rolle certificates: quadratic stage

This file is generated by
`tools/generate_degree_seven_rolle_stage_three.py`.  It contains exact
rational isolating intervals for the two roots of every possible normalized
fifth derivative `21*x^2 + 6*a6*x + a5` below the degree-seven minimum.

All checks use ordinary kernel reduction and exact rational arithmetic.
-/

namespace TraceEuclidean

set_option linter.style.longLine false

structure DegreeSevenStageThreeEntry where
  a6 : ℤ
  a5 : ℤ
  firstRoot : RationalRootInterval
  secondRoot : RationalRootInterval
deriving DecidableEq, Repr

namespace DegreeSevenStageThreeEntry

def derivativeCoefficients (entry : DegreeSevenStageThreeEntry) : List ℤ :=
  [entry.a5, 6 * entry.a6, 21]

def baseCoefficients (entry : DegreeSevenStageThreeEntry) : List ℤ :=
  [0, 5 * entry.a5, 15 * entry.a6, 35]

def rootIntervals (entry : DegreeSevenStageThreeEntry) :
    List RationalRootInterval :=
  [entry.firstRoot, entry.secondRoot]

def Valid (entry : DegreeSevenStageThreeEntry) : Prop :=
  GeneralRationalRootIntervalCertificate.Valid 2
    entry.derivativeCoefficients entry.rootIntervals

def a4Candidates (entry : DegreeSevenStageThreeEntry) : Finset ℤ :=
  cubicTranslationCandidates entry.baseCoefficients
    (-16) 16 entry.firstRoot entry.secondRoot

end DegreeSevenStageThreeEntry

def degreeSevenStageThreeEntries :
    List DegreeSevenStageThreeEntry :=
  [
    ⟨(-3 : ℤ), (-9 : ℤ), ⟨(-40 : ℚ) / 113, (-23 : ℚ) / 65⟩, ⟨(132 : ℚ) / 109, (109 : ℚ) / 90⟩⟩,
    ⟨(-3 : ℤ), (-8 : ℤ), ⟨(-31 : ℚ) / 96, (-41 : ℚ) / 127⟩, ⟨(105 : ℚ) / 89, (59 : ℚ) / 50⟩⟩,
    ⟨(-3 : ℤ), (-7 : ℤ), ⟨(-52 : ℚ) / 179, (-9 : ℚ) / 31⟩, ⟨(70 : ℚ) / 61, (101 : ℚ) / 88⟩⟩,
    ⟨(-3 : ℤ), (-6 : ℤ), ⟨(-39 : ℚ) / 152, (-10 : ℚ) / 39⟩, ⟨(49 : ℚ) / 44, (186 : ℚ) / 167⟩⟩,
    ⟨(-3 : ℤ), (-5 : ℤ), ⟨(-19 : ℚ) / 86, (-17 : ℚ) / 77⟩, ⟨(83 : ℚ) / 77, (69 : ℚ) / 64⟩⟩,
    ⟨(-3 : ℤ), (-4 : ℤ), ⟨(-11 : ℚ) / 60, (-13 : ℚ) / 71⟩, ⟨(181 : ℚ) / 174, (155 : ℚ) / 149⟩⟩,
    ⟨(-3 : ℤ), (-3 : ℤ), ⟨(-4103 : ℚ) / 28672, (-4089 : ℚ) / 28672⟩, ⟨(4095 : ℚ) / 4096, (4097 : ℚ) / 4096⟩⟩,
    ⟨(-3 : ℤ), (-2 : ℤ), ⟨(-23 : ℚ) / 231, (-22 : ℚ) / 221⟩, ⟨(22 : ℚ) / 23, (199 : ℚ) / 208⟩⟩,
    ⟨(-3 : ℤ), (-1 : ℤ), ⟨(-11 : ℚ) / 210, (-10 : ℚ) / 191⟩, ⟨(211 : ℚ) / 232, (201 : ℚ) / 221⟩⟩,
    ⟨(-3 : ℤ), (0 : ℤ), ⟨(-1 : ℚ) / 4096, (1 : ℚ) / 4096⟩, ⟨(24569 : ℚ) / 28672, (24583 : ℚ) / 28672⟩⟩,
    ⟨(-3 : ℤ), (1 : ℤ), ⟨(4 : ℚ) / 67, (7 : ℚ) / 117⟩, ⟨(59 : ℚ) / 74, (63 : ℚ) / 79⟩⟩,
    ⟨(-3 : ℤ), (2 : ℤ), ⟨(8 : ℚ) / 61, (13 : ℚ) / 99⟩, ⟨(45 : ℚ) / 62, (53 : ℚ) / 73⟩⟩,
    ⟨(-3 : ℤ), (3 : ℤ), ⟨(12 : ℚ) / 53, (29 : ℚ) / 128⟩, ⟨(29 : ℚ) / 46, (70 : ℚ) / 111⟩⟩,
    ⟨(-2 : ℤ), (-12 : ℤ), ⟨(-58 : ℚ) / 111, (-35 : ℚ) / 67⟩, ⟨(35 : ℚ) / 32, (163 : ℚ) / 149⟩⟩,
    ⟨(-2 : ℤ), (-11 : ℤ), ⟨(-33 : ℚ) / 67, (-32 : ℚ) / 65⟩, ⟨(317 : ℚ) / 298, (50 : ℚ) / 47⟩⟩,
    ⟨(-2 : ℤ), (-10 : ℤ), ⟨(-95 : ℚ) / 206, (-89 : ℚ) / 193⟩, ⟨(127 : ℚ) / 123, (95 : ℚ) / 92⟩⟩,
    ⟨(-2 : ℤ), (-9 : ℤ), ⟨(-12295 : ℚ) / 28672, (-12281 : ℚ) / 28672⟩, ⟨(4095 : ℚ) / 4096, (4097 : ℚ) / 4096⟩⟩,
    ⟨(-2 : ℤ), (-8 : ℤ), ⟨(-43 : ℚ) / 109, (-28 : ℚ) / 71⟩, ⟨(113 : ℚ) / 117, (85 : ℚ) / 88⟩⟩,
    ⟨(-2 : ℤ), (-7 : ℤ), ⟨(-19 : ℚ) / 53, (-81 : ℚ) / 226⟩, ⟨(53 : ℚ) / 57, (93 : ℚ) / 100⟩⟩,
    ⟨(-2 : ℤ), (-6 : ℤ), ⟨(-33 : ℚ) / 103, (-41 : ℚ) / 128⟩, ⟨(107 : ℚ) / 120, (33 : ℚ) / 37⟩⟩,
    ⟨(-2 : ℤ), (-5 : ℤ), ⟨(-47 : ℚ) / 168, (-40 : ℚ) / 143⟩, ⟨(40 : ℚ) / 47, (143 : ℚ) / 168⟩⟩,
    ⟨(-2 : ℤ), (-4 : ℤ), ⟨(-21 : ℚ) / 89, (-25 : ℚ) / 106⟩, ⟨(88 : ℚ) / 109, (109 : ℚ) / 135⟩⟩,
    ⟨(-2 : ℤ), (-3 : ℤ), ⟨(-19 : ℚ) / 101, (-22 : ℚ) / 117⟩, ⟨(60 : ℚ) / 79, (79 : ℚ) / 104⟩⟩,
    ⟨(-2 : ℤ), (-2 : ℤ), ⟨(-17 : ℚ) / 126, (-12 : ℚ) / 89⟩, ⟨(113 : ℚ) / 160, (101 : ℚ) / 143⟩⟩,
    ⟨(-2 : ℤ), (-1 : ℤ), ⟨(-11 : ℚ) / 149, (-9 : ℚ) / 122⟩, ⟨(20 : ℚ) / 31, (91 : ℚ) / 141⟩⟩,
    ⟨(-2 : ℤ), (0 : ℤ), ⟨(-1 : ℚ) / 4096, (1 : ℚ) / 4096⟩, ⟨(16377 : ℚ) / 28672, (16391 : ℚ) / 28672⟩⟩,
    ⟨(-2 : ℤ), (1 : ℤ), ⟨(8 : ℚ) / 79, (7 : ℚ) / 69⟩, ⟨(55 : ℚ) / 117, (63 : ℚ) / 134⟩⟩,
    ⟨(-1 : ℤ), (-13 : ℤ), ⟨(-67 : ℚ) / 102, (-44 : ℚ) / 67⟩, ⟨(49 : ℚ) / 52, (82 : ℚ) / 87⟩⟩,
    ⟨(-1 : ℤ), (-12 : ℤ), ⟨(-52 : ℚ) / 83, (-57 : ℚ) / 91⟩, ⟨(83 : ℚ) / 91, (52 : ℚ) / 57⟩⟩,
    ⟨(-1 : ℤ), (-11 : ℤ), ⟨(-47 : ℚ) / 79, (-69 : ℚ) / 116⟩, ⟨(81 : ℚ) / 92, (59 : ℚ) / 67⟩⟩,
    ⟨(-1 : ℤ), (-10 : ℤ), ⟨(-59 : ℚ) / 105, (-50 : ℚ) / 89⟩, ⟨(50 : ℚ) / 59, (89 : ℚ) / 105⟩⟩,
    ⟨(-1 : ℤ), (-9 : ℤ), ⟨(-29 : ℚ) / 55, (-97 : ℚ) / 184⟩, ⟨(126 : ℚ) / 155, (113 : ℚ) / 139⟩⟩,
    ⟨(-1 : ℤ), (-8 : ℤ), ⟨(-53 : ℚ) / 108, (-26 : ℚ) / 53⟩, ⟨(59 : ℚ) / 76, (66 : ℚ) / 85⟩⟩,
    ⟨(-1 : ℤ), (-7 : ℤ), ⟨(-47 : ℚ) / 104, (-61 : ℚ) / 135⟩, ⟨(59 : ℚ) / 80, (45 : ℚ) / 61⟩⟩,
    ⟨(-1 : ℤ), (-6 : ℤ), ⟨(-55 : ℚ) / 134, (-16 : ℚ) / 39⟩, ⟨(71 : ℚ) / 102, (55 : ℚ) / 79⟩⟩,
    ⟨(-1 : ℤ), (-5 : ℤ), ⟨(-34 : ℚ) / 93, (-19 : ℚ) / 52⟩, ⟨(28 : ℚ) / 43, (99 : ℚ) / 152⟩⟩,
    ⟨(-1 : ℤ), (-4 : ℤ), ⟨(-25 : ℚ) / 79, (-31 : ℚ) / 98⟩, ⟨(59 : ℚ) / 98, (56 : ℚ) / 93⟩⟩,
    ⟨(-1 : ℤ), (-3 : ℤ), ⟨(-29 : ℚ) / 111, (-35 : ℚ) / 134⟩, ⟨(35 : ℚ) / 64, (64 : ℚ) / 117⟩⟩,
    ⟨(-1 : ℤ), (-2 : ℤ), ⟨(-15 : ℚ) / 76, (-14 : ℚ) / 71⟩, ⟨(14 : ℚ) / 29, (71 : ℚ) / 147⟩⟩,
    ⟨(-1 : ℤ), (-1 : ℤ), ⟨(-21 : ℚ) / 178, (-23 : ℚ) / 195⟩, ⟨(44 : ℚ) / 109, (21 : ℚ) / 52⟩⟩,
    ⟨(-1 : ℤ), (0 : ℤ), ⟨(-1 : ℚ) / 4096, (1 : ℚ) / 4096⟩, ⟨(8185 : ℚ) / 28672, (8199 : ℚ) / 28672⟩⟩,
    ⟨(0 : ℤ), (-13 : ℤ), ⟨(-48 : ℚ) / 61, (-59 : ℚ) / 75⟩, ⟨(59 : ℚ) / 75, (48 : ℚ) / 61⟩⟩,
    ⟨(0 : ℤ), (-12 : ℤ), ⟨(-31 : ℚ) / 41, (-96 : ℚ) / 127⟩, ⟨(96 : ℚ) / 127, (31 : ℚ) / 41⟩⟩,
    ⟨(0 : ℤ), (-11 : ℤ), ⟨(-76 : ℚ) / 105, (-55 : ℚ) / 76⟩, ⟨(55 : ℚ) / 76, (76 : ℚ) / 105⟩⟩,
    ⟨(0 : ℤ), (-10 : ℤ), ⟨(-49 : ℚ) / 71, (-69 : ℚ) / 100⟩, ⟨(69 : ℚ) / 100, (49 : ℚ) / 71⟩⟩,
    ⟨(0 : ℤ), (-9 : ℤ), ⟨(-55 : ℚ) / 84, (-36 : ℚ) / 55⟩, ⟨(36 : ℚ) / 55, (55 : ℚ) / 84⟩⟩,
    ⟨(0 : ℤ), (-8 : ℤ), ⟨(-50 : ℚ) / 81, (-79 : ℚ) / 128⟩, ⟨(79 : ℚ) / 128, (50 : ℚ) / 81⟩⟩,
    ⟨(0 : ℤ), (-7 : ℤ), ⟨(-41 : ℚ) / 71, (-56 : ℚ) / 97⟩, ⟨(56 : ℚ) / 97, (41 : ℚ) / 71⟩⟩,
    ⟨(0 : ℤ), (-6 : ℤ), ⟨(-54 : ℚ) / 101, (-31 : ℚ) / 58⟩, ⟨(31 : ℚ) / 58, (54 : ℚ) / 101⟩⟩,
    ⟨(0 : ℤ), (-5 : ℤ), ⟨(-61 : ℚ) / 125, (-20 : ℚ) / 41⟩, ⟨(20 : ℚ) / 41, (61 : ℚ) / 125⟩⟩,
    ⟨(0 : ℤ), (-4 : ℤ), ⟨(-79 : ℚ) / 181, (-24 : ℚ) / 55⟩, ⟨(24 : ℚ) / 55, (79 : ℚ) / 181⟩⟩,
    ⟨(0 : ℤ), (-3 : ℤ), ⟨(-31 : ℚ) / 82, (-48 : ℚ) / 127⟩, ⟨(48 : ℚ) / 127, (31 : ℚ) / 82⟩⟩,
    ⟨(0 : ℤ), (-2 : ℤ), ⟨(-25 : ℚ) / 81, (-29 : ℚ) / 94⟩, ⟨(29 : ℚ) / 94, (25 : ℚ) / 81⟩⟩,
    ⟨(0 : ℤ), (-1 : ℤ), ⟨(-19 : ℚ) / 87, (-12 : ℚ) / 55⟩, ⟨(12 : ℚ) / 55, (19 : ℚ) / 87⟩⟩
  ]

def degreeSevenStageThreeExpectedRanges :
    List (ℤ × ℤ × ℤ × ℤ) :=
  [
    ((-3 : ℤ), (-9 : ℤ), (-8 : ℤ), (58 : ℤ)),
    ((-3 : ℤ), (-8 : ℤ), (-7 : ℤ), (52 : ℤ)),
    ((-3 : ℤ), (-7 : ℤ), (-5 : ℤ), (46 : ℤ)),
    ((-3 : ℤ), (-6 : ℤ), (-4 : ℤ), (40 : ℤ)),
    ((-3 : ℤ), (-5 : ℤ), (-2 : ℤ), (35 : ℤ)),
    ((-3 : ℤ), (-4 : ℤ), (-1 : ℤ), (30 : ℤ)),
    ((-3 : ℤ), (-3 : ℤ), (-1 : ℤ), (25 : ℤ)),
    ((-3 : ℤ), (-2 : ℤ), (0 : ℤ), (20 : ℤ)),
    ((-3 : ℤ), (-1 : ℤ), (0 : ℤ), (15 : ℤ)),
    ((-3 : ℤ), (0 : ℤ), (0 : ℤ), (11 : ℤ)),
    ((-3 : ℤ), (1 : ℤ), (0 : ℤ), (6 : ℤ)),
    ((-3 : ℤ), (2 : ℤ), (0 : ℤ), (3 : ℤ)),
    ((-3 : ℤ), (3 : ℤ), (-1 : ℤ), (-1 : ℤ)),
    ((-2 : ℤ), (-12 : ℤ), (-18 : ℤ), (55 : ℤ)),
    ((-2 : ℤ), (-11 : ℤ), (-15 : ℤ), (50 : ℤ)),
    ((-2 : ℤ), (-10 : ℤ), (-13 : ℤ), (45 : ℤ)),
    ((-2 : ℤ), (-9 : ℤ), (-11 : ℤ), (40 : ℤ)),
    ((-2 : ℤ), (-8 : ℤ), (-8 : ℤ), (35 : ℤ)),
    ((-2 : ℤ), (-7 : ℤ), (-7 : ℤ), (30 : ℤ)),
    ((-2 : ℤ), (-6 : ℤ), (-5 : ℤ), (25 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (-3 : ℤ), (21 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (-2 : ℤ), (17 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (-1 : ℤ), (13 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (0 : ℤ), (9 : ℤ)),
    ((-2 : ℤ), (-1 : ℤ), (0 : ℤ), (6 : ℤ)),
    ((-2 : ℤ), (0 : ℤ), (0 : ℤ), (3 : ℤ)),
    ((-2 : ℤ), (1 : ℤ), (0 : ℤ), (0 : ℤ)),
    ((-1 : ℤ), (-13 : ℤ), (-26 : ℤ), (45 : ℤ)),
    ((-1 : ℤ), (-12 : ℤ), (-23 : ℤ), (40 : ℤ)),
    ((-1 : ℤ), (-11 : ℤ), (-20 : ℤ), (36 : ℤ)),
    ((-1 : ℤ), (-10 : ℤ), (-17 : ℤ), (31 : ℤ)),
    ((-1 : ℤ), (-9 : ℤ), (-14 : ℤ), (27 : ℤ)),
    ((-1 : ℤ), (-8 : ℤ), (-11 : ℤ), (23 : ℤ)),
    ((-1 : ℤ), (-7 : ℤ), (-9 : ℤ), (19 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (-7 : ℤ), (16 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (-5 : ℤ), (12 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (-3 : ℤ), (9 : ℤ)),
    ((-1 : ℤ), (-3 : ℤ), (-2 : ℤ), (6 : ℤ)),
    ((-1 : ℤ), (-2 : ℤ), (-1 : ℤ), (4 : ℤ)),
    ((-1 : ℤ), (-1 : ℤ), (0 : ℤ), (2 : ℤ)),
    ((-1 : ℤ), (0 : ℤ), (0 : ℤ), (0 : ℤ)),
    ((0 : ℤ), (-13 : ℤ), (-34 : ℤ), (34 : ℤ)),
    ((0 : ℤ), (-12 : ℤ), (-30 : ℤ), (30 : ℤ)),
    ((0 : ℤ), (-11 : ℤ), (-26 : ℤ), (26 : ℤ)),
    ((0 : ℤ), (-10 : ℤ), (-23 : ℤ), (23 : ℤ)),
    ((0 : ℤ), (-9 : ℤ), (-19 : ℤ), (19 : ℤ)),
    ((0 : ℤ), (-8 : ℤ), (-16 : ℤ), (16 : ℤ)),
    ((0 : ℤ), (-7 : ℤ), (-13 : ℤ), (13 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-10 : ℤ), (10 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (-8 : ℤ), (8 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (-5 : ℤ), (5 : ℤ)),
    ((0 : ℤ), (-3 : ℤ), (-3 : ℤ), (3 : ℤ)),
    ((0 : ℤ), (-2 : ℤ), (-2 : ℤ), (2 : ℤ)),
    ((0 : ℤ), (-1 : ℤ), (0 : ℤ), (0 : ℤ))
  ]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- Exact rational root isolation checks for all generated quadratic rows.
theorem degreeSevenStageThreeEntries_valid :
    degreeSevenStageThreeEntries.Forall
      DegreeSevenStageThreeEntry.Valid := by
  norm_num [degreeSevenStageThreeEntries,
    DegreeSevenStageThreeEntry.Valid,
    DegreeSevenStageThreeEntry.derivativeCoefficients,
    DegreeSevenStageThreeEntry.rootIntervals,
    GeneralRationalRootIntervalCertificate.Valid,
    integerPolynomialRationalEval, DensePolynomial.eval]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- Exact Horner interval evaluation of every next-coefficient range.
theorem degreeSevenStageThreeRanges_checked :
    degreeSevenStageThreeEntries.map (fun entry =>
      (entry.a6, entry.a5,
        cubicTranslationLowerBound entry.baseCoefficients
          entry.firstRoot 16,
        cubicTranslationUpperBound entry.baseCoefficients
          (-16) entry.secondRoot)) =
      degreeSevenStageThreeExpectedRanges := by
  norm_num [degreeSevenStageThreeEntries,
    degreeSevenStageThreeExpectedRanges,
    DegreeSevenStageThreeEntry.baseCoefficients,
    cubicTranslationLowerBound, cubicTranslationUpperBound,
    integerPolynomialRootIntervalEval,
    integerPolynomialIntervalEval,
    denseRationalPolynomialIntervalEval,
    RationalRootInterval.toIntervalRat,
    LeanCert.Core.IntervalRat.singleton,
    LeanCert.Core.IntervalRat.add,
    LeanCert.Core.IntervalRat.mul,
    LeanCert.Core.IntervalRat.min4,
    LeanCert.Core.IntervalRat.max4, min_def, max_def, Int.toNat]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
-- The first exact septic frontier contains 1,641 coefficient prefixes.
theorem degreeSevenStageThree_prefix_count :
    (degreeSevenStageThreeEntries.flatMap fun entry =>
      entry.a4Candidates.toList.map fun a4 =>
        (entry.a6, entry.a5, a4)).length = 1641 := by
  norm_num [degreeSevenStageThreeEntries,
    DegreeSevenStageThreeEntry.a4Candidates,
    DegreeSevenStageThreeEntry.baseCoefficients,
    cubicTranslationCandidates, integerIcc,
    cubicTranslationLowerBound, cubicTranslationUpperBound,
    integerPolynomialRootIntervalEval,
    integerPolynomialIntervalEval,
    denseRationalPolynomialIntervalEval,
    RationalRootInterval.toIntervalRat,
    LeanCert.Core.IntervalRat.singleton,
    LeanCert.Core.IntervalRat.add,
    LeanCert.Core.IntervalRat.mul,
    LeanCert.Core.IntervalRat.min4,
    LeanCert.Core.IntervalRat.max4, min_def, max_def, Int.toNat]

end TraceEuclidean
