import TraceEuclidean.VoightCoefficientPruning

/-!
# Generated degree-five Rolle certificates: third derivative stage

This file is generated by `tools/generate_degree_five_rolle_certificates.py`.
It contains exact rational isolating intervals for the two roots of each
possible normalized third derivative `10 * x^2 + 4 * a4 * x + a3`.

All checks below use ordinary kernel reduction and `norm_num`; no native code
evaluation or floating point arithmetic enters the proof.
-/

namespace TraceEuclidean

set_option linter.style.longLine false

/-- One admissible top-coefficient pair and exact isolating intervals for the
two roots of its normalized third derivative. -/
structure DegreeFiveStageThreeEntry where
  a4 : ℤ
  a3 : ℤ
  firstRoot : RationalRootInterval
  secondRoot : RationalRootInterval
deriving DecidableEq, Repr

namespace DegreeFiveStageThreeEntry

/-- Coefficients of `10*x^2 + 4*a4*x + a3`, in ascending order. -/
def derivativeCoefficients (entry : DegreeFiveStageThreeEntry) : List ℤ :=
  [entry.a3, 4 * entry.a4, 10]

/-- Coefficients of the zero-constant-term cubic whose integer translation is
the next coefficient `a2`. -/
def baseCoefficients (entry : DegreeFiveStageThreeEntry) : List ℤ :=
  [0, 3 * entry.a3, 6 * entry.a4, 10]

def rootIntervals (entry : DegreeFiveStageThreeEntry) :
    List RationalRootInterval :=
  [entry.firstRoot, entry.secondRoot]

def Valid (entry : DegreeFiveStageThreeEntry) : Prop :=
  GeneralRationalRootIntervalCertificate.Valid 2
    entry.derivativeCoefficients entry.rootIntervals

/-- Exact finite set of the possible next coefficient `a2`. -/
def a2Candidates (entry : DegreeFiveStageThreeEntry) : Finset ℤ :=
  cubicTranslationCandidates entry.baseCoefficients
    (-10) 10 entry.firstRoot entry.secondRoot

end DegreeFiveStageThreeEntry

/-- The twenty split and separable quadratic stages surviving the Hunter
coefficient inequalities. -/
def degreeFiveStageThreeEntries :
    List DegreeFiveStageThreeEntry :=
  [
    ⟨(-2 : ℤ), (-5 : ℤ), ⟨(-33 : ℚ) / 80, (-40 : ℚ) / 97⟩, ⟨(137 : ℚ) / 113, (97 : ℚ) / 80⟩⟩,
    ⟨(-2 : ℤ), (-4 : ℤ), ⟨(-23 : ℚ) / 66, (-31 : ℚ) / 89⟩, ⟨(31 : ℚ) / 27, (178 : ℚ) / 155⟩⟩,
    ⟨(-2 : ℤ), (-3 : ℤ), ⟨(-32 : ℚ) / 115, (-37 : ℚ) / 133⟩, ⟨(69 : ℚ) / 64, (124 : ℚ) / 115⟩⟩,
    ⟨(-2 : ℤ), (-2 : ℤ), ⟨(-4101 : ℚ) / 20480, (-4091 : ℚ) / 20480⟩, ⟨(4095 : ℚ) / 4096, (4097 : ℚ) / 4096⟩⟩,
    ⟨(-2 : ℤ), (-1 : ℤ), ⟨(-11 : ℚ) / 100, (-10 : ℚ) / 91⟩, ⟨(111 : ℚ) / 122, (101 : ℚ) / 111⟩⟩,
    ⟨(-2 : ℤ), (0 : ℤ), ⟨(-1 : ℚ) / 4096, (1 : ℚ) / 4096⟩, ⟨(16379 : ℚ) / 20480, (16389 : ℚ) / 20480⟩⟩,
    ⟨(-2 : ℤ), (1 : ℤ), ⟨(11 : ℚ) / 71, (9 : ℚ) / 58⟩, ⟨(89 : ℚ) / 138, (20 : ℚ) / 31⟩⟩,
    ⟨(-1 : ℤ), (-6 : ℤ), ⟨(-12293 : ℚ) / 20480, (-12283 : ℚ) / 20480⟩, ⟨(4095 : ℚ) / 4096, (4097 : ℚ) / 4096⟩⟩,
    ⟨(-1 : ℤ), (-5 : ℤ), ⟨(-23 : ℚ) / 43, (-100 : ℚ) / 187⟩, ⟨(43 : ℚ) / 46, (158 : ℚ) / 169⟩⟩,
    ⟨(-1 : ℤ), (-4 : ℤ), ⟨(-19 : ℚ) / 41, (-63 : ℚ) / 136⟩, ⟨(120 : ℚ) / 139, (139 : ℚ) / 161⟩⟩,
    ⟨(-1 : ℤ), (-3 : ℤ), ⟨(-59 : ℚ) / 154, (-18 : ℚ) / 47⟩, ⟨(83 : ℚ) / 106, (65 : ℚ) / 83⟩⟩,
    ⟨(-1 : ℤ), (-2 : ℤ), ⟨(-29 : ℚ) / 100, (-20 : ℚ) / 69⟩, ⟨(109 : ℚ) / 158, (89 : ℚ) / 129⟩⟩,
    ⟨(-1 : ℤ), (-1 : ℤ), ⟨(-27 : ℚ) / 155, (-31 : ℚ) / 178⟩, ⟨(31 : ℚ) / 54, (58 : ℚ) / 101⟩⟩,
    ⟨(-1 : ℤ), (0 : ℤ), ⟨(-1 : ℚ) / 4096, (1 : ℚ) / 4096⟩, ⟨(8187 : ℚ) / 20480, (8197 : ℚ) / 20480⟩⟩,
    ⟨(0 : ℤ), (-6 : ℤ), ⟨(-55 : ℚ) / 71, (-79 : ℚ) / 102⟩, ⟨(79 : ℚ) / 102, (55 : ℚ) / 71⟩⟩,
    ⟨(0 : ℤ), (-5 : ℤ), ⟨(-99 : ℚ) / 140, (-70 : ℚ) / 99⟩, ⟨(70 : ℚ) / 99, (99 : ℚ) / 140⟩⟩,
    ⟨(0 : ℤ), (-4 : ℤ), ⟨(-74 : ℚ) / 117, (-43 : ℚ) / 68⟩, ⟨(43 : ℚ) / 68, (74 : ℚ) / 117⟩⟩,
    ⟨(0 : ℤ), (-3 : ℤ), ⟨(-86 : ℚ) / 157, (-23 : ℚ) / 42⟩, ⟨(23 : ℚ) / 42, (86 : ℚ) / 157⟩⟩,
    ⟨(0 : ℤ), (-2 : ℤ), ⟨(-17 : ℚ) / 38, (-55 : ℚ) / 123⟩, ⟨(55 : ℚ) / 123, (17 : ℚ) / 38⟩⟩,
    ⟨(0 : ℤ), (-1 : ℤ), ⟨(-37 : ℚ) / 117, (-43 : ℚ) / 136⟩, ⟨(43 : ℚ) / 136, (37 : ℚ) / 117⟩⟩
  ]

/-- Human-readable exact ranges `(a4, a3, min a2, max a2)`.  This is
redundant data used to make the generated search frontier easy to audit. -/
def degreeFiveStageThreeExpectedRanges :
    List (ℤ × ℤ × ℤ × ℤ) :=
  [
    ((-2 : ℤ), (-5 : ℤ), (-3 : ℤ), (18 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (-2 : ℤ), (14 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (-1 : ℤ), (11 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (0 : ℤ), (8 : ℤ)),
    ((-2 : ℤ), (-1 : ℤ), (0 : ℤ), (5 : ℤ)),
    ((-2 : ℤ), (0 : ℤ), (0 : ℤ), (2 : ℤ)),
    ((-2 : ℤ), (1 : ℤ), (0 : ℤ), (0 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (-6 : ℤ), (14 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (-4 : ℤ), (11 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (-3 : ℤ), (8 : ℤ)),
    ((-1 : ℤ), (-3 : ℤ), (-2 : ℤ), (5 : ℤ)),
    ((-1 : ℤ), (-2 : ℤ), (0 : ℤ), (3 : ℤ)),
    ((-1 : ℤ), (-1 : ℤ), (0 : ℤ), (1 : ℤ)),
    ((-1 : ℤ), (0 : ℤ), (0 : ℤ), (0 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-9 : ℤ), (9 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (-7 : ℤ), (7 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (-5 : ℤ), (5 : ℤ)),
    ((0 : ℤ), (-3 : ℤ), (-3 : ℤ), (3 : ℤ)),
    ((0 : ℤ), (-2 : ℤ), (-1 : ℤ), (1 : ℤ)),
    ((0 : ℤ), (-1 : ℤ), (0 : ℤ), (0 : ℤ))
  ]

/-- Explicit audit rows for the third-stage coefficient triples. -/
def degreeFiveStageThreePrefixesRow000 : List (ℤ × ℤ × ℤ) :=
  [
    ((-2 : ℤ), (-5 : ℤ), (-3 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (-2 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (-1 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (0 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (1 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (2 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (3 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (4 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (5 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (6 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (7 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (8 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (9 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (10 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (11 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (12 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (13 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (14 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (15 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (16 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (17 : ℤ)),
    ((-2 : ℤ), (-5 : ℤ), (18 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow001 : List (ℤ × ℤ × ℤ) :=
  [
    ((-2 : ℤ), (-4 : ℤ), (-2 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (-1 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (0 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (1 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (2 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (3 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (4 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (5 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (6 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (7 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (8 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (9 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (10 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (11 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (12 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (13 : ℤ)),
    ((-2 : ℤ), (-4 : ℤ), (14 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow002 : List (ℤ × ℤ × ℤ) :=
  [
    ((-2 : ℤ), (-3 : ℤ), (-1 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (0 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (1 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (2 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (3 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (4 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (5 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (6 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (7 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (8 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (9 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (10 : ℤ)),
    ((-2 : ℤ), (-3 : ℤ), (11 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow003 : List (ℤ × ℤ × ℤ) :=
  [
    ((-2 : ℤ), (-2 : ℤ), (0 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (1 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (2 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (3 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (4 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (5 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (6 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (7 : ℤ)),
    ((-2 : ℤ), (-2 : ℤ), (8 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow004 : List (ℤ × ℤ × ℤ) :=
  [
    ((-2 : ℤ), (-1 : ℤ), (0 : ℤ)),
    ((-2 : ℤ), (-1 : ℤ), (1 : ℤ)),
    ((-2 : ℤ), (-1 : ℤ), (2 : ℤ)),
    ((-2 : ℤ), (-1 : ℤ), (3 : ℤ)),
    ((-2 : ℤ), (-1 : ℤ), (4 : ℤ)),
    ((-2 : ℤ), (-1 : ℤ), (5 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow005 : List (ℤ × ℤ × ℤ) :=
  [
    ((-2 : ℤ), (0 : ℤ), (0 : ℤ)),
    ((-2 : ℤ), (0 : ℤ), (1 : ℤ)),
    ((-2 : ℤ), (0 : ℤ), (2 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow006 : List (ℤ × ℤ × ℤ) :=
  [
    ((-2 : ℤ), (1 : ℤ), (0 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow007 : List (ℤ × ℤ × ℤ) :=
  [
    ((-1 : ℤ), (-6 : ℤ), (-6 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (-5 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (-4 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (-3 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (-2 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (-1 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (0 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (1 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (2 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (3 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (4 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (5 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (6 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (7 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (8 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (9 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (10 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (11 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (12 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (13 : ℤ)),
    ((-1 : ℤ), (-6 : ℤ), (14 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow008 : List (ℤ × ℤ × ℤ) :=
  [
    ((-1 : ℤ), (-5 : ℤ), (-4 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (-3 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (-2 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (-1 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (0 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (1 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (2 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (3 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (4 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (5 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (6 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (7 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (8 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (9 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (10 : ℤ)),
    ((-1 : ℤ), (-5 : ℤ), (11 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow009 : List (ℤ × ℤ × ℤ) :=
  [
    ((-1 : ℤ), (-4 : ℤ), (-3 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (-2 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (-1 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (0 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (1 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (2 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (3 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (4 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (5 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (6 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (7 : ℤ)),
    ((-1 : ℤ), (-4 : ℤ), (8 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow010 : List (ℤ × ℤ × ℤ) :=
  [
    ((-1 : ℤ), (-3 : ℤ), (-2 : ℤ)),
    ((-1 : ℤ), (-3 : ℤ), (-1 : ℤ)),
    ((-1 : ℤ), (-3 : ℤ), (0 : ℤ)),
    ((-1 : ℤ), (-3 : ℤ), (1 : ℤ)),
    ((-1 : ℤ), (-3 : ℤ), (2 : ℤ)),
    ((-1 : ℤ), (-3 : ℤ), (3 : ℤ)),
    ((-1 : ℤ), (-3 : ℤ), (4 : ℤ)),
    ((-1 : ℤ), (-3 : ℤ), (5 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow011 : List (ℤ × ℤ × ℤ) :=
  [
    ((-1 : ℤ), (-2 : ℤ), (0 : ℤ)),
    ((-1 : ℤ), (-2 : ℤ), (1 : ℤ)),
    ((-1 : ℤ), (-2 : ℤ), (2 : ℤ)),
    ((-1 : ℤ), (-2 : ℤ), (3 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow012 : List (ℤ × ℤ × ℤ) :=
  [
    ((-1 : ℤ), (-1 : ℤ), (0 : ℤ)),
    ((-1 : ℤ), (-1 : ℤ), (1 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow013 : List (ℤ × ℤ × ℤ) :=
  [
    ((-1 : ℤ), (0 : ℤ), (0 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow014 : List (ℤ × ℤ × ℤ) :=
  [
    ((0 : ℤ), (-6 : ℤ), (-9 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-8 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-7 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-6 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-5 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-4 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-3 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-2 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (-1 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (0 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (1 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (2 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (3 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (4 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (5 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (6 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (7 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (8 : ℤ)),
    ((0 : ℤ), (-6 : ℤ), (9 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow015 : List (ℤ × ℤ × ℤ) :=
  [
    ((0 : ℤ), (-5 : ℤ), (-7 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (-6 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (-5 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (-4 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (-3 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (-2 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (-1 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (0 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (1 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (2 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (3 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (4 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (5 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (6 : ℤ)),
    ((0 : ℤ), (-5 : ℤ), (7 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow016 : List (ℤ × ℤ × ℤ) :=
  [
    ((0 : ℤ), (-4 : ℤ), (-5 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (-4 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (-3 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (-2 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (-1 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (0 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (1 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (2 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (3 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (4 : ℤ)),
    ((0 : ℤ), (-4 : ℤ), (5 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow017 : List (ℤ × ℤ × ℤ) :=
  [
    ((0 : ℤ), (-3 : ℤ), (-3 : ℤ)),
    ((0 : ℤ), (-3 : ℤ), (-2 : ℤ)),
    ((0 : ℤ), (-3 : ℤ), (-1 : ℤ)),
    ((0 : ℤ), (-3 : ℤ), (0 : ℤ)),
    ((0 : ℤ), (-3 : ℤ), (1 : ℤ)),
    ((0 : ℤ), (-3 : ℤ), (2 : ℤ)),
    ((0 : ℤ), (-3 : ℤ), (3 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow018 : List (ℤ × ℤ × ℤ) :=
  [
    ((0 : ℤ), (-2 : ℤ), (-1 : ℤ)),
    ((0 : ℤ), (-2 : ℤ), (0 : ℤ)),
    ((0 : ℤ), (-2 : ℤ), (1 : ℤ))
  ]

def degreeFiveStageThreePrefixesRow019 : List (ℤ × ℤ × ℤ) :=
  [
    ((0 : ℤ), (-1 : ℤ), (0 : ℤ))
  ]

/-- Explicit audit list of all third-stage coefficient triples. -/
def degreeFiveStageThreePrefixes : List (ℤ × ℤ × ℤ) :=
  degreeFiveStageThreePrefixesRow000 ++
    degreeFiveStageThreePrefixesRow001 ++
    degreeFiveStageThreePrefixesRow002 ++
    degreeFiveStageThreePrefixesRow003 ++
    degreeFiveStageThreePrefixesRow004 ++
    degreeFiveStageThreePrefixesRow005 ++
    degreeFiveStageThreePrefixesRow006 ++
    degreeFiveStageThreePrefixesRow007 ++
    degreeFiveStageThreePrefixesRow008 ++
    degreeFiveStageThreePrefixesRow009 ++
    degreeFiveStageThreePrefixesRow010 ++
    degreeFiveStageThreePrefixesRow011 ++
    degreeFiveStageThreePrefixesRow012 ++
    degreeFiveStageThreePrefixesRow013 ++
    degreeFiveStageThreePrefixesRow014 ++
    degreeFiveStageThreePrefixesRow015 ++
    degreeFiveStageThreePrefixesRow016 ++
    degreeFiveStageThreePrefixesRow017 ++
    degreeFiveStageThreePrefixesRow018 ++
    degreeFiveStageThreePrefixesRow019

theorem degreeFiveStageThreePrefixesRow000_mem_of_bounds {a2 : ℤ}
    (hlower : (-3 : ℤ) ≤ a2)
    (hupper : a2 ≤ (18 : ℤ)) :
    ((-2 : ℤ), (-5 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-2 : ℤ), (-5 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow000 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow000]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow001_mem_of_bounds {a2 : ℤ}
    (hlower : (-2 : ℤ) ≤ a2)
    (hupper : a2 ≤ (14 : ℤ)) :
    ((-2 : ℤ), (-4 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-2 : ℤ), (-4 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow001 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow001]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow002_mem_of_bounds {a2 : ℤ}
    (hlower : (-1 : ℤ) ≤ a2)
    (hupper : a2 ≤ (11 : ℤ)) :
    ((-2 : ℤ), (-3 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-2 : ℤ), (-3 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow002 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow002]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow003_mem_of_bounds {a2 : ℤ}
    (hlower : (0 : ℤ) ≤ a2)
    (hupper : a2 ≤ (8 : ℤ)) :
    ((-2 : ℤ), (-2 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-2 : ℤ), (-2 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow003 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow003]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow004_mem_of_bounds {a2 : ℤ}
    (hlower : (0 : ℤ) ≤ a2)
    (hupper : a2 ≤ (5 : ℤ)) :
    ((-2 : ℤ), (-1 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-2 : ℤ), (-1 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow004 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow004]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow005_mem_of_bounds {a2 : ℤ}
    (hlower : (0 : ℤ) ≤ a2)
    (hupper : a2 ≤ (2 : ℤ)) :
    ((-2 : ℤ), (0 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-2 : ℤ), (0 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow005 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow005]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow006_mem_of_bounds {a2 : ℤ}
    (hlower : (0 : ℤ) ≤ a2)
    (hupper : a2 ≤ (0 : ℤ)) :
    ((-2 : ℤ), (1 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-2 : ℤ), (1 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow006 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow006]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow007_mem_of_bounds {a2 : ℤ}
    (hlower : (-6 : ℤ) ≤ a2)
    (hupper : a2 ≤ (14 : ℤ)) :
    ((-1 : ℤ), (-6 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-1 : ℤ), (-6 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow007 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow007]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow008_mem_of_bounds {a2 : ℤ}
    (hlower : (-4 : ℤ) ≤ a2)
    (hupper : a2 ≤ (11 : ℤ)) :
    ((-1 : ℤ), (-5 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-1 : ℤ), (-5 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow008 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow008]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow009_mem_of_bounds {a2 : ℤ}
    (hlower : (-3 : ℤ) ≤ a2)
    (hupper : a2 ≤ (8 : ℤ)) :
    ((-1 : ℤ), (-4 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-1 : ℤ), (-4 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow009 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow009]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow010_mem_of_bounds {a2 : ℤ}
    (hlower : (-2 : ℤ) ≤ a2)
    (hupper : a2 ≤ (5 : ℤ)) :
    ((-1 : ℤ), (-3 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-1 : ℤ), (-3 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow010 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow010]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow011_mem_of_bounds {a2 : ℤ}
    (hlower : (0 : ℤ) ≤ a2)
    (hupper : a2 ≤ (3 : ℤ)) :
    ((-1 : ℤ), (-2 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-1 : ℤ), (-2 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow011 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow011]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow012_mem_of_bounds {a2 : ℤ}
    (hlower : (0 : ℤ) ≤ a2)
    (hupper : a2 ≤ (1 : ℤ)) :
    ((-1 : ℤ), (-1 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-1 : ℤ), (-1 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow012 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow012]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow013_mem_of_bounds {a2 : ℤ}
    (hlower : (0 : ℤ) ≤ a2)
    (hupper : a2 ≤ (0 : ℤ)) :
    ((-1 : ℤ), (0 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((-1 : ℤ), (0 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow013 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow013]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow014_mem_of_bounds {a2 : ℤ}
    (hlower : (-9 : ℤ) ≤ a2)
    (hupper : a2 ≤ (9 : ℤ)) :
    ((0 : ℤ), (-6 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((0 : ℤ), (-6 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow014 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow014]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow015_mem_of_bounds {a2 : ℤ}
    (hlower : (-7 : ℤ) ≤ a2)
    (hupper : a2 ≤ (7 : ℤ)) :
    ((0 : ℤ), (-5 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((0 : ℤ), (-5 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow015 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow015]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow016_mem_of_bounds {a2 : ℤ}
    (hlower : (-5 : ℤ) ≤ a2)
    (hupper : a2 ≤ (5 : ℤ)) :
    ((0 : ℤ), (-4 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((0 : ℤ), (-4 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow016 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow016]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow017_mem_of_bounds {a2 : ℤ}
    (hlower : (-3 : ℤ) ≤ a2)
    (hupper : a2 ≤ (3 : ℤ)) :
    ((0 : ℤ), (-3 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((0 : ℤ), (-3 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow017 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow017]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow018_mem_of_bounds {a2 : ℤ}
    (hlower : (-1 : ℤ) ≤ a2)
    (hupper : a2 ≤ (1 : ℤ)) :
    ((0 : ℤ), (-2 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((0 : ℤ), (-2 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow018 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow018]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

theorem degreeFiveStageThreePrefixesRow019_mem_of_bounds {a2 : ℤ}
    (hlower : (0 : ℤ) ≤ a2)
    (hupper : a2 ≤ (0 : ℤ)) :
    ((0 : ℤ), (-1 : ℤ), a2) ∈
      degreeFiveStageThreePrefixes := by
  have hrow : ((0 : ℤ), (-1 : ℤ), a2) ∈
      degreeFiveStageThreePrefixesRow019 := by
    interval_cases a2 <;> simp_all [degreeFiveStageThreePrefixesRow019]
  simpa only [degreeFiveStageThreePrefixes, List.mem_append,
    hrow, or_true, true_or]

set_option maxRecDepth 100000 in
theorem degreeFiveStageThreeEntries_valid :
    degreeFiveStageThreeEntries.Forall
      DegreeFiveStageThreeEntry.Valid := by
  norm_num (config := { maxSteps := 1000000 }) [degreeFiveStageThreeEntries,
    DegreeFiveStageThreeEntry.Valid,
    DegreeFiveStageThreeEntry.derivativeCoefficients,
    DegreeFiveStageThreeEntry.rootIntervals,
    GeneralRationalRootIntervalCertificate.Valid,
    integerPolynomialRationalEval, DensePolynomial.eval]

set_option maxRecDepth 100000 in
/-- The computed integer ranges agree exactly with the displayed audit data. -/
theorem degreeFiveStageThreeRanges_checked :
    degreeFiveStageThreeEntries.map (fun entry =>
      (entry.a4, entry.a3,
        cubicTranslationLowerBound entry.baseCoefficients
          entry.firstRoot 10,
        cubicTranslationUpperBound entry.baseCoefficients
          (-10) entry.secondRoot)) =
      degreeFiveStageThreeExpectedRanges := by
  norm_num [degreeFiveStageThreeEntries,
    degreeFiveStageThreeExpectedRanges,
    DegreeFiveStageThreeEntry.baseCoefficients,
    cubicTranslationLowerBound, cubicTranslationUpperBound,
    integerPolynomialRootIntervalEval,
    integerPolynomialIntervalEval,
    denseRationalPolynomialIntervalEval,
    RationalRootInterval.toIntervalRat,
    LeanCert.Core.IntervalRat.singleton,
    LeanCert.Core.IntervalRat.add,
    LeanCert.Core.IntervalRat.mul,
    LeanCert.Core.IntervalRat.min4,
    LeanCert.Core.IntervalRat.max4, min_def, max_def, Int.toNat]

set_option maxRecDepth 100000 in
/-- The exact third-stage frontier contains 191 coefficient triples. -/
theorem degreeFiveStageThree_prefix_count :
    degreeFiveStageThreePrefixes.length = 191 := by
  norm_num [degreeFiveStageThreePrefixes,
    degreeFiveStageThreePrefixesRow000, degreeFiveStageThreePrefixesRow001, degreeFiveStageThreePrefixesRow002, degreeFiveStageThreePrefixesRow003, degreeFiveStageThreePrefixesRow004, degreeFiveStageThreePrefixesRow005, degreeFiveStageThreePrefixesRow006, degreeFiveStageThreePrefixesRow007, degreeFiveStageThreePrefixesRow008, degreeFiveStageThreePrefixesRow009, degreeFiveStageThreePrefixesRow010, degreeFiveStageThreePrefixesRow011, degreeFiveStageThreePrefixesRow012, degreeFiveStageThreePrefixesRow013, degreeFiveStageThreePrefixesRow014, degreeFiveStageThreePrefixesRow015, degreeFiveStageThreePrefixesRow016, degreeFiveStageThreePrefixesRow017, degreeFiveStageThreePrefixesRow018, degreeFiveStageThreePrefixesRow019]

end TraceEuclidean
