import TraceEuclidean.FiniteSubmoduleIntervals
import TraceEuclidean.FixedVolumeFiniteness
import Mathlib.NumberTheory.NumberField.Ideal.Basic
import Mathlib.RingTheory.Ideal.Quotient.Index

/-!
# Finite reduction codes

Two elementary devices used by the direct finiteness proof are collected
here.  A finite set of complete (not necessarily canonical) codes covers only
finitely many objects.  For a fixed number field and a nonzero integer `m`,
there are only finitely many submodules of a free integer-ring module that
contain `m` times the whole module.
-/

namespace TraceEuclidean

open scoped NumberField
open scoped Pointwise

noncomputable section

/-- A finite family of complete relational codes proves finiteness.  This
version is useful when reduction theory supplies a code noncanonically. -/
theorem finite_of_finite_complete_relation
    {α β : Type*} (P : α → Prop) (codes : Set β) (R : α → β → Prop)
    (hcodes : codes.Finite)
    (hcovered : ∀ a, P a → ∃ b ∈ codes, R a b)
    (hcomplete : ∀ {a a' b}, P a → P a' → R a b → R a' b → a = a') :
    {a | P a}.Finite := by
  classical
  cases isEmpty_or_nonempty α with
  | inl hα =>
      letI := hα
      have hempty : {a | P a} = (∅ : Set α) := by
        ext a
        exact isEmptyElim a
      rw [hempty]
      exact Set.finite_empty
  | inr hα =>
    letI := hα
    let decode : β → α := fun b ↦
      if h : ∃ a, P a ∧ R a b then Classical.choose h else Classical.choice inferInstance
    have hdecode {b : β} (h : ∃ a, P a ∧ R a b) :
        P (decode b) ∧ R (decode b) b := by
      simp only [decode, dif_pos h]
      exact Classical.choose_spec h
    apply (hcodes.image decode).subset
    intro a ha
    obtain ⟨b, hb, hab⟩ := hcovered a ha
    have hex : ∃ a', P a' ∧ R a' b := ⟨a, ha, hab⟩
    refine ⟨b, hb, ?_⟩
    exact hcomplete (hdecode hex).1 ha (hdecode hex).2 hab

/-- The submodule `m M` of a free integer-ring coordinate module. -/
def integerMultipleCoordinateSubmodule
    (K : Type*) [Field K] [NumberField K] (n m : ℕ) :
    Submodule (𝓞 K) (Fin n → 𝓞 K) :=
  Ideal.span ({(m : 𝓞 K)} : Set (𝓞 K)) • (⊤ : Submodule (𝓞 K) (Fin n → 𝓞 K))

/-- The submodule `a M` of a free integer-ring coordinate module. -/
def principalMultipleCoordinateSubmodule
    (K : Type*) [Field K] [NumberField K] (n : ℕ) (a : 𝓞 K) :
    Submodule (𝓞 K) (Fin n → 𝓞 K) :=
  Ideal.span ({a} : Set (𝓞 K)) • (⊤ : Submodule (𝓞 K) (Fin n → 𝓞 K))

/-- The principal coordinate module is the coordinatewise product of the
principal ideal generated by `a`. -/
theorem principalMultipleCoordinateSubmodule_toAddSubgroup
    (K : Type*) [Field K] [NumberField K] (n : ℕ) (a : 𝓞 K) :
    (principalMultipleCoordinateSubmodule K n a).toAddSubgroup =
      AddSubgroup.pi Set.univ
        (fun _ : Fin n => (Ideal.span ({a} : Set (𝓞 K))).toAddSubgroup) := by
  classical
  ext x
  rw [principalMultipleCoordinateSubmodule,
    Submodule.ideal_span_singleton_smul]
  change x ∈ (a • (⊤ : Submodule (𝓞 K) (Fin n → 𝓞 K))) ↔ _
  rw [Submodule.mem_smul_pointwise_iff_exists]
  simp only [AddSubgroup.mem_pi, Set.mem_univ, true_implies,
    Submodule.mem_toAddSubgroup, Ideal.mem_span_singleton]
  constructor
  · rintro ⟨z, _hz, rfl⟩ i
    exact ⟨z i, by simp⟩
  · intro h
    choose z hz using h
    refine ⟨z, by simp, ?_⟩
    funext i
    simpa using (hz i).symm

/-- The additive index of `a (𝓞_K)^n` is the `n`-th power of the absolute
norm of the principal ideal `(a)`. -/
theorem principalMultipleCoordinateSubmodule_index
    (K : Type*) [Field K] [NumberField K] (n : ℕ) (a : 𝓞 K) :
    (principalMultipleCoordinateSubmodule K n a).toAddSubgroup.index =
      Ideal.absNorm (Ideal.span ({a} : Set (𝓞 K))) ^ n := by
  rw [principalMultipleCoordinateSubmodule_toAddSubgroup,
    AddSubgroup.index_pi]
  simp [Ideal.absNorm_eq_index]

/-- For nonzero `m`, only finitely many integer-ring submodules of
`(𝓞 K)^n` contain `m (𝓞 K)^n`. -/
theorem finite_coordinateSubmodules_above_integerMultiple
    (K : Type*) [Field K] [NumberField K] (n m : ℕ) (hm : m ≠ 0) :
    {P : Submodule (𝓞 K) (Fin n → 𝓞 K) |
      integerMultipleCoordinateSubmodule K n m ≤ P}.Finite := by
  let I : Ideal (𝓞 K) := Ideal.span ({(m : 𝓞 K)} : Set (𝓞 K))
  have hI : I ≠ ⊥ := by
    change Ideal.span ({(m : 𝓞 K)} : Set (𝓞 K)) ≠ ⊥
    intro hzero
    apply hm
    exact_mod_cast Ideal.span_singleton_eq_bot.mp hzero
  letI : Finite ((𝓞 K) ⧸ I) := Ring.HasFiniteQuotients.finiteQuotient hI
  have htop : (⊤ : Submodule (𝓞 K) (Fin n → 𝓞 K)).FG :=
    Module.Finite.fg_top
  letI : Finite ((Fin n → 𝓞 K) ⧸ I • (⊤ : Submodule (𝓞 K) (Fin n → 𝓞 K))) :=
    Submodule.finite_quotient_smul I htop
  simpa only [integerMultipleCoordinateSubmodule, I] using
    finite_submodules_above_of_finite_quotient
      (𝓞 K) (Fin n → 𝓞 K)
      (I • (⊤ : Submodule (𝓞 K) (Fin n → 𝓞 K)))

/-- For a nonzero algebraic integer `a`, only finitely many integer-ring
submodules of `(𝓞 K)^n` contain `a (𝓞 K)^n`.  This is the form needed for
the determinant/adjugate reduction code. -/
theorem finite_coordinateSubmodules_above_principalMultiple
    (K : Type*) [Field K] [NumberField K] (n : ℕ) (a : 𝓞 K) (ha : a ≠ 0) :
    {P : Submodule (𝓞 K) (Fin n → 𝓞 K) |
      principalMultipleCoordinateSubmodule K n a ≤ P}.Finite := by
  let I : Ideal (𝓞 K) := Ideal.span ({a} : Set (𝓞 K))
  have hI : I ≠ ⊥ := by
    change Ideal.span ({a} : Set (𝓞 K)) ≠ ⊥
    exact Submodule.span_singleton_eq_bot.not.mpr ha
  letI : Finite ((𝓞 K) ⧸ I) := Ring.HasFiniteQuotients.finiteQuotient hI
  have htop : (⊤ : Submodule (𝓞 K) (Fin n → 𝓞 K)).FG :=
    Module.Finite.fg_top
  letI : Finite ((Fin n → 𝓞 K) ⧸ I • (⊤ : Submodule (𝓞 K) (Fin n → 𝓞 K))) :=
    Submodule.finite_quotient_smul I htop
  simpa only [principalMultipleCoordinateSubmodule, I] using
    finite_submodules_above_of_finite_quotient
      (𝓞 K) (Fin n → 𝓞 K)
      (I • (⊤ : Submodule (𝓞 K) (Fin n → 𝓞 K)))

/-- A determinant-normalized reduction code consists of an integral Gram
matrix and an integral coordinate submodule. -/
abbrev IntegralReductionCode
    (K : Type*) [Field K] [NumberField K] (n : ℕ) :=
  Matrix (Fin n) (Fin n) (𝓞 K) × Submodule (𝓞 K) (Fin n → 𝓞 K)

/-- The finite constraints satisfied by a determinant-normalized reduction
code.  The matrix is bounded and nonsingular, while the coordinate module
contains the determinant multiple of the standard module. -/
def IntegralReductionCode.IsBounded
    {K : Type*} [Field K] [NumberField K] {n : ℕ}
    (B : ℝ) (c : IntegralReductionCode K n) : Prop :=
  Matrix.ConjugateBounded B c.1 ∧ c.1.det ≠ 0 ∧
    principalMultipleCoordinateSubmodule K n c.1.det ≤ c.2

/-- For a fixed number field, rank, and archimedean bound, there are only
finitely many determinant-normalized reduction codes. -/
theorem finite_boundedIntegralReductionCodes
    (K : Type*) [Field K] [NumberField K] (n : ℕ) (B : ℝ) :
    {c : IntegralReductionCode K n |
      IntegralReductionCode.IsBounded B c}.Finite := by
  apply finite_of_finite_keys_and_fibers
    (fun c : IntegralReductionCode K n ↦
      IntegralReductionCode.IsBounded B c)
    Prod.fst
    {G : Matrix (Fin n) (Fin n) (𝓞 K) | Matrix.ConjugateBounded B G}
    (finite_matrices_of_conjugateBounded K (Fin n) (Fin n) B)
  · intro c hc
    exact hc.1
  · intro G
    by_cases hG : G.det = 0
    · have hempty :
          {c : IntegralReductionCode K n |
            IntegralReductionCode.IsBounded B c ∧ c.1 = G} = ∅ := by
        ext c
        simp only [Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
        intro hc
        apply hc.1.2.1
        rw [hc.2, hG]
      rw [hempty]
      exact Set.finite_empty
    · have hmodules :=
        finite_coordinateSubmodules_above_principalMultiple K n G.det hG
      apply ((Set.finite_singleton G).prod hmodules).subset
      intro c hc
      refine ⟨?_, ?_⟩
      · simpa using hc.2
      · simpa [hc.2] using hc.1.2.2

end

end TraceEuclidean
