import TraceEuclidean.DirectFixedFieldFiniteness
import TraceEuclidean.TraceDeterminant
import Mathlib.Analysis.InnerProductSpace.GramMatrix

/-!
# Discriminant identity for a selected lattice field basis

A field basis made of lattice vectors gives a canonical free sublattice: take
all products of the basis vectors with an integral basis of the number field.
This file realizes that sublattice in the Euclidean trace space and proves its
exact covolume formula.  The formula is stated for any integral Gram matrix,
so it applies both to the classic form and to the scale-two form.
-/

namespace TraceEuclidean

open Module Matrix MeasureTheory
open scoped NumberField InnerProductSpace

noncomputable section

namespace GlobalLatticePresentation

/-- The rational tower basis attached to a selected field basis. -/
def rationalTowerBasisFrom (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1)) :
    Basis (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1))
      ℚ (Fin P.rank → P.field.1) :=
  (NumberField.integralBasis P.field.1).smulTower' b

@[simp]
theorem rationalTowerBasisFrom_apply (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1))
    (ia : Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1)) :
    P.rationalTowerBasisFrom b ia =
      (NumberField.integralBasis P.field.1 ia.2) • b ia.1 := by
  exact Basis.smulTower'_apply _ _ ia

/-- The selected tower basis in rational diagonal coordinates. -/
def diagonalRationalTowerBasisFrom (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1)) :
    Basis (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1))
      ℚ (P.TraceDimensionIndex → ℚ) :=
  (P.rationalTowerBasisFrom b).map P.traceDiagonalIsometry.toLinearEquiv

/-- The selected tower basis after scalar extension to the real trace space. -/
def realTowerBasisFrom (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1)) :
    Basis (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1))
      ℝ P.RealTraceSpace :=
  ((P.diagonalRationalTowerBasisFrom b).baseChange ℝ).map
    (TensorProduct.piScalarRight ℚ ℝ ℝ P.TraceDimensionIndex)

@[simp]
theorem realTowerBasisFrom_apply (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1))
    (ia : Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1))
    (j : P.TraceDimensionIndex) :
    P.realTowerBasisFrom b ia j =
      P.rationalPointEmbedding
        ((NumberField.integralBasis P.field.1 ia.2) • b ia.1) j := by
  simp [realTowerBasisFrom, diagonalRationalTowerBasisFrom,
    rationalPointEmbedding_apply, TensorProduct.piScalarRightHom_tmul]

/-- The selected tower basis in the Euclidean trace realization. -/
def euclideanTowerBasisFrom (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1)) :
    Basis (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1))
      ℝ P.EuclideanTraceSpace :=
  (P.realTowerBasisFrom b).map P.euclideanTraceScalingEquiv

@[simp]
theorem euclideanTowerBasisFrom_apply (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1))
    (ia : Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1)) :
    P.euclideanTowerBasisFrom b ia =
      P.euclideanPointEmbedding
        ((NumberField.integralBasis P.field.1 ia.2) • b ia.1) := by
  ext j
  simp [euclideanTowerBasisFrom, euclideanPointEmbedding]

/-- The free Euclidean sublattice generated by the selected field basis. -/
def euclideanTowerSublatticeFrom (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1)) :
    Submodule ℤ P.EuclideanTraceSpace :=
  Submodule.span ℤ (Set.range (P.euclideanTowerBasisFrom b))

instance (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1)) :
    DiscreteTopology (P.euclideanTowerSublatticeFrom b) := by
  unfold euclideanTowerSublatticeFrom
  infer_instance

instance (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1)) :
    IsZLattice ℝ (P.euclideanTowerSublatticeFrom b) := by
  unfold euclideanTowerSublatticeFrom
  infer_instance

/-- Covolume squared of the free tower sublattice is its Euclidean Gram
determinant. -/
theorem euclideanTowerSublattice_covolume_sq_eq_det_gram
    (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1)) :
    ZLattice.covolume (P.euclideanTowerSublatticeFrom b) ^ (2 : ℕ) =
      (Matrix.gram ℝ (P.euclideanTowerBasisFrom b)).det := by
  classical
  let bstd : OrthonormalBasis P.TraceDimensionIndex ℝ
      P.EuclideanTraceSpace :=
    EuclideanSpace.basisFun P.TraceDimensionIndex ℝ
  let e : P.TraceDimensionIndex ≃
      (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1)) :=
    bstd.toBasis.indexEquiv (P.euclideanTowerBasisFrom b)
  let b0o : OrthonormalBasis
      (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1)) ℝ
      P.EuclideanTraceSpace := bstd.reindex e
  let b0 : Basis
      (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1)) ℝ
      P.EuclideanTraceSpace := b0o.toBasis
  let bZ : Basis
      (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1)) ℤ
      (P.euclideanTowerSublatticeFrom b) := by
    unfold euclideanTowerSublatticeFrom
    exact (P.euclideanTowerBasisFrom b).restrictScalars ℤ
  have hvol : volume.real (ZSpan.fundamentalDomain b0) = 1 := by
    calc
      volume.real (ZSpan.fundamentalDomain b0) =
          volume.real (Basis.parallelepiped b0) :=
        measureReal_congr
          (ZSpan.fundamentalDomain_ae_parallelepiped b0 volume)
      _ = 1 := by
        simpa [Measure.real, b0] using
          congrArg ENNReal.toReal b0o.volume_parallelepiped
  let m : Matrix
      (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1))
      (Fin P.rank × Module.Free.ChooseBasisIndex ℤ (𝓞 P.field.1)) ℝ :=
    Matrix.of fun i j ↦ b0o.repr (P.euclideanTowerBasisFrom b j) i
  have hm : b0.toMatrix ((↑) ∘ bZ) = m := by
    ext i j
    change b0.repr (bZ j : P.EuclideanTraceSpace) i =
      b0o.repr (P.euclideanTowerBasisFrom b j) i
    change b0.repr
        (((P.euclideanTowerBasisFrom b).restrictScalars ℤ j :
          P.euclideanTowerSublatticeFrom b) : P.EuclideanTraceSpace) i = _
    rw [(P.euclideanTowerBasisFrom b).restrictScalars_apply ℤ]
    rfl
  rw [ZLattice.covolume_eq_det_mul_measureReal
      (P.euclideanTowerSublatticeFrom b) (μ := volume) bZ b0,
    hvol, mul_one, sq_abs, Basis.det_apply, hm]
  rw [Matrix.gram_eq_conjTranspose_mul b0o
      (P.euclideanTowerBasisFrom b), Matrix.det_mul,
    Matrix.det_conjTranspose]
  simp [m, pow_two]

/-- The Euclidean Gram matrix of the selected tower basis is the real cast of
the trace block matrix of the field-valued Gram matrix. -/
theorem gram_euclideanTowerBasisFrom_eq_map_traceBlockMatrix
    (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1)) :
    Matrix.gram ℝ (P.euclideanTowerBasisFrom b) =
      (traceBlockMatrix (NumberField.integralBasis P.field.1)
        (LinearMap.BilinForm.toMatrix b P.Q.associated)).map
          (Rat.castHom ℝ) := by
  ext ⟨i, a⟩ ⟨j, c⟩
  rw [Matrix.gram_apply, P.euclideanTowerBasisFrom_apply,
    P.euclideanTowerBasisFrom_apply, P.inner_euclideanPointEmbedding]
  simp only [traceBlockMatrix, Matrix.map_apply]
  rw [map_smul, LinearMap.map_smul₂]
  simp [LinearMap.BilinForm.toMatrix_apply, smul_eq_mul,
    mul_assoc, mul_left_comm]

/-- Exact covolume identity for an integral Gram matrix on the selected field
basis.  Absolute values remove all orientation choices. -/
theorem euclideanTowerSublattice_covolume_sq_eq_discr_pow_absNorm
    (P : GlobalLatticePresentation)
    (b : Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1))
    (G : Matrix (Fin P.rank) (Fin P.rank) (𝓞 P.field.1))
    (hG : (algebraMap (𝓞 P.field.1) P.field.1).mapMatrix G =
      LinearMap.BilinForm.toMatrix b P.Q.associated) :
    ZLattice.covolume (P.euclideanTowerSublatticeFrom b) ^ (2 : ℕ) =
      ((|NumberField.discr P.field.1| : ℤ) : ℝ) ^ P.rank *
        (Ideal.absNorm (Ideal.span ({G.det} : Set (𝓞 P.field.1))) : ℝ) := by
  have hraw :
      ZLattice.covolume (P.euclideanTowerSublatticeFrom b) ^ (2 : ℕ) =
        (((traceBlockMatrix (NumberField.integralBasis P.field.1)
          (LinearMap.BilinForm.toMatrix b P.Q.associated)).det : ℚ) : ℝ) := by
    rw [P.euclideanTowerSublattice_covolume_sq_eq_det_gram b,
      P.gram_euclideanTowerBasisFrom_eq_map_traceBlockMatrix b]
    exact (Rat.cast_det _).symm
  have habsQ :
      |(traceBlockMatrix (NumberField.integralBasis P.field.1)
        (LinearMap.BilinForm.toMatrix b P.Q.associated)).det| =
        |(NumberField.discr P.field.1 : ℚ)| ^ P.rank *
          (Ideal.absNorm
            (Ideal.span ({G.det} : Set (𝓞 P.field.1))) : ℚ) := by
    rw [det_traceBlockMatrix, ← NumberField.coe_discr,
      ← hG, ← (algebraMap (𝓞 P.field.1) P.field.1).map_det,
      ← Algebra.coe_norm_int, abs_mul, abs_pow,
      Ideal.absNorm_span_singleton, Nat.cast_natAbs, Int.cast_abs]
    simp
  have hnonneg :
      0 ≤ ZLattice.covolume
        (P.euclideanTowerSublatticeFrom b) ^ (2 : ℕ) := by positivity
  calc
    ZLattice.covolume (P.euclideanTowerSublatticeFrom b) ^ (2 : ℕ) =
        |ZLattice.covolume
          (P.euclideanTowerSublatticeFrom b) ^ (2 : ℕ)| :=
      (abs_of_nonneg hnonneg).symm
    _ = |(((traceBlockMatrix (NumberField.integralBasis P.field.1)
          (LinearMap.BilinForm.toMatrix b P.Q.associated)).det : ℚ) : ℝ)| := by
      rw [hraw]
    _ = ((|NumberField.discr P.field.1| : ℤ) : ℝ) ^ P.rank *
          (Ideal.absNorm (Ideal.span ({G.det} : Set (𝓞 P.field.1))) : ℝ) := by
      rw [← Rat.cast_abs, habsQ]
      push_cast
      norm_cast

end GlobalLatticePresentation

end

end TraceEuclidean
