import TraceEuclidean.V15HunterCoefficientFiniteness
import TraceEuclidean.V15CubicGeneratorArithmetic
import TraceEuclidean.V15PowerBasisPolynomialDiscriminant

/-!
# The general power-family index relation

This module extends the cubic and quartic integral-index bridges to every
degree.  A primitive algebraic integer supplies the integral power family
`1, a, ..., a^(d-1)`.  Its discriminant is nonzero, and comparison with any
integral basis gives a strictly positive natural index whose square is the
ratio between the power-family and field discriminants.
-/

namespace TraceEuclidean

noncomputable section

open Algebra Module NumberField Polynomial
open scoped Matrix NumberField

/-- A degree-`d` number field admits an integral basis indexed by `Fin d`. -/
theorem v15_exists_ringOfIntegers_basis_fin
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (hdegree : Module.finrank ℚ K = d) :
    Nonempty (Basis (Fin d) ℤ (𝓞 K)) := by
  let e : Module.Free.ChooseBasisIndex ℤ (𝓞 K) ≃ Fin d :=
    Fintype.equivOfCardEq (by
      rw [← Module.finrank_eq_card_basis
        (NumberField.RingOfIntegers.basis K)]
      simpa using (NumberField.RingOfIntegers.rank K).trans hdegree)
  exact ⟨(NumberField.RingOfIntegers.basis K).reindex e⟩

/-- The integral power family `1, a, ..., a^(d-1)`. -/
def v15GeneralPowerFamily
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (a : 𝓞 K) : Fin d → 𝓞 K :=
  fun i ↦ a ^ (i : ℕ)

/-- After localization, the general integral power family is the rational
power basis generated by `a`. -/
theorem v15_generalPowerFamily_discr_eq_powerBasis
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (hdegree : Module.finrank ℚ K = d)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤) :
    Algebra.discr ℚ
        (fun i ↦ ((v15GeneralPowerFamily K d a i : 𝓞 K) : K)) =
      Algebra.discr ℚ
        (PowerBasis.ofAdjoinEqTop (IsIntegral.of_finite ℚ (a : K))
          (Algebra.adjoin_eq_top_of_primitive_element
            (IsIntegral.of_finite ℚ (a : K)).isAlgebraic hgen)).basis := by
  classical
  let hint : IsIntegral ℚ (a : K) := IsIntegral.of_finite ℚ (a : K)
  let hsub : Algebra.adjoin ℚ {(a : K)} = ⊤ :=
    Algebra.adjoin_eq_top_of_primitive_element hint.isAlgebraic hgen
  let pb : PowerBasis ℚ K := PowerBasis.ofAdjoinEqTop hint hsub
  have hdim : pb.dim = d := by
    rw [PowerBasis.ofAdjoinEqTop_dim]
    have h := hgen
    rw [Field.primitive_element_iff_minpoly_natDegree_eq] at h
    exact h.trans hdegree
  let e : Fin pb.dim ≃ Fin d := finCongr hdim
  change Algebra.discr ℚ
      (fun i ↦ ((v15GeneralPowerFamily K d a i : 𝓞 K) : K)) =
    Algebra.discr ℚ pb.basis
  rw [← Algebra.discr_reindex ℚ pb.basis e]
  congr 1
  ext i
  change ((v15GeneralPowerFamily K d a i : 𝓞 K) : K) =
    pb.basis (e.symm i)
  rw [pb.basis_eq_pow]
  have he : ((e.symm i : Fin pb.dim) : ℕ) = (i : ℕ) := rfl
  rw [he]
  have hpgen : pb.gen = (a : K) := rfl
  rw [hpgen]
  simp [v15GeneralPowerFamily]

/-- The discriminant of the integral power family is the polynomial
discriminant of the integral minimal polynomial of its generator. -/
theorem v15_generalPowerFamily_discr_eq_minpoly_discr
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (hdegree : Module.finrank ℚ K = d)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤) :
    Algebra.discr ℤ (v15GeneralPowerFamily K d a) =
      (minpoly ℤ (a : K)).discr := by
  classical
  let hint : IsIntegral ℚ (a : K) := IsIntegral.of_finite ℚ (a : K)
  let hsub : Algebra.adjoin ℚ {(a : K)} = ⊤ :=
    Algebra.adjoin_eq_top_of_primitive_element hint.isAlgebraic hgen
  let pb : PowerBasis ℚ K := PowerBasis.ofAdjoinEqTop hint hsub
  have hpgen : pb.gen = (a : K) := rfl
  have hmin :
      minpoly ℚ (a : K) =
        (minpoly ℤ (a : K)).map (algebraMap ℤ ℚ) :=
    minpoly.isIntegrallyClosed_eq_field_fractions'
      ℚ a.isIntegral_coe
  have hmonic : (minpoly ℤ (a : K)).Monic :=
    minpoly.monic a.isIntegral_coe
  have hpos : 0 < (minpoly ℤ (a : K)).natDegree := by
    have hpbpos : 0 < (minpoly ℚ pb.gen).natDegree := by
      simpa using pb.dim_pos
    rw [hpgen, hmin] at hpbpos
    have hmap := hmonic.natDegree_map (algebraMap ℤ ℚ)
    change ((minpoly ℤ (a : K)).map
      (algebraMap ℤ ℚ)).natDegree =
        (minpoly ℤ (a : K)).natDegree at hmap
    rw [hmap] at hpbpos
    exact hpbpos
  apply Rat.intCast_injective
  rw [v15_discr_ringOfIntegers_cast]
  rw [v15_generalPowerFamily_discr_eq_powerBasis
    K d hdegree a hgen]
  change Algebra.discr ℚ pb.basis = _
  rw [v15_powerBasis_discr_eq_minpoly_discr pb, hpgen, hmin]
  exact (v15_intCast_discr_eq_discr_map
    (minpoly ℤ (a : K)) hmonic hpos).symm

/-- The primitive integral power family has nonzero discriminant. -/
theorem v15_generalPowerFamily_discr_ne_zero
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (hdegree : Module.finrank ℚ K = d)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤) :
    Algebra.discr ℤ (v15GeneralPowerFamily K d a) ≠ 0 := by
  classical
  intro hzero
  have hcast := congrArg (fun z : ℤ ↦ (z : ℚ)) hzero
  rw [v15_discr_ringOfIntegers_cast] at hcast
  simp only [Int.cast_zero] at hcast
  rw [v15_generalPowerFamily_discr_eq_powerBasis
    K d hdegree a hgen] at hcast
  exact (Algebra.discr_not_zero_of_basis ℚ
    (PowerBasis.ofAdjoinEqTop (IsIntegral.of_finite ℚ (a : K))
      (Algebra.adjoin_eq_top_of_primitive_element
        (IsIntegral.of_finite ℚ (a : K)).isAlgebraic hgen)).basis) hcast

/-- The determinant of the integral power family in any integral basis gives
the square factor between the power-family and field discriminants. -/
theorem v15_generalPowerFamily_discr_eq_det_sq_mul_fieldDiscriminant
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (a : 𝓞 K)
    (bO : Basis (Fin d) ℤ (𝓞 K)) :
    Algebra.discr ℤ (v15GeneralPowerFamily K d a) =
      (bO.toMatrix (v15GeneralPowerFamily K d a)).det ^ 2 *
        NumberField.discr K := by
  classical
  let P := bO.toMatrix (v15GeneralPowerFamily K d a)
  change Algebra.discr ℤ (v15GeneralPowerFamily K d a) =
    P.det ^ 2 * NumberField.discr K
  calc
    Algebra.discr ℤ (v15GeneralPowerFamily K d a) =
        Algebra.discr ℤ
          (bO ᵥ* P.map (algebraMap ℤ (𝓞 K))) := by
      rw [bO.toMatrix_map_vecMul (v15GeneralPowerFamily K d a)]
    _ = P.det ^ 2 * Algebra.discr ℤ bO :=
      Algebra.discr_of_matrix_vecMul bO P
    _ = P.det ^ 2 * NumberField.discr K := by
      rw [NumberField.discr_eq_discr K bO]

/-- A primitive algebraic integer in an arbitrary-degree number field has a
strictly positive natural index with the exact discriminant relation. -/
theorem v15_generalPowerFamily_exists_positive_index
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (hdegree : Module.finrank ℚ K = d)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤)
    (bO : Basis (Fin d) ℤ (𝓞 K)) :
    ∃ index : ℕ, 0 < index ∧
      Algebra.discr ℤ (v15GeneralPowerFamily K d a) =
        (index : ℤ) ^ 2 * NumberField.discr K := by
  classical
  let P := bO.toMatrix (v15GeneralPowerFamily K d a)
  have hfamily : Algebra.discr ℤ (v15GeneralPowerFamily K d a) =
      P.det ^ 2 * NumberField.discr K := by
    exact v15_generalPowerFamily_discr_eq_det_sq_mul_fieldDiscriminant
      K d a bO
  have hdet : P.det ≠ 0 := by
    intro hzero
    apply v15_generalPowerFamily_discr_ne_zero
      K d hdegree a hgen
    rw [hfamily, hzero]
    norm_num
  refine ⟨P.det.natAbs, Int.natAbs_pos.mpr hdet, ?_⟩
  rw [hfamily]
  simp [sq_abs]

/-- The integral basis can be chosen internally in the general index
relation. -/
theorem v15_generalPowerFamily_exists_positive_index'
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (hdegree : Module.finrank ℚ K = d)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤) :
    ∃ index : ℕ, 0 < index ∧
      Algebra.discr ℤ (v15GeneralPowerFamily K d a) =
        (index : ℤ) ^ 2 * NumberField.discr K := by
  obtain ⟨bO⟩ := v15_exists_ringOfIntegers_basis_fin K d hdegree
  exact v15_generalPowerFamily_exists_positive_index
    K d hdegree a hgen bO

/-- The computable polynomial discriminant of a primitive integral
generator differs from the field discriminant by the square of a strictly
positive natural index. -/
theorem v15_minpoly_discr_exists_positive_index
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (hdegree : Module.finrank ℚ K = d)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤) :
    ∃ index : ℕ, 0 < index ∧
      (minpoly ℤ (a : K)).discr =
        (index : ℤ) ^ 2 * NumberField.discr K := by
  obtain ⟨index, hindexPos, hindex⟩ :=
    v15_generalPowerFamily_exists_positive_index'
      K d hdegree a hgen
  refine ⟨index, hindexPos, ?_⟩
  rw [← v15_generalPowerFamily_discr_eq_minpoly_discr
    K d hdegree a hgen]
  exact hindex

/-- A Hunter polynomial together with the primitive algebraic integer that
realizes it and the exact integral-index relation for the underlying field. -/
def V15HunterFieldPolynomialCandidate
    (K : Type*) [Field K] [NumberField K]
    (d : ℕ) (B : ℝ) (f : ℤ[X]) : Prop :=
  V15HunterPolynomialCandidate d B f ∧
    ∃ a : 𝓞 K,
      IntermediateField.adjoin ℚ {(a : K)} = ⊤ ∧
      f = minpoly ℤ (a : K) ∧
      ∃ index : ℕ, 0 < index ∧
        f.discr =
          (index : ℤ) ^ 2 * NumberField.discr K

open scoped Classical in
/-- The Hunter ball construction lands in the finite polynomial search
space while retaining a generator and its exact field-discriminant index. -/
theorem v15_exists_hunterFieldPolynomialCandidate_of_hunterBall
    (K : Type*) [Field K] [NumberField K] {n : ℕ}
    (hreal : NumberField.IsTotallyReal K)
    (hdegree : Module.finrank ℚ K = n + 1)
    (hprime : Nat.Prime (n + 1))
    (hn : 0 < n) (r : ℝ) (hr : 0 < r)
    (hball :
      ((|NumberField.discr K| : ℤ) : ℝ) *
          (((2 : ℝ) ^ n) ^ 2) <
        (n + 1 : ℝ) *
          (euclideanUnitBallVolume n * r ^ n) ^ 2) :
    ∃ f : ℤ[X],
      V15HunterFieldPolynomialCandidate K (n + 1)
        ((n + 1 : ℝ) * r ^ 2) f := by
  obtain ⟨a, hgen, hs1Nonneg, hs1Half, hspread⟩ :=
    v15_exists_trace_normalized_primitive_coefficients_of_hunterBall
      K hreal hdegree hprime hn r hr hball
  let f : ℤ[X] := minpoly ℤ (a : K)
  have hdegQ : (minpoly ℚ (a : K)).natDegree = n + 1 := by
    have h := hgen
    rw [Field.primitive_element_iff_minpoly_natDegree_eq] at h
    exact h.trans hdegree
  have hmin :
      f.map (algebraMap ℤ ℚ) = minpoly ℚ (a : K) := by
    simpa [f] using
      (minpoly.isIntegrallyClosed_eq_field_fractions'
        ℚ a.isIntegral_coe).symm
  have hdeg : f.natDegree = n + 1 := by
    have hmap := (minpoly.monic a.isIntegral_coe).natDegree_map
      (algebraMap ℤ ℚ)
    change (f.map (algebraMap ℤ ℚ)).natDegree = f.natDegree at hmap
    rw [hmin, hdegQ] at hmap
    exact hmap.symm
  have hcand : V15HunterPolynomialCandidate (n + 1)
      ((n + 1 : ℝ) * r ^ 2) f := by
    refine ⟨minpoly.monic a.isIntegral_coe,
      minpoly.irreducible a.isIntegral_coe, hdeg,
      v15_primitive_integral_minpoly_splits_real K hreal a hgen,
      ?_, ?_, ?_⟩
    · simpa [f, v15GeneralS1] using hs1Nonneg
    · simpa [f, v15GeneralS1] using hs1Half
    · simpa [f, v15GeneralS1, v15GeneralS2] using hspread
  obtain ⟨index, hindexPos, hindex⟩ :=
    v15_minpoly_discr_exists_positive_index
      K (n + 1) hdegree a hgen
  exact ⟨f, hcand, a, hgen, rfl, index, hindexPos, by
    simpa [f] using hindex⟩

/-- Field-realizable Hunter candidates form a finite subset of the general
finite Hunter polynomial set. -/
theorem v15_hunterFieldPolynomialCandidates_finite
    (K : Type*) [Field K] [NumberField K]
    {d : ℕ} (hd : 2 ≤ d) (B : ℝ) :
    Set.Finite {f : ℤ[X] |
      V15HunterFieldPolynomialCandidate K d B f} := by
  exact (v15_hunterPolynomialCandidates_finite hd B).subset
    (fun _ hf => hf.1)

end

end TraceEuclidean
