import TraceEuclidean.V15IdealCoordinates
import Mathlib.GroupTheory.Index

/-!
The final ideal-theoretic implication used in Theorem 1.7: when the principal
sublattice generated by one basis vector has relative index one in the
fractional ideal, the ideal is principal and the rank-one quadratic lattice
is obtained from a free one by scaling that vector.
-/

namespace TraceEuclidean

open scoped NumberField

noncomputable section

variable {F : Type*} [Field F] [NumberField F]

def v15PrincipalSubmodule (β : F) : Submodule (𝓞 F) F :=
  Submodule.span (𝓞 F) {β}

theorem v15_principal_submodule_le_ideal
    (I : FractionalIdeal (nonZeroDivisors (𝓞 F)) F)
    {β : F} (hβ : β ∈ I) :
    v15PrincipalSubmodule β ≤ I.coeToSubmodule := by
  unfold v15PrincipalSubmodule
  apply Submodule.span_le.mpr
  change β ∈ I.coeToSubmodule at hβ
  intro x hx
  have hx' : x = β := by simpa only [Set.mem_singleton_iff] using hx
  subst x
  exact hβ

theorem v15_ideal_principal_of_index_one
    (I : FractionalIdeal (nonZeroDivisors (𝓞 F)) F)
    {β : F} (hβ : β ∈ I)
    (hindex :
      (v15PrincipalSubmodule β).toAddSubgroup.relIndex
        I.coeToSubmodule.toAddSubgroup = 1) :
    I.coeToSubmodule = v15PrincipalSubmodule β := by
  have hle := v15_principal_submodule_le_ideal I hβ
  have hrev : I.coeToSubmodule.toAddSubgroup ≤
      (v15PrincipalSubmodule β).toAddSubgroup :=
    AddSubgroup.relIndex_eq_one.mp hindex
  apply le_antisymm
  · exact hrev
  · exact hle

/-- Index one produces an explicit `𝓞_F`-linear equivalence from the free
rank-one module to the original, possibly initially nonfree, ideal. -/
def v15_index_one_ideal_equiv
    (I : FractionalIdeal (nonZeroDivisors (𝓞 F)) F)
    {β : F} (hβ : β ∈ I) (hβ0 : β ≠ 0)
    (hindex :
      (v15PrincipalSubmodule β).toAddSubgroup.relIndex
        I.coeToSubmodule.toAddSubgroup = 1) :
    (𝓞 F) ≃ₗ[𝓞 F] I :=
  (LinearEquiv.toSpanNonzeroSingleton (𝓞 F) F β hβ0).trans
    (LinearEquiv.ofEq _ _
      (v15_ideal_principal_of_index_one I hβ hindex).symm)

@[simp]
theorem v15_index_one_ideal_equiv_apply
    (I : FractionalIdeal (nonZeroDivisors (𝓞 F)) F)
    {β : F} (hβ : β ∈ I) (hβ0 : β ≠ 0)
    (hindex :
      (v15PrincipalSubmodule β).toAddSubgroup.relIndex
        I.coeToSubmodule.toAddSubgroup = 1)
    (u : 𝓞 F) :
    ((v15_index_one_ideal_equiv I hβ hβ0 hindex u : I) : F) =
      (u : F) * β := by
  rfl

/-- The coefficient changes from `α` to `αβ²` under the index-one
identification of the ideal with `𝓞_F`. -/
theorem v15_index_one_quadratic_isometry
    (I : FractionalIdeal (nonZeroDivisors (𝓞 F)) F)
    {β : F} (hβ : β ∈ I) (hβ0 : β ≠ 0)
    (hindex :
      (v15PrincipalSubmodule β).toAddSubgroup.relIndex
        I.coeToSubmodule.toAddSubgroup = 1)
    (α : F) (u : 𝓞 F) :
    α * (((v15_index_one_ideal_equiv I hβ hβ0 hindex u : I) : F) ^ 2) =
      (α * β ^ 2) * (u : F) ^ 2 := by
  rw [v15_index_one_ideal_equiv_apply]
  ring

/-- A principal fractional ideal has an explicit linear equivalence with
the ring of integers, without choosing a presentation in advance. -/
def v15_principal_ideal_equiv
    (I : FractionalIdeal (nonZeroDivisors (𝓞 F)) F)
    {β : F} (hβ0 : β ≠ 0)
    (hprincipal : I = FractionalIdeal.spanSingleton
      (nonZeroDivisors (𝓞 F)) β) :
    (𝓞 F) ≃ₗ[𝓞 F] I :=
  (LinearEquiv.toSpanNonzeroSingleton (𝓞 F) F β hβ0).trans
    (LinearEquiv.ofEq _ _ (by
      rw [hprincipal]
      exact (FractionalIdeal.coe_spanSingleton _ β).symm))

@[simp]
theorem v15_principal_ideal_equiv_apply
    (I : FractionalIdeal (nonZeroDivisors (𝓞 F)) F)
    {β : F} (hβ0 : β ≠ 0)
    (hprincipal : I = FractionalIdeal.spanSingleton
      (nonZeroDivisors (𝓞 F)) β) (u : 𝓞 F) :
    ((v15_principal_ideal_equiv I hβ0 hprincipal u : I) : F) =
      (u : F) * β := by
  rfl

/-- Multiplication by the generator identifies the original quadratic
ideal lattice with the free rank-one lattice of coefficient `αβ²`. -/
theorem v15_principal_ideal_quadratic_isometry
    (I : FractionalIdeal (nonZeroDivisors (𝓞 F)) F)
    {β : F} (hβ0 : β ≠ 0)
    (hprincipal : I = FractionalIdeal.spanSingleton
      (nonZeroDivisors (𝓞 F)) β)
    (α : F) (u : 𝓞 F) :
    α * (((v15_principal_ideal_equiv I hβ0 hprincipal u : I) : F) ^ 2) =
      (α * β ^ 2) * (u : F) ^ 2 := by
  rw [v15_principal_ideal_equiv_apply]
  ring

end

end TraceEuclidean
