import TraceEuclidean.V15QuarticGeneratorNormalization
import TraceEuclidean.V15QuarticHermite
import Mathlib.RingTheory.Polynomial.Eisenstein.IsIntegral

/-!
# Maximality of the quartic order in the `2048` branch

The weak three-dimensional Minkowski bound leaves the polynomial
discriminants `2048` and `2304`.  This module closes the first branch.  The
polynomial `X^4 - 4 X^2 + 2` is Eisenstein at `2`; its discriminant is the
pure power `2^11`.  The discriminant denominator theorem and mathlib's
Eisenstein integrality theorem therefore show that its power order is the
full ring of integers.
-/

namespace TraceEuclidean

noncomputable section

open NumberField Module Polynomial
open scoped NumberField

private theorem v15_quarticPolynomial_2048_eq :
    v15QuarticPolynomial 0 (-4) 0 2 =
      X ^ 4 + (-(4 * X ^ 2) + 2) := by
  simp [v15QuarticPolynomial]
  ring

private theorem v15_quarticPolynomial_2048_monic :
    (v15QuarticPolynomial 0 (-4) 0 2).Monic := by
  rw [v15_quarticPolynomial_2048_eq]
  apply (monic_X_pow 4).add_of_left
  compute_degree
  norm_num

private theorem v15_quarticPolynomial_2048_natDegree :
    (v15QuarticPolynomial 0 (-4) 0 2).natDegree = 4 := by
  rw [v15_quarticPolynomial_2048_eq,
    natDegree_add_eq_left_of_natDegree_lt]
  · simp
  · compute_degree
    norm_num

/-- The quartic polynomial in the `2048` row is Eisenstein at `2`. -/
theorem v15_quarticPolynomial_2048_isEisensteinAt_two :
    (v15QuarticPolynomial 0 (-4) 0 2).IsEisensteinAt
      (Submodule.span ℤ {(2 : ℤ)}) := by
  refine Monic.isEisensteinAt_of_mem_of_notMem
    v15_quarticPolynomial_2048_monic ?_ (fun {i} hi => ?_) ?_
  · rw [Ideal.ne_top_iff_one, Ideal.mem_span_singleton]
    norm_num
  · have hi' : i < 4 := by
      simpa [v15_quarticPolynomial_2048_natDegree] using hi
    interval_cases i <;>
      simp [v15QuarticPolynomial, Ideal.mem_span_singleton]
  · rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    norm_num [v15QuarticPolynomial]

/-- In the `2048` row, every algebraic integer already belongs to the power
order generated by `a`. -/
theorem v15_quartic_2048_all_integral_mem_adjoin
    (K : Type*) [Field K] [NumberField K]
    (hdegree : Module.finrank ℚ K = 4)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤)
    (hs1 : v15QuarticS1 K a = 0)
    (hs2 : v15QuarticS2 K a = -4)
    (hs3 : v15QuarticS3 K a = 0)
    (hs4 : v15QuarticS4 K a = 2) :
    ∀ x : K, IsIntegral ℤ x → x ∈ Algebra.adjoin ℤ {(a : K)} := by
  intro x hx
  let hint : IsIntegral ℚ (a : K) := IsIntegral.of_finite ℚ (a : K)
  let hsub : Algebra.adjoin ℚ {(a : K)} = ⊤ :=
    Algebra.adjoin_eq_top_of_primitive_element hint.isAlgebraic hgen
  let B : PowerBasis ℚ K := PowerBasis.ofAdjoinEqTop hint hsub
  have hBgen : B.gen = (a : K) := by
    simp [B, PowerBasis.ofAdjoinEqTop]
  have hBint : IsIntegral ℤ B.gen := by
    rw [hBgen]
    exact a.isIntegral_coe
  have hdisc : Algebra.discr ℚ B.basis = (2 : ℚ) ^ 11 := by
    rw [← v15_quarticPowerFamily_discr_eq_powerBasis
      K hdegree a hgen]
    rw [← v15_discr_ringOfIntegers_cast]
    rw [v15_quarticPowerFamily_discr_eq_quarticDiscriminant
      K hdegree a hgen, hs1, hs2, hs3, hs4]
    norm_num [v15QuarticDiscriminant]
  have H := Algebra.discr_mul_isIntegral_mem_adjoin ℚ hBint hx
  rw [hdisc] at H
  have H' : (2 : ℤ) ^ 11 • x ∈
      Algebra.adjoin ℤ ({B.gen} : Set K) := by
    norm_num [Algebra.smul_def, zsmul_eq_mul] at H ⊢
    exact H
  have hmin : minpoly ℤ B.gen =
      v15QuarticPolynomial 0 (-4) 0 2 := by
    rw [hBgen, ← v15_quarticPolynomial_eq_minpoly
      K hdegree a hgen, hs1, hs2, hs3, hs4]
  have hei : (minpoly ℤ B.gen).IsEisensteinAt
      (Submodule.span ℤ {(2 : ℤ)}) := by
    rw [hmin]
    exact v15_quarticPolynomial_2048_isEisensteinAt_two
  have hxmem :=
    mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt
      (p := (2 : ℤ)) (n := 11) (show Prime (2 : ℤ) by norm_num)
      hBint hx H' hei
  simpa [hBgen] using hxmem

/-- In the `2048` row, the integral generator `a` generates the full ring
of integers as a `ℤ`-algebra. -/
theorem v15_quartic_2048_adjoin_ringOfIntegers_eq_top
    (K : Type*) [Field K] [NumberField K]
    (hdegree : Module.finrank ℚ K = 4)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤)
    (hs1 : v15QuarticS1 K a = 0)
    (hs2 : v15QuarticS2 K a = -4)
    (hs3 : v15QuarticS3 K a = 0)
    (hs4 : v15QuarticS4 K a = 2) :
    Algebra.adjoin ℤ ({a} : Set (𝓞 K)) = ⊤ := by
  apply top_unique
  intro z _
  let f : 𝓞 K →ₐ[ℤ] K := IsScalarTower.toAlgHom ℤ (𝓞 K) K
  have hz : (z : K) ∈ Algebra.adjoin ℤ ({(a : K)} : Set K) :=
    v15_quartic_2048_all_integral_mem_adjoin
      K hdegree a hgen hs1 hs2 hs3 hs4 z z.isIntegral_coe
  have hmap :
      Subalgebra.map f (Algebra.adjoin ℤ ({a} : Set (𝓞 K))) =
        Algebra.adjoin ℤ ({(a : K)} : Set K) := by
    rw [AlgHom.map_adjoin_singleton]
    rfl
  rw [← hmap] at hz
  obtain ⟨y, hy, hyz⟩ := hz
  have : y = z := by
    apply Subtype.ext
    exact hyz
  rwa [this] at hy

/-- A quartic field generated by the `2048` row has field discriminant
`2048`; in particular the apparent nontrivial-index alternative cannot
occur. -/
theorem v15_quartic_field_discriminant_eq_2048
    (K : Type*) [Field K] [NumberField K]
    (hdegree : Module.finrank ℚ K = 4)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤)
    (hs1 : v15QuarticS1 K a = 0)
    (hs2 : v15QuarticS2 K a = -4)
    (hs3 : v15QuarticS3 K a = 0)
    (hs4 : v15QuarticS4 K a = 2) :
    NumberField.discr K = 2048 := by
  classical
  let htop : Algebra.adjoin ℤ ({a} : Set (𝓞 K)) = ⊤ :=
    v15_quartic_2048_adjoin_ringOfIntegers_eq_top
      K hdegree a hgen hs1 hs2 hs3 hs4
  let pb : PowerBasis ℤ (𝓞 K) :=
    PowerBasis.ofAdjoinEqTop' (RingOfIntegers.isIntegral a) htop
  have hdim : pb.dim = 4 := by
    rw [← PowerBasis.finrank, RingOfIntegers.rank, hdegree]
  let e : Fin pb.dim ≃ Fin 4 := finCongr hdim
  have hfamily : Algebra.discr ℤ (v15QuarticPowerFamily K a) =
      Algebra.discr ℤ pb.basis := by
    rw [← Algebra.discr_reindex ℤ pb.basis e]
    congr 1
    ext i
    simp only [Function.comp_apply]
    apply congrArg (fun z : 𝓞 K ↦ (z : K))
    change v15QuarticPowerFamily K a i = pb.basis (e.symm i)
    rw [pb.basis_eq_pow]
    have he : ((e.symm i : Fin pb.dim) : ℕ) = (i : ℕ) := rfl
    rw [he]
    fin_cases i <;> simp [v15QuarticPowerFamily, pb]
  calc
    NumberField.discr K = Algebra.discr ℤ pb.basis :=
      (NumberField.discr_eq_discr K pb.basis).symm
    _ = Algebra.discr ℤ (v15QuarticPowerFamily K a) := hfamily.symm
    _ = v15QuarticDiscriminant (v15QuarticS1 K a)
        (v15QuarticS2 K a) (v15QuarticS3 K a)
        (v15QuarticS4 K a) :=
      v15_quarticPowerFamily_discr_eq_quarticDiscriminant
        K hdegree a hgen
    _ = 2048 := by
      rw [hs1, hs2, hs3, hs4]
      norm_num [v15QuarticDiscriminant]

private theorem v15_quarticPolynomial_2304_shift_eq :
    (v15QuarticPolynomial 0 (-4) 0 1).comp (X + C 1) =
      X ^ 4 + (4 * X ^ 3 + 2 * X ^ 2 - 4 * X - 2) := by
  simp [v15QuarticPolynomial]
  ring

private theorem v15_quarticPolynomial_2304_shift_monic :
    ((v15QuarticPolynomial 0 (-4) 0 1).comp
      (X + C 1)).Monic := by
  rw [v15_quarticPolynomial_2304_shift_eq]
  apply (monic_X_pow 4).add_of_left
  compute_degree
  norm_num

private theorem v15_quarticPolynomial_2304_shift_natDegree :
    ((v15QuarticPolynomial 0 (-4) 0 1).comp
      (X + C 1)).natDegree = 4 := by
  rw [v15_quarticPolynomial_2304_shift_eq,
    natDegree_add_eq_left_of_natDegree_lt]
  · simp
  · compute_degree
    norm_num

/-- Translating the `2304` polynomial by one produces a polynomial that is
Eisenstein at `2`. -/
theorem v15_quarticPolynomial_2304_shift_isEisensteinAt_two :
    ((v15QuarticPolynomial 0 (-4) 0 1).comp
      (X + C 1)).IsEisensteinAt
        (Submodule.span ℤ {(2 : ℤ)}) := by
  refine Monic.isEisensteinAt_of_mem_of_notMem
    v15_quarticPolynomial_2304_shift_monic ?_ (fun {i} hi => ?_) ?_
  · rw [Ideal.ne_top_iff_one, Ideal.mem_span_singleton]
    norm_num
  · have hi' : i < 4 := by
      rw [v15_quarticPolynomial_2304_shift_natDegree] at hi
      exact hi
    rw [v15_quarticPolynomial_2304_shift_eq]
    interval_cases i <;>
      simp [Ideal.mem_span_singleton, coeff_X]
  · rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    rw [v15_quarticPolynomial_2304_shift_eq]
    norm_num

/-- In the `2304` row, every algebraic integer becomes an element of the
power order after multiplication by `9`.  Thus this branch has no residual
`2`-primary denominator; only the `3`-primary saturation remains. -/
theorem v15_quartic_2304_nine_smul_integral_mem_adjoin
    (K : Type*) [Field K] [NumberField K]
    (hdegree : Module.finrank ℚ K = 4)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤)
    (hs1 : v15QuarticS1 K a = 0)
    (hs2 : v15QuarticS2 K a = -4)
    (hs3 : v15QuarticS3 K a = 0)
    (hs4 : v15QuarticS4 K a = 1) :
    ∀ x : K, IsIntegral ℤ x →
      (3 : ℤ) ^ 2 • x ∈ Algebra.adjoin ℤ {(a : K)} := by
  intro x hx
  let beta : K := (a : K) - 1
  have hbetaInt : IsIntegral ℤ beta := by
    exact a.isIntegral_coe.sub isIntegral_one
  let hintA : IsIntegral ℚ (a : K) :=
    IsIntegral.of_finite ℚ (a : K)
  let hsubA : Algebra.adjoin ℚ {(a : K)} = ⊤ :=
    Algebra.adjoin_eq_top_of_primitive_element hintA.isAlgebraic hgen
  have hsubBeta : Algebra.adjoin ℚ {beta} = ⊤ := by
    apply top_unique
    rw [← hsubA]
    apply Algebra.adjoin_le
    rw [Set.singleton_subset_iff]
    have hbetaMem : beta ∈ Algebra.adjoin ℚ ({beta} : Set K) :=
      Algebra.subset_adjoin (Set.mem_singleton beta)
    have hone : (1 : K) ∈ Algebra.adjoin ℚ ({beta} : Set K) :=
      Subalgebra.one_mem _
    have hadd := Subalgebra.add_mem _ hbetaMem hone
    simpa [beta] using hadd
  let hintBeta : IsIntegral ℚ beta := IsIntegral.of_finite ℚ beta
  let B : PowerBasis ℚ K :=
    PowerBasis.ofAdjoinEqTop hintBeta hsubBeta
  have hBgen : B.gen = beta := by
    simp [B, PowerBasis.ofAdjoinEqTop]
  have hBint : IsIntegral ℤ B.gen := by
    rw [hBgen]
    exact hbetaInt
  have hdim : B.dim = 4 := by
    rw [PowerBasis.ofAdjoinEqTop_dim]
    exact (PowerBasis.finrank B).symm.trans hdegree
  have hminA : minpoly ℤ (a : K) =
      v15QuarticPolynomial 0 (-4) 0 1 := by
    rw [← v15_quarticPolynomial_eq_minpoly K hdegree a hgen,
      hs1, hs2, hs3, hs4]
  have hminBeta : minpoly ℤ beta =
      (v15QuarticPolynomial 0 (-4) 0 1).comp (X + C 1) := by
    apply Polynomial.map_injective (algebraMap ℤ ℚ)
      (algebraMap ℤ ℚ).injective_int
    rw [← minpoly.isIntegrallyClosed_eq_field_fractions' ℚ hbetaInt,
      map_comp]
    simp only [map_one]
    have h := minpoly.sub_algebraMap (A := ℚ) (a : K) (1 : ℚ)
    have hminAQ : minpoly ℚ (a : K) =
        (v15QuarticPolynomial 0 (-4) 0 1).map
          (algebraMap ℤ ℚ) := by
      rw [← hminA]
      exact minpoly.isIntegrallyClosed_eq_field_fractions'
        ℚ a.isIntegral_coe
    rw [hminAQ] at h
    simpa [beta] using h
  have hdisc : Algebra.discr ℚ B.basis = (2304 : ℚ) := by
    rw [v15_powerBasis_discr_dim_four B hdim]
    have hminMap : B.minpolyGen =
        (minpoly ℤ B.gen).map (algebraMap ℤ ℚ) := by
      rw [B.minpolyGen_eq]
      exact minpoly.isIntegrallyClosed_eq_field_fractions' ℚ hBint
    rw [hminMap, hBgen, hminBeta,
      v15_quarticPolynomial_2304_shift_eq]
    simp only [Polynomial.coeff_map]
    norm_num [coeff_X]
  have H := Algebra.discr_mul_isIntegral_mem_adjoin ℚ hBint hx
  rw [hdisc] at H
  have H' : (2 : ℤ) ^ 8 • ((3 : ℤ) ^ 2 • x) ∈
      Algebra.adjoin ℤ ({B.gen} : Set K) := by
    norm_num [Algebra.smul_def, zsmul_eq_mul] at H ⊢
    rw [← mul_assoc]
    norm_num
    exact H
  have hei : (minpoly ℤ B.gen).IsEisensteinAt
      (Submodule.span ℤ {(2 : ℤ)}) := by
    rw [hBgen, hminBeta]
    exact v15_quarticPolynomial_2304_shift_isEisensteinAt_two
  have h9mem :=
    mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt
      (p := (2 : ℤ)) (n := 8) (show Prime (2 : ℤ) by norm_num)
      hBint (hx.smul _) H' hei
  have h9memBeta : (3 : ℤ) ^ 2 • x ∈
      Algebra.adjoin ℤ ({beta} : Set K) := by
    simpa [hBgen] using h9mem
  apply (Algebra.adjoin_le (show ({beta} : Set K) ⊆
    Algebra.adjoin ℤ ({(a : K)} : Set K) by
      rw [Set.singleton_subset_iff]
      exact Subalgebra.sub_mem _
        (Algebra.subset_adjoin (Set.mem_singleton (a : K)))
        (Subalgebra.one_mem _))) h9memBeta

/-- A primitive quartic generator satisfying the unconditional spread bound
can be normalized as an actual algebraic integer.  If the field
discriminant lies strictly between `29` and `725`, its normalized row is
exactly the `2048` or `2304` row. -/
theorem v15_quartic_weak_minkowski_normalized_row_2048_or_2304
    (K : Type*) [Field K] [NumberField K]
    (hreal : NumberField.IsTotallyReal K)
    (hdegree : Module.finrank ℚ K = 4)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤)
    (hspreadLt : v15QuarticSpread (v15QuarticS1 K a)
      (v15QuarticS2 K a) < 35)
    (hfieldLower : 29 < NumberField.discr K)
    (hfieldUpper : NumberField.discr K < 725) :
    ∃ b : 𝓞 K,
      IntermediateField.adjoin ℚ {(b : K)} = ⊤ ∧
      ((v15QuarticS1 K b = 0 ∧ v15QuarticS2 K b = -4 ∧
          v15QuarticS3 K b = 0 ∧ v15QuarticS4 K b = 2) ∨
        (v15QuarticS1 K b = 0 ∧ v15QuarticS2 K b = -4 ∧
          v15QuarticS3 K b = 0 ∧ v15QuarticS4 K b = 1)) := by
  rcases v15_exists_normalized_quartic_generator K hdegree a hgen with
    ⟨b, hgenb, hs1, hspreadEq, hminorEq, hdiscEq⟩
  have hspreadPosA := v15_quarticSpread_pos K hreal hdegree a hgen
  have hminorA :=
    v15_quarticHermiteMinorThree_pos K hreal hdegree a hgen
  have hspreadPosB : 0 < v15QuarticSpread
      (v15QuarticS1 K b) (v15QuarticS2 K b) := by
    rw [hspreadEq]
    exact hspreadPosA
  have hspreadLtB : v15QuarticSpread
      (v15QuarticS1 K b) (v15QuarticS2 K b) < 35 := by
    rw [hspreadEq]
    exact hspreadLt
  have hminorB : 0 < v15QuarticHermiteMinorThree
      (v15QuarticS1 K b) (v15QuarticS2 K b)
      (v15QuarticS3 K b) (v15QuarticS4 K b) := by
    rw [hminorEq]
    exact hminorA
  obtain ⟨bO⟩ := v15_exists_ringOfIntegers_basis_fin_four K hdegree
  obtain ⟨index, hindex, hrelation⟩ :=
    v15_quartic_exists_positive_index K hdegree b hgenb bO
  have hfieldPos : 0 < NumberField.discr K := by omega
  have hindexInt : (0 : ℤ) < index := by exact_mod_cast hindex
  have hsquare : (0 : ℤ) < (index : ℤ) ^ 2 :=
    sq_pos_of_pos hindexInt
  have hdiscPosB : 0 < v15QuarticDiscriminant
      (v15QuarticS1 K b) (v15QuarticS2 K b)
      (v15QuarticS3 K b) (v15QuarticS4 K b) := by
    rw [hrelation]
    exact mul_pos hsquare hfieldPos
  have hs2 := v15_quartic_s2_bounds_of_normalized_thirtyFive
    (v15QuarticS1 K b) (v15QuarticS2 K b) hs1
      hspreadPosB hspreadLtB
  have hs2Upper : v15QuarticS2 K b ≤ 2 := by omega
  obtain ⟨hs3, hs3', hs4, hs4'⟩ :=
    v15_quartic_s3_s4_bounds_of_normalized_thirtyFive
      (v15QuarticS1 K b) (v15QuarticS2 K b)
      (v15QuarticS3 K b) (v15QuarticS4 K b)
      hs1 hspreadPosB hspreadLtB hminorB hdiscPosB
  have hs1Bounds : 0 ≤ v15QuarticS1 K b ∧
      v15QuarticS1 K b ≤ 2 := by omega
  have hnoRoot := v15_quartic_minpoly_no_integer_root
    K hdegree b hgenb
  have hnoQuadratic := v15_quartic_minpoly_no_quadratic_factor
    K hdegree b hgenb
  have hrows := v15_normalized_quartic_rows_of_spread_lt_thirtyFive
    (v15QuarticS1 K b) (v15QuarticS2 K b)
    (v15QuarticS3 K b) (v15QuarticS4 K b)
    hs1Bounds.1 hs1Bounds.2 hs2.1 hs2Upper hs3 hs3' hs4 hs4'
    hspreadPosB hspreadLtB hminorB hdiscPosB hnoRoot hnoQuadratic
  have hcandidates :=
    v15_normalized_quartic_discriminant_candidates_of_spread_lt_thirtyFive
      (v15QuarticS1 K b) (v15QuarticS2 K b)
      (v15QuarticS3 K b) (v15QuarticS4 K b)
      hs1Bounds.1 hs1Bounds.2 hs2.1 hs2Upper hs3 hs3' hs4 hs4'
      hspreadPosB hspreadLtB hminorB hdiscPosB hnoRoot hnoQuadratic
  have htwo := v15_quartic_small_field_candidates_reduce_to_2048_or_2304
    (v15QuarticS1 K b) (v15QuarticS2 K b)
    (v15QuarticS3 K b) (v15QuarticS4 K b)
    (NumberField.discr K) index hindex hfieldLower hfieldUpper
    hrelation hcandidates
  refine ⟨b, hgenb, ?_⟩
  rcases hrows with h | h | h | h | h | h
  all_goals rcases h with ⟨h1, h2, h3, h4⟩
  · rw [h1, h2, h3, h4] at htwo
    norm_num [v15QuarticDiscriminant] at htwo
  · exact Or.inr ⟨h1, h2, h3, h4⟩
  · exact Or.inl ⟨h1, h2, h3, h4⟩
  · rw [h1, h2, h3, h4] at htwo
    norm_num [v15QuarticDiscriminant] at htwo
  · rw [h1, h2, h3, h4] at htwo
    norm_num [v15QuarticDiscriminant] at htwo
  · rw [h1, h2, h3, h4] at htwo
    norm_num [v15QuarticDiscriminant] at htwo

/-- The `2048` row in the preceding theorem is impossible below field
discriminant `725`: its power order is already maximal and hence the field
discriminant is `2048`.  The weak Minkowski route therefore leaves only the
single normalized `2304` row. -/
theorem v15_quartic_weak_minkowski_normalized_row_2304
    (K : Type*) [Field K] [NumberField K]
    (hreal : NumberField.IsTotallyReal K)
    (hdegree : Module.finrank ℚ K = 4)
    (a : 𝓞 K)
    (hgen : IntermediateField.adjoin ℚ {(a : K)} = ⊤)
    (hspreadLt : v15QuarticSpread (v15QuarticS1 K a)
      (v15QuarticS2 K a) < 35)
    (hfieldLower : 29 < NumberField.discr K)
    (hfieldUpper : NumberField.discr K < 725) :
    ∃ b : 𝓞 K,
      IntermediateField.adjoin ℚ {(b : K)} = ⊤ ∧
      v15QuarticS1 K b = 0 ∧ v15QuarticS2 K b = -4 ∧
      v15QuarticS3 K b = 0 ∧ v15QuarticS4 K b = 1 := by
  rcases v15_quartic_weak_minkowski_normalized_row_2048_or_2304
      K hreal hdegree a hgen hspreadLt hfieldLower hfieldUpper with
    ⟨b, hgenb, h2048 | h2304⟩
  · rcases h2048 with ⟨hs1, hs2, hs3, hs4⟩
    have hfield := v15_quartic_field_discriminant_eq_2048
      K hdegree b hgenb hs1 hs2 hs3 hs4
    omega
  · exact ⟨b, hgenb, h2304⟩

end

end TraceEuclidean
