import TraceEuclidean.V15VoightResultantCertificates.FiveChunk0
import TraceEuclidean.V15VoightResultantCertificates.FiveChunk1
import TraceEuclidean.V15VoightResultantCertificates.FiveChunk2
import TraceEuclidean.V15VoightResultantCertificates.FiveChunk3
import TraceEuclidean.V15VoightResultantCertificates.FiveChunk4
import TraceEuclidean.V15VoightResultantCertificates.FiveChunk5
import TraceEuclidean.V15VoightResultantCertificates.FiveChunk6
import TraceEuclidean.V15VoightResultantCertificates.SixChunk0
import TraceEuclidean.V15VoightResultantCertificates.SixChunk1
import TraceEuclidean.V15VoightResultantCertificates.SixChunk2
import TraceEuclidean.V15VoightResultantCertificates.SixChunk3
import TraceEuclidean.V15VoightResultantCertificates.SixChunk4
import TraceEuclidean.V15VoightResultantCertificates.SixChunk5
import TraceEuclidean.V15VoightResultantCertificates.SixChunk6
import TraceEuclidean.V15VoightResultantCertificates.SixChunk7
import TraceEuclidean.V15VoightResultantCertificates.SixChunk8
import TraceEuclidean.V15VoightResultantCertificates.SevenChunk0
import TraceEuclidean.V15VoightResultantCertificates.SevenChunk1
import TraceEuclidean.V15VoightResultantCertificates.SevenChunk2
import TraceEuclidean.V15VoightResultantCertificates.SevenChunk3
import TraceEuclidean.V15VoightResultantCertificates.EightChunk0
import TraceEuclidean.V15VoightResultantCertificates.EightChunk1
import TraceEuclidean.V15VoightResultantCertificates.NineChunk0
import TraceEuclidean.V15VoightResultantCertificates.TenChunk0
import TraceEuclidean.V15VoightResultantCertificates.TenChunk1
import TraceEuclidean.V15VoightResultantCertificates.TenChunk2
import TraceEuclidean.V15VoightResultantCertificates.TenChunk3
import TraceEuclidean.V15VoightResultantCertificates.TenChunk4
import TraceEuclidean.V15VoightResultantCertificates.TenChunk5
import TraceEuclidean.V15VoightResultantCertificates.TenChunk6
import TraceEuclidean.V15VoightResultantCertificates.TenChunk7

/-!
# Exact resultant certificates for all archived Voight rows

This file is generated by `tools/generate_voight_discriminant_data.py`.
Each native theorem checks at most one hundred rows so successful
certificates are cached independently and failures are localized.
-/

namespace TraceEuclidean

theorem v15_voightPolynomialRowsFive_resultant_certificate :
    v15VoightPolynomialRowsFive.all
      (v15VoightResultantCertificate 5) = true := by
  simp only [
    v15VoightPolynomialRowsFive,
    List.all_append,
    v15_voightPolynomialRowsFiveChunk0_resultant_certificate,
    v15_voightPolynomialRowsFiveChunk1_resultant_certificate,
    v15_voightPolynomialRowsFiveChunk2_resultant_certificate,
    v15_voightPolynomialRowsFiveChunk3_resultant_certificate,
    v15_voightPolynomialRowsFiveChunk4_resultant_certificate,
    v15_voightPolynomialRowsFiveChunk5_resultant_certificate,
    v15_voightPolynomialRowsFiveChunk6_resultant_certificate,
    Bool.and_true
  ]

theorem v15_voightPolynomialRowsSix_resultant_certificate :
    v15VoightPolynomialRowsSix.all
      (v15VoightResultantCertificate 6) = true := by
  simp only [
    v15VoightPolynomialRowsSix,
    List.all_append,
    v15_voightPolynomialRowsSixChunk0_resultant_certificate,
    v15_voightPolynomialRowsSixChunk1_resultant_certificate,
    v15_voightPolynomialRowsSixChunk2_resultant_certificate,
    v15_voightPolynomialRowsSixChunk3_resultant_certificate,
    v15_voightPolynomialRowsSixChunk4_resultant_certificate,
    v15_voightPolynomialRowsSixChunk5_resultant_certificate,
    v15_voightPolynomialRowsSixChunk6_resultant_certificate,
    v15_voightPolynomialRowsSixChunk7_resultant_certificate,
    v15_voightPolynomialRowsSixChunk8_resultant_certificate,
    Bool.and_true
  ]

theorem v15_voightPolynomialRowsSeven_resultant_certificate :
    v15VoightPolynomialRowsSeven.all
      (v15VoightResultantCertificate 7) = true := by
  simp only [
    v15VoightPolynomialRowsSeven,
    List.all_append,
    v15_voightPolynomialRowsSevenChunk0_resultant_certificate,
    v15_voightPolynomialRowsSevenChunk1_resultant_certificate,
    v15_voightPolynomialRowsSevenChunk2_resultant_certificate,
    v15_voightPolynomialRowsSevenChunk3_resultant_certificate,
    Bool.and_true
  ]

theorem v15_voightPolynomialRowsEight_resultant_certificate :
    v15VoightPolynomialRowsEight.all
      (v15VoightResultantCertificate 8) = true := by
  simp only [
    v15VoightPolynomialRowsEight,
    List.all_append,
    v15_voightPolynomialRowsEightChunk0_resultant_certificate,
    v15_voightPolynomialRowsEightChunk1_resultant_certificate,
    Bool.and_true
  ]

theorem v15_voightPolynomialRowsNine_resultant_certificate :
    v15VoightPolynomialRowsNine.all
      (v15VoightResultantCertificate 9) = true := by
  simp only [
    v15VoightPolynomialRowsNine,
    v15_voightPolynomialRowsNineChunk0_resultant_certificate
  ]

theorem v15_voightPolynomialRowsTen_resultant_certificate :
    v15VoightPolynomialRowsTen.all
      (v15VoightResultantCertificate 10) = true := by
  simp only [
    v15VoightPolynomialRowsTen,
    List.all_append,
    v15_voightPolynomialRowsTenChunk0_resultant_certificate,
    v15_voightPolynomialRowsTenChunk1_resultant_certificate,
    v15_voightPolynomialRowsTenChunk2_resultant_certificate,
    v15_voightPolynomialRowsTenChunk3_resultant_certificate,
    v15_voightPolynomialRowsTenChunk4_resultant_certificate,
    v15_voightPolynomialRowsTenChunk5_resultant_certificate,
    v15_voightPolynomialRowsTenChunk6_resultant_certificate,
    v15_voightPolynomialRowsTenChunk7_resultant_certificate,
    Bool.and_true
  ]

/-- All 2773 archived polynomial rows have exact rational
row-reduction certificates for their claimed resultants. -/
theorem v15_allVoightPolynomialRows_resultant_certificate :
    v15VoightPolynomialRowsFive.all
      (v15VoightResultantCertificate 5) = true ∧
    v15VoightPolynomialRowsSix.all
      (v15VoightResultantCertificate 6) = true ∧
    v15VoightPolynomialRowsSeven.all
      (v15VoightResultantCertificate 7) = true ∧
    v15VoightPolynomialRowsEight.all
      (v15VoightResultantCertificate 8) = true ∧
    v15VoightPolynomialRowsNine.all
      (v15VoightResultantCertificate 9) = true ∧
    v15VoightPolynomialRowsTen.all
      (v15VoightResultantCertificate 10) = true := by
  exact ⟨
    v15_voightPolynomialRowsFive_resultant_certificate,
    v15_voightPolynomialRowsSix_resultant_certificate,
    v15_voightPolynomialRowsSeven_resultant_certificate,
    v15_voightPolynomialRowsEight_resultant_certificate,
    v15_voightPolynomialRowsNine_resultant_certificate,
    v15_voightPolynomialRowsTen_resultant_certificate
  ⟩

/-- The certificate for the table selected by any degree. -/
theorem v15_voightPolynomialRows_resultant_certificate (degree : ℕ) :
    (v15VoightPolynomialRows degree).all
      (v15VoightResultantCertificate degree) = true :=
  match degree with
  | 0 => by rfl
  | 1 => by rfl
  | 2 => by rfl
  | 3 => by rfl
  | 4 => by rfl
  | 5 => v15_voightPolynomialRowsFive_resultant_certificate
  | 6 => v15_voightPolynomialRowsSix_resultant_certificate
  | 7 => v15_voightPolynomialRowsSeven_resultant_certificate
  | 8 => v15_voightPolynomialRowsEight_resultant_certificate
  | 9 => v15_voightPolynomialRowsNine_resultant_certificate
  | 10 => v15_voightPolynomialRowsTen_resultant_certificate
  | .succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (degree))))))))))) => by rfl

/-- Every row in the table selected by a degree has the recorded
coefficient length, monicity, positive discriminant, and positive index. -/
theorem v15_voightPolynomialRows_structural_certificate (degree : ℕ) :
    (v15VoightPolynomialRows degree).all
      (V15VoightPolynomialRow.structurallyValid degree) = true :=
  match degree with
  | 0 => by rfl
  | 1 => by rfl
  | 2 => by rfl
  | 3 => by rfl
  | 4 => by rfl
  | 5 => v15_voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.1
  | 6 => v15_voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.1
  | 7 => v15_voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.2.1
  | 8 => v15_voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1
  | 9 => v15_voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1
  | 10 => v15_voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1
  | .succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (degree))))))))))) => by rfl

end TraceEuclidean
