import TraceEuclidean.VoightResultantCertificates.FiveChunk0
import TraceEuclidean.VoightResultantCertificates.FiveChunk1
import TraceEuclidean.VoightResultantCertificates.FiveChunk2
import TraceEuclidean.VoightResultantCertificates.FiveChunk3
import TraceEuclidean.VoightResultantCertificates.FiveChunk4
import TraceEuclidean.VoightResultantCertificates.FiveChunk5
import TraceEuclidean.VoightResultantCertificates.FiveChunk6
import TraceEuclidean.VoightResultantCertificates.SixChunk0
import TraceEuclidean.VoightResultantCertificates.SixChunk1
import TraceEuclidean.VoightResultantCertificates.SixChunk2
import TraceEuclidean.VoightResultantCertificates.SixChunk3
import TraceEuclidean.VoightResultantCertificates.SixChunk4
import TraceEuclidean.VoightResultantCertificates.SixChunk5
import TraceEuclidean.VoightResultantCertificates.SixChunk6
import TraceEuclidean.VoightResultantCertificates.SixChunk7
import TraceEuclidean.VoightResultantCertificates.SixChunk8
import TraceEuclidean.VoightResultantCertificates.SevenChunk0
import TraceEuclidean.VoightResultantCertificates.SevenChunk1
import TraceEuclidean.VoightResultantCertificates.SevenChunk2
import TraceEuclidean.VoightResultantCertificates.SevenChunk3
import TraceEuclidean.VoightResultantCertificates.EightChunk0
import TraceEuclidean.VoightResultantCertificates.EightChunk1
import TraceEuclidean.VoightResultantCertificates.NineChunk0
import TraceEuclidean.VoightResultantCertificates.TenChunk0
import TraceEuclidean.VoightResultantCertificates.TenChunk1
import TraceEuclidean.VoightResultantCertificates.TenChunk2
import TraceEuclidean.VoightResultantCertificates.TenChunk3
import TraceEuclidean.VoightResultantCertificates.TenChunk4
import TraceEuclidean.VoightResultantCertificates.TenChunk5
import TraceEuclidean.VoightResultantCertificates.TenChunk6
import TraceEuclidean.VoightResultantCertificates.TenChunk7

/-!
# Exact resultant certificates for all archived Voight rows

This file is generated by `tools/generate_voight_discriminant_data.py`.
Each native theorem checks at most one hundred rows so successful
certificates are cached independently and failures are localized.
-/

namespace TraceEuclidean

theorem voightPolynomialRowsFive_resultant_certificate :
    voightPolynomialRowsFive.all
      (voightResultantCertificate 5) = true := by
  simp only [
    voightPolynomialRowsFive,
    List.all_append,
    voightPolynomialRowsFiveChunk0_resultant_certificate,
    voightPolynomialRowsFiveChunk1_resultant_certificate,
    voightPolynomialRowsFiveChunk2_resultant_certificate,
    voightPolynomialRowsFiveChunk3_resultant_certificate,
    voightPolynomialRowsFiveChunk4_resultant_certificate,
    voightPolynomialRowsFiveChunk5_resultant_certificate,
    voightPolynomialRowsFiveChunk6_resultant_certificate,
    Bool.and_true
  ]

theorem voightPolynomialRowsSix_resultant_certificate :
    voightPolynomialRowsSix.all
      (voightResultantCertificate 6) = true := by
  simp only [
    voightPolynomialRowsSix,
    List.all_append,
    voightPolynomialRowsSixChunk0_resultant_certificate,
    voightPolynomialRowsSixChunk1_resultant_certificate,
    voightPolynomialRowsSixChunk2_resultant_certificate,
    voightPolynomialRowsSixChunk3_resultant_certificate,
    voightPolynomialRowsSixChunk4_resultant_certificate,
    voightPolynomialRowsSixChunk5_resultant_certificate,
    voightPolynomialRowsSixChunk6_resultant_certificate,
    voightPolynomialRowsSixChunk7_resultant_certificate,
    voightPolynomialRowsSixChunk8_resultant_certificate,
    Bool.and_true
  ]

theorem voightPolynomialRowsSeven_resultant_certificate :
    voightPolynomialRowsSeven.all
      (voightResultantCertificate 7) = true := by
  simp only [
    voightPolynomialRowsSeven,
    List.all_append,
    voightPolynomialRowsSevenChunk0_resultant_certificate,
    voightPolynomialRowsSevenChunk1_resultant_certificate,
    voightPolynomialRowsSevenChunk2_resultant_certificate,
    voightPolynomialRowsSevenChunk3_resultant_certificate,
    Bool.and_true
  ]

theorem voightPolynomialRowsEight_resultant_certificate :
    voightPolynomialRowsEight.all
      (voightResultantCertificate 8) = true := by
  simp only [
    voightPolynomialRowsEight,
    List.all_append,
    voightPolynomialRowsEightChunk0_resultant_certificate,
    voightPolynomialRowsEightChunk1_resultant_certificate,
    Bool.and_true
  ]

theorem voightPolynomialRowsNine_resultant_certificate :
    voightPolynomialRowsNine.all
      (voightResultantCertificate 9) = true := by
  simp only [
    voightPolynomialRowsNine,
    voightPolynomialRowsNineChunk0_resultant_certificate
  ]

theorem voightPolynomialRowsTen_resultant_certificate :
    voightPolynomialRowsTen.all
      (voightResultantCertificate 10) = true := by
  simp only [
    voightPolynomialRowsTen,
    List.all_append,
    voightPolynomialRowsTenChunk0_resultant_certificate,
    voightPolynomialRowsTenChunk1_resultant_certificate,
    voightPolynomialRowsTenChunk2_resultant_certificate,
    voightPolynomialRowsTenChunk3_resultant_certificate,
    voightPolynomialRowsTenChunk4_resultant_certificate,
    voightPolynomialRowsTenChunk5_resultant_certificate,
    voightPolynomialRowsTenChunk6_resultant_certificate,
    voightPolynomialRowsTenChunk7_resultant_certificate,
    Bool.and_true
  ]

/-- All 2773 archived polynomial rows have exact rational
row-reduction certificates for their claimed resultants. -/
theorem allVoightPolynomialRows_resultant_certificate :
    voightPolynomialRowsFive.all
      (voightResultantCertificate 5) = true ∧
    voightPolynomialRowsSix.all
      (voightResultantCertificate 6) = true ∧
    voightPolynomialRowsSeven.all
      (voightResultantCertificate 7) = true ∧
    voightPolynomialRowsEight.all
      (voightResultantCertificate 8) = true ∧
    voightPolynomialRowsNine.all
      (voightResultantCertificate 9) = true ∧
    voightPolynomialRowsTen.all
      (voightResultantCertificate 10) = true := by
  exact ⟨
    voightPolynomialRowsFive_resultant_certificate,
    voightPolynomialRowsSix_resultant_certificate,
    voightPolynomialRowsSeven_resultant_certificate,
    voightPolynomialRowsEight_resultant_certificate,
    voightPolynomialRowsNine_resultant_certificate,
    voightPolynomialRowsTen_resultant_certificate
  ⟩

/-- The certificate for the table selected by any degree. -/
theorem voightPolynomialRows_resultant_certificate (degree : ℕ) :
    (voightPolynomialRows degree).all
      (voightResultantCertificate degree) = true :=
  match degree with
  | 0 => by rfl
  | 1 => by rfl
  | 2 => by rfl
  | 3 => by rfl
  | 4 => by rfl
  | 5 => voightPolynomialRowsFive_resultant_certificate
  | 6 => voightPolynomialRowsSix_resultant_certificate
  | 7 => voightPolynomialRowsSeven_resultant_certificate
  | 8 => voightPolynomialRowsEight_resultant_certificate
  | 9 => voightPolynomialRowsNine_resultant_certificate
  | 10 => voightPolynomialRowsTen_resultant_certificate
  | .succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (degree))))))))))) => by rfl

/-- Every row in the table selected by a degree has the recorded
coefficient length, monicity, positive discriminant, and positive index. -/
theorem voightPolynomialRows_structural_certificate (degree : ℕ) :
    (voightPolynomialRows degree).all
      (VoightPolynomialRow.structurallyValid degree) = true :=
  match degree with
  | 0 => by rfl
  | 1 => by rfl
  | 2 => by rfl
  | 3 => by rfl
  | 4 => by rfl
  | 5 => voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.1
  | 6 => voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.1
  | 7 => voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.2.1
  | 8 => voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1
  | 9 => voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1
  | 10 => voightPolynomialRowData_certificate.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1
  | .succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (.succ (degree))))))))))) => by rfl

end TraceEuclidean
