import TraceEuclidean.GlobalLatticeClass
import Mathlib.LinearAlgebra.Basis.VectorSpace
import Mathlib.LinearAlgebra.Matrix.BilinearForm
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.Algebra.Group.Pointwise.Set.Basic
import Mathlib.RingTheory.Ideal.Operations

/-!
Concrete scale-two Gram matrices and volume ideals for the global lattice
presentations.  The volume ideal is generated by the determinants of all
full-size Gram matrices with vectors in the lattice, which is the intrinsic
definition used in the manuscript and in O'Meara, Section 82E.
-/

namespace TraceEuclidean

open Module
open scoped NumberField
open scoped Pointwise

noncomputable section

namespace GlobalLatticePresentation

/-- The finite independent subset selected from the spanning lattice. -/
def latticeBasisIndex (P : GlobalLatticePresentation) :
    Set (Fin P.rank → P.field.1) :=
  (linearIndepOn_empty P.field.1
    (id : (Fin P.rank → P.field.1) → (Fin P.rank → P.field.1))).extend
      (Set.empty_subset (P.L : Set (Fin P.rank → P.field.1)))

/-- A field basis selected inside the full lattice. -/
def latticeSubbasis (P : GlobalLatticePresentation) :
    Basis P.latticeBasisIndex P.field.1 (Fin P.rank → P.field.1) :=
  Module.Basis.ofSpan P.full.span_eq_top.ge

noncomputable instance latticeBasisIndexFinite (P : GlobalLatticePresentation) :
    Finite P.latticeBasisIndex :=
  Module.Finite.finite_basis P.latticeSubbasis

noncomputable instance latticeBasisIndexFintype (P : GlobalLatticePresentation) :
    Fintype P.latticeBasisIndex :=
  @Fintype.ofFinite P.latticeBasisIndex P.latticeBasisIndexFinite

theorem card_latticeBasisIndex (P : GlobalLatticePresentation) :
    Fintype.card P.latticeBasisIndex = P.rank := by
  rw [← Module.finrank_eq_card_basis P.latticeSubbasis]
  simp

/-- Reindex the selected lattice basis by the paper's rank. -/
def latticeFieldBasis (P : GlobalLatticePresentation) :
    Basis (Fin P.rank) P.field.1 (Fin P.rank → P.field.1) :=
  P.latticeSubbasis.reindex
    (Fintype.equivFinOfCardEq P.card_latticeBasisIndex)

theorem latticeBasisIndex_subset (P : GlobalLatticePresentation) :
    (P.latticeBasisIndex : Set (Fin P.rank → P.field.1)) ⊆ P.L := by
  exact (linearIndepOn_empty P.field.1
    (id : (Fin P.rank → P.field.1) → (Fin P.rank → P.field.1))).extend_subset
      (Set.empty_subset (P.L : Set (Fin P.rank → P.field.1)))

theorem latticeSubbasis_mem (P : GlobalLatticePresentation)
    (i : P.latticeBasisIndex) : P.latticeSubbasis i ∈ P.L := by
  have hi : P.latticeSubbasis i = i.1 := by
    unfold latticeSubbasis
    exact Module.Basis.ofSpan_apply_self P.full.span_eq_top.ge i
  rw [hi]
  exact P.latticeBasisIndex_subset i.2

theorem latticeFieldBasis_mem (P : GlobalLatticePresentation)
    (i : Fin P.rank) : P.latticeFieldBasis i ∈ P.L := by
  simpa [latticeFieldBasis] using
    P.latticeSubbasis_mem
      ((Fintype.equivFinOfCardEq P.card_latticeBasisIndex).symm i)

/-- The selected full field basis, bundled as lattice vectors. -/
def latticeFieldBasisVectors (P : GlobalLatticePresentation) :
    Fin P.rank → P.L :=
  fun i ↦ ⟨P.latticeFieldBasis i, P.latticeFieldBasis_mem i⟩

theorem latticeFieldBasisVectors_linearIndependent
    (P : GlobalLatticePresentation) :
    LinearIndependent P.field.1
      (fun i ↦ (P.latticeFieldBasisVectors i).1) := by
  change LinearIndependent P.field.1 P.latticeFieldBasis
  exact P.latticeFieldBasis.linearIndependent

theorem latticeFieldBasisVectors_span
    (P : GlobalLatticePresentation) :
    Submodule.span P.field.1
        (Set.range fun i ↦ (P.latticeFieldBasisVectors i).1) = ⊤ := by
  change Submodule.span P.field.1 (Set.range P.latticeFieldBasis) = ⊤
  exact P.latticeFieldBasis.span_eq

/-- A classic-integral bilinear value, viewed in the ring of integers. -/
def classicBilinearInteger (P : GlobalLatticePresentation)
    (hclassic : P.IsClassicIntegral) (x y : P.L) : 𝓞 P.field.1 :=
  ⟨QuadraticMap.associated P.Q x.1 y.1, hclassic x y⟩

@[simp]
theorem coe_classicBilinearInteger (P : GlobalLatticePresentation)
    (hclassic : P.IsClassicIntegral) (x y : P.L) :
    (P.classicBilinearInteger hclassic x y : P.field.1) =
      QuadraticMap.associated P.Q x.1 y.1 :=
  rfl

/-- A full-size Gram matrix with entries in the ring of integers. -/
def classicGramMatrix (P : GlobalLatticePresentation)
    (hclassic : P.IsClassicIntegral) (v : Fin P.rank → P.L) :
    Matrix (Fin P.rank) (Fin P.rank) (𝓞 P.field.1) :=
  fun i j ↦ P.classicBilinearInteger hclassic (v i) (v j)

/-- The determinant of a classic-integral Gram matrix. -/
def classicGramDet (P : GlobalLatticePresentation)
    (hclassic : P.IsClassicIntegral) (v : Fin P.rank → P.L) :
    𝓞 P.field.1 :=
  (P.classicGramMatrix hclassic v).det

theorem map_classicGramMatrix_basis
    (P : GlobalLatticePresentation) (hclassic : P.IsClassicIntegral) :
    (algebraMap (𝓞 P.field.1) P.field.1).mapMatrix
        (P.classicGramMatrix hclassic P.latticeFieldBasisVectors) =
      LinearMap.BilinForm.toMatrix P.latticeFieldBasis P.Q.associated := by
  ext i j
  simp [classicGramMatrix, latticeFieldBasisVectors]

/-- The selected classic Gram determinant is nonzero. -/
theorem classicGramDet_basis_ne_zero
    (P : GlobalLatticePresentation) (hclassic : P.IsClassicIntegral) :
    P.classicGramDet hclassic P.latticeFieldBasisVectors ≠ 0 := by
  intro hzero
  have hdet :
      (LinearMap.BilinForm.toMatrix
        P.latticeFieldBasis P.Q.associated).det ≠ 0 :=
    (LinearMap.BilinForm.nondegenerate_iff_det_ne_zero
      P.latticeFieldBasis).mp
        (QuadraticMap.nondegenerate_associated_iff.mpr P.nondegenerate)
  apply hdet
  rw [← P.map_classicGramMatrix_basis hclassic,
    ← (algebraMap (𝓞 P.field.1) P.field.1).map_det]
  change (P.classicGramMatrix hclassic P.latticeFieldBasisVectors).det = 0 at hzero
  rw [hzero, map_zero]

/--
The classic volume ideal generated by all full-size Gram determinants.
-/
def classicVolumeIdealOf (P : GlobalLatticePresentation)
    (hclassic : P.IsClassicIntegral) : Ideal (𝓞 P.field.1) :=
  Ideal.span (Set.range (P.classicGramDet hclassic))

/-- The volume ideal does not depend on the proof of classic integrality. -/
theorem classicVolumeIdealOf_proof_irrel
    (P : GlobalLatticePresentation) (h h' : P.IsClassicIntegral) :
    P.classicVolumeIdealOf h = P.classicVolumeIdealOf h' := by
  have hdet : P.classicGramDet h = P.classicGramDet h' := by
    funext v
    unfold classicGramDet classicGramMatrix classicBilinearInteger
    congr 1
  unfold classicVolumeIdealOf
  rw [hdet]

/-- The classic volume ideal of a nondegenerate full lattice is nonzero. -/
theorem classicVolumeIdealOf_ne_bot
    (P : GlobalLatticePresentation) (hclassic : P.IsClassicIntegral) :
    P.classicVolumeIdealOf hclassic ≠ ⊥ := by
  intro hbot
  have hmem :
      P.classicGramDet hclassic P.latticeFieldBasisVectors ∈
        P.classicVolumeIdealOf hclassic :=
    Ideal.subset_span (Set.mem_range_self P.latticeFieldBasisVectors)
  rw [hbot] at hmem
  exact P.classicGramDet_basis_ne_zero hclassic (by simpa using hmem)

/--
The polar value `Q(x+y)-Q(x)-Q(y)`, which is integral whenever the quadratic
values are integral.  It is the associated bilinear value of the form scaled
by two.
-/
def scaledBilinearInteger (P : GlobalLatticePresentation) (x y : P.L) :
    𝓞 P.field.1 :=
  ⟨P.Q (x.1 + y.1) - P.Q x.1 - P.Q y.1,
    (P.integral (x + y)).sub (P.integral x) |>.sub (P.integral y)⟩

@[simp]
theorem coe_scaledBilinearInteger (P : GlobalLatticePresentation)
    (x y : P.L) :
    (P.scaledBilinearInteger x y : P.field.1) =
      P.Q (x.1 + y.1) - P.Q x.1 - P.Q y.1 :=
  rfl

/-- The scaled integral entry is twice the associated bilinear value. -/
theorem scaledBilinearInteger_eq_two_associated
    (P : GlobalLatticePresentation) (x y : P.L) :
    (P.scaledBilinearInteger x y : P.field.1) =
      2 * QuadraticMap.associated P.Q x.1 y.1 := by
  simp only [coe_scaledBilinearInteger, QuadraticMap.associated_apply]
  simp [invOf_eq_inv]

/-- On a classic-integral lattice, the scale-two entry is twice the Gram entry. -/
theorem scaledBilinearInteger_eq_two_classic
    (P : GlobalLatticePresentation) (hclassic : P.IsClassicIntegral)
    (x y : P.L) :
    P.scaledBilinearInteger x y =
      (2 : 𝓞 P.field.1) * P.classicBilinearInteger hclassic x y := by
  apply NumberField.RingOfIntegers.coe_injective
  change (P.scaledBilinearInteger x y : P.field.1) =
    algebraMap (𝓞 P.field.1) P.field.1 (2 : 𝓞 P.field.1) *
      (P.classicBilinearInteger hclassic x y : P.field.1)
  rw [map_ofNat]
  exact P.scaledBilinearInteger_eq_two_associated x y

/-- A full-size integral Gram matrix for the scale-two form. -/
def integralScaledGramMatrix (P : GlobalLatticePresentation)
    (v : Fin P.rank → P.L) :
    Matrix (Fin P.rank) (Fin P.rank) (𝓞 P.field.1) :=
  fun i j ↦ P.scaledBilinearInteger (v i) (v j)

/-- The determinant of a scale-two integral Gram matrix. -/
def integralScaledGramDet (P : GlobalLatticePresentation)
    (v : Fin P.rank → P.L) : 𝓞 P.field.1 :=
  (P.integralScaledGramMatrix v).det

/-- The integral scale-two Gram matrix is twice the classic Gram matrix. -/
theorem integralScaledGramMatrix_eq_two_smul
    (P : GlobalLatticePresentation) (hclassic : P.IsClassicIntegral)
    (v : Fin P.rank → P.L) :
    P.integralScaledGramMatrix v =
      (2 : 𝓞 P.field.1) • P.classicGramMatrix hclassic v := by
  apply Matrix.ext
  intro i j
  change P.scaledBilinearInteger (v i) (v j) =
    (2 : 𝓞 P.field.1) * P.classicBilinearInteger hclassic (v i) (v j)
  exact P.scaledBilinearInteger_eq_two_classic hclassic (v i) (v j)

/-- Scaling every Gram entry by two scales its determinant by `2^rank`. -/
theorem integralScaledGramDet_eq_two_pow_mul
    (P : GlobalLatticePresentation) (hclassic : P.IsClassicIntegral)
    (v : Fin P.rank → P.L) :
    P.integralScaledGramDet v =
      (2 : 𝓞 P.field.1) ^ P.rank * P.classicGramDet hclassic v := by
  rw [integralScaledGramDet, P.integralScaledGramMatrix_eq_two_smul hclassic,
    Matrix.det_smul]
  simp [classicGramDet]

theorem map_integralScaledGramMatrix_basis
    (P : GlobalLatticePresentation) :
    (algebraMap (𝓞 P.field.1) P.field.1).mapMatrix
        (P.integralScaledGramMatrix P.latticeFieldBasisVectors) =
      (2 : P.field.1) •
        LinearMap.BilinForm.toMatrix P.latticeFieldBasis P.Q.associated := by
  apply Matrix.ext
  intro i j
  simp only [RingHom.mapMatrix_apply, Matrix.smul_apply,
    LinearMap.BilinForm.toMatrix_apply, smul_eq_mul]
  change
    (P.scaledBilinearInteger
      (P.latticeFieldBasisVectors i) (P.latticeFieldBasisVectors j) :
        P.field.1) =
      2 * QuadraticMap.associated P.Q
        (P.latticeFieldBasis i) (P.latticeFieldBasis j)
  simpa [latticeFieldBasisVectors] using
    P.scaledBilinearInteger_eq_two_associated
      (P.latticeFieldBasisVectors i) (P.latticeFieldBasisVectors j)

/-- The selected scale-two Gram determinant is nonzero. -/
theorem integralScaledGramDet_basis_ne_zero
    (P : GlobalLatticePresentation) :
    P.integralScaledGramDet P.latticeFieldBasisVectors ≠ 0 := by
  intro hzero
  have hdet :
      (LinearMap.BilinForm.toMatrix
        P.latticeFieldBasis P.Q.associated).det ≠ 0 :=
    (LinearMap.BilinForm.nondegenerate_iff_det_ne_zero
      P.latticeFieldBasis).mp
        (QuadraticMap.nondegenerate_associated_iff.mpr P.nondegenerate)
  have htwo : (2 : P.field.1) ≠ 0 := by norm_num
  have hscaled :
      ((2 : P.field.1) •
        LinearMap.BilinForm.toMatrix
          P.latticeFieldBasis P.Q.associated).det ≠ 0 := by
    rw [Matrix.det_smul]
    exact mul_ne_zero (pow_ne_zero _ htwo) hdet
  apply hscaled
  rw [← P.map_integralScaledGramMatrix_basis,
    ← (algebraMap (𝓞 P.field.1) P.field.1).map_det]
  change (P.integralScaledGramMatrix P.latticeFieldBasisVectors).det = 0 at hzero
  rw [hzero, map_zero]

/--
The integral volume ideal after scaling the quadratic form by two.
-/
def integralScaledVolumeIdealOf (P : GlobalLatticePresentation) :
    Ideal (𝓞 P.field.1) :=
  Ideal.span (Set.range P.integralScaledGramDet)

/-- The generator set of the scale-two volume ideal is multiplied by `2^rank`. -/
theorem range_integralScaledGramDet_eq
    (P : GlobalLatticePresentation) (hclassic : P.IsClassicIntegral) :
    Set.range P.integralScaledGramDet =
      ({(2 : 𝓞 P.field.1) ^ P.rank} : Set (𝓞 P.field.1)) *
        Set.range (P.classicGramDet hclassic) := by
  rw [Set.singleton_mul]
  ext z
  constructor
  · rintro ⟨v, rfl⟩
    refine ⟨P.classicGramDet hclassic v, ⟨v, rfl⟩, ?_⟩
    exact (P.integralScaledGramDet_eq_two_pow_mul hclassic v).symm
  · rintro ⟨_, ⟨v, rfl⟩, rfl⟩
    exact ⟨v, P.integralScaledGramDet_eq_two_pow_mul hclassic v⟩

/-- The scale-two volume ideal is the classic volume ideal times `(2^rank)`. -/
theorem integralScaledVolumeIdealOf_eq
    (P : GlobalLatticePresentation) (hclassic : P.IsClassicIntegral) :
    P.integralScaledVolumeIdealOf =
      Ideal.span ({(2 : 𝓞 P.field.1) ^ P.rank} : Set (𝓞 P.field.1)) *
        P.classicVolumeIdealOf hclassic := by
  rw [integralScaledVolumeIdealOf, classicVolumeIdealOf,
    P.range_integralScaledGramDet_eq, Ideal.span_mul_span]

/-- Absolute norms acquire the paper's exact factor `2^(rank*degree)`. -/
theorem absNorm_integralScaledVolumeIdealOf
    (P : GlobalLatticePresentation) (hclassic : P.IsClassicIntegral) :
    Ideal.absNorm P.integralScaledVolumeIdealOf =
      2 ^ (P.rank * P.degree) *
        Ideal.absNorm (P.classicVolumeIdealOf hclassic) := by
  rw [P.integralScaledVolumeIdealOf_eq hclassic,
    ← Ideal.span_singleton_pow, map_mul, map_pow]
  have htwo :
      Ideal.absNorm (Ideal.span ({(2 : 𝓞 P.field.1)})) = 2 ^ P.degree := by
    simpa [GlobalLatticePresentation.degree,
      NumberField.RingOfIntegers.rank] using
      (Ideal.absNorm_span_natCast (S := 𝓞 P.field.1) 2)
  rw [htwo, pow_mul' 2 P.rank P.degree]

/-- The scale-two volume ideal of a nondegenerate full lattice is nonzero. -/
theorem integralScaledVolumeIdealOf_ne_bot
    (P : GlobalLatticePresentation) :
    P.integralScaledVolumeIdealOf ≠ ⊥ := by
  intro hbot
  have hmem :
      P.integralScaledGramDet P.latticeFieldBasisVectors ∈
        P.integralScaledVolumeIdealOf :=
    Ideal.subset_span (Set.mem_range_self P.latticeFieldBasisVectors)
  rw [hbot] at hmem
  exact P.integralScaledGramDet_basis_ne_zero (by simpa using hmem)

end GlobalLatticePresentation

namespace GlobalLatticeClass

/-- The selected representative satisfies classic integrality when its class does. -/
theorem representative_isClassicIntegral {c : GlobalLatticeClass}
    (hc : c.IsClassicIntegral) : c.representative.IsClassicIntegral := by
  rw [← isClassicIntegral_mk c.representative, c.mk_representative]
  exact hc

/--
The classic volume ideal of a class.  Outside the classic-integral locus it is
set to the zero ideal; all classic finiteness statements carry the locus
hypothesis.
-/
def classicVolumeIdeal (c : GlobalLatticeClass) :
    Ideal (𝓞 c.fieldCode) := by
  by_cases hc : c.IsClassicIntegral
  · exact c.representative.classicVolumeIdealOf
      (representative_isClassicIntegral hc)
  · exact ⊥

/-- The volume ideal of the scale-two form attached to an integral class. -/
def integralScaledVolumeIdeal (c : GlobalLatticeClass) :
    Ideal (𝓞 c.fieldCode) :=
  c.representative.integralScaledVolumeIdealOf

/-- A classic class has a nonzero selected volume ideal. -/
theorem classicVolumeIdeal_ne_bot {c : GlobalLatticeClass}
    (hc : c.IsClassicIntegral) : c.classicVolumeIdeal ≠ ⊥ := by
  rw [show c.classicVolumeIdeal =
      c.representative.classicVolumeIdealOf
        (representative_isClassicIntegral hc) by
    simp [classicVolumeIdeal, hc]]
  exact c.representative.classicVolumeIdealOf_ne_bot
    (representative_isClassicIntegral hc)

/-- Every integral class has a nonzero scale-two volume ideal. -/
theorem integralScaledVolumeIdeal_ne_bot (c : GlobalLatticeClass) :
    c.integralScaledVolumeIdeal ≠ ⊥ :=
  c.representative.integralScaledVolumeIdealOf_ne_bot

/-- The norm of a classic class volume ideal is at least one. -/
theorem one_le_absNorm_classicVolumeIdeal {c : GlobalLatticeClass}
    (hc : c.IsClassicIntegral) :
    1 ≤ Ideal.absNorm c.classicVolumeIdeal := by
  exact Nat.one_le_iff_ne_zero.mpr
    (Ideal.absNorm_eq_zero_iff.not.mpr (classicVolumeIdeal_ne_bot hc))

/-- The norm of every scale-two class volume ideal is at least one. -/
theorem one_le_absNorm_integralScaledVolumeIdeal (c : GlobalLatticeClass) :
    1 ≤ Ideal.absNorm c.integralScaledVolumeIdeal := by
  exact Nat.one_le_iff_ne_zero.mpr
    (Ideal.absNorm_eq_zero_iff.not.mpr (integralScaledVolumeIdeal_ne_bot c))

/-- On the classic locus, the class-level norm has the exact scale-two factor. -/
theorem absNorm_integralScaledVolumeIdeal {c : GlobalLatticeClass}
    (hc : c.IsClassicIntegral) :
    Ideal.absNorm c.integralScaledVolumeIdeal =
      2 ^ (c.rank * c.degree) * Ideal.absNorm c.classicVolumeIdeal := by
  unfold integralScaledVolumeIdeal classicVolumeIdeal
  split
  next hclassic =>
    calc
      Ideal.absNorm c.representative.integralScaledVolumeIdealOf =
          2 ^ (c.representative.rank * c.representative.degree) *
            Ideal.absNorm (c.representative.classicVolumeIdealOf
              (representative_isClassicIntegral hclassic)) :=
        c.representative.absNorm_integralScaledVolumeIdealOf
          (representative_isClassicIntegral hclassic)
      _ = 2 ^ (c.rank * c.degree) *
            Ideal.absNorm (c.representative.classicVolumeIdealOf _) := by
        rw [representative_rank, representative_degree]
  next hnot => exact (hnot hc).elim

/-- Transport the selected classic volume ideal to an exact field-code fiber. -/
def classicVolumeIdealInFiber (K : CodedNumberField)
    (c : FieldFiber fieldCode K) : Ideal (𝓞 K) := by
  rw [← c.2]
  exact classicVolumeIdeal c.1

/-- Transport the selected scaled volume ideal to an exact field-code fiber. -/
def integralScaledVolumeIdealInFiber (K : CodedNumberField)
    (c : FieldFiber fieldCode K) : Ideal (𝓞 K) := by
  rw [← c.2]
  exact integralScaledVolumeIdeal c.1

/-- Nonzero classic volume ideal in an exact field-code fiber. -/
theorem classicVolumeIdealInFiber_ne_bot (K : CodedNumberField)
    (c : FieldFiber fieldCode K) (hc : c.1.IsClassicIntegral) :
    classicVolumeIdealInFiber K c ≠ ⊥ := by
  rcases c with ⟨c, hcK⟩
  subst K
  exact classicVolumeIdeal_ne_bot hc

/-- Nonzero scale-two volume ideal in an exact field-code fiber. -/
theorem integralScaledVolumeIdealInFiber_ne_bot (K : CodedNumberField)
    (c : FieldFiber fieldCode K) :
    integralScaledVolumeIdealInFiber K c ≠ ⊥ := by
  rcases c with ⟨c, hcK⟩
  subst K
  exact integralScaledVolumeIdeal_ne_bot c

/-- The norm of a nonzero classic volume ideal is at least one. -/
theorem one_le_absNorm_classicVolumeIdealInFiber (K : CodedNumberField)
    (c : FieldFiber fieldCode K) (hc : c.1.IsClassicIntegral) :
    1 ≤ Ideal.absNorm (classicVolumeIdealInFiber K c) := by
  exact Nat.one_le_iff_ne_zero.mpr
    (Ideal.absNorm_eq_zero_iff.not.mpr
      (classicVolumeIdealInFiber_ne_bot K c hc))

/-- The norm of every scale-two volume ideal is at least one. -/
theorem one_le_absNorm_integralScaledVolumeIdealInFiber
    (K : CodedNumberField) (c : FieldFiber fieldCode K) :
    1 ≤ Ideal.absNorm (integralScaledVolumeIdealInFiber K c) := by
  exact Nat.one_le_iff_ne_zero.mpr
    (Ideal.absNorm_eq_zero_iff.not.mpr
      (integralScaledVolumeIdealInFiber_ne_bot K c))

end GlobalLatticeClass

end

end TraceEuclidean
