#!/usr/bin/env python3
"""Generate the Lean discriminant lists from Voight's archived field tables."""

from __future__ import annotations

import ast
import argparse
import hashlib
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT_DIR = ROOT / "inputs" / "voight"
OUTPUT = ROOT / "lean" / "TraceEuclidean" / "V15VoightDiscriminantData.lean"


@dataclass(frozen=True)
class Table:
    degree: int
    filename: str
    expected_count: int
    expected_minimum: int
    lean_name: str
    line_records: bool = False


TABLES = (
    Table(5, "5-17.txt", 674, 14641, "Five"),
    Table(6, "6-16.txt", 827, 300125, "Six"),
    Table(7, "7-15.5.txt", 301, 20134393, "Seven"),
    Table(8, "8-15.txt", 164, 282300416, "Eight"),
    Table(9, "9-14.5.txt", 15, 9685993193, "Nine"),
)

SUPPLEMENTAL_TABLES = (
    Table(10, "10.txt", 792, 443952558373, "Ten", line_records=True),
)

EXPECTED_HASHES = {
    "5-17.txt": "7c2ce57f51de3ad34bb60ade85659689fc629406315e9699a144f737d1b34192",
    "6-16.txt": "6e6bc75b54ad2643a42a3dfdd9497347eb89735d00c5b7367e934ad32d8ae082",
    "7-15.5.txt": "95ed179560eb866445eee3da22826cf98cc5eb0bc7f5091c27f4d332dc421a3d",
    "8-15.txt": "204a0ea04e2f4079f6fea20369ad8822d4d678a718272b9aaea68cf144b83294",
    "9-14.5.txt": "9c14aa90371184020bb121c36e63ceaa5bd4ada0eb55198fd94d4df67d6d3821",
    "10.txt": "cceac525009d9ab6b947e17186a5e74df2643eace152955702d306af6defbe83",
}


def validate_hashes() -> None:
    for filename, expected in EXPECTED_HASHES.items():
        actual = hashlib.sha256((INPUT_DIR / filename).read_bytes()).hexdigest()
        if actual != expected:
            raise ValueError(f"{filename}: expected SHA-256 {expected}, found {actual}")


def read_table(table: Table) -> list[int]:
    source = (INPUT_DIR / table.filename).read_text(encoding="utf-8")
    if table.line_records:
        rows = [ast.literal_eval(line) for line in source.splitlines() if line.strip()]
    else:
        rows = ast.literal_eval(source)
    if len(rows) != table.expected_count:
        raise ValueError(
            f"{table.filename}: expected {table.expected_count} rows, found {len(rows)}"
        )
    discriminants: list[int] = []
    for row_number, row in enumerate(rows, 1):
        if not (
            isinstance(row, list)
            and len(row) == 2
            and isinstance(row[0], int)
            and isinstance(row[1], list)
            and all(isinstance(c, int) for c in row[1])
        ):
            raise ValueError(f"{table.filename}:{row_number}: malformed row")
        discriminant, coefficients = row
        if discriminant <= 0:
            raise ValueError(f"{table.filename}:{row_number}: nonpositive discriminant")
        if len(coefficients) != table.degree + 1 or coefficients[-1] != 1:
            raise ValueError(f"{table.filename}:{row_number}: malformed monic polynomial")
        discriminants.append(discriminant)
    if discriminants[0] != table.expected_minimum:
        raise ValueError(
            f"{table.filename}: expected first discriminant {table.expected_minimum}, "
            f"found {discriminants[0]}"
        )
    if discriminants != sorted(discriminants):
        raise ValueError(f"{table.filename}: discriminants are not sorted")
    return discriminants


def format_list(values: list[int]) -> str:
    lines = []
    for start in range(0, len(values), 6):
        chunk = ", ".join(str(value) for value in values[start : start + 6])
        lines.append(f"    {chunk}")
    return "[\n" + ",\n".join(lines) + "\n  ]"


def render() -> str:
    validate_hashes()
    data = {table.degree: read_table(table) for table in TABLES}
    supplemental = {
        table.degree: read_table(table) for table in SUPPLEMENTAL_TABLES
    }
    if supplemental[10][0] <= 14**10:
        raise ValueError("10.txt: first discriminant does not exceed 14^10")
    out = [
        "import Mathlib",
        "",
        "/-!",
        "# Discriminants from Voight's archived totally real field tables",
        "",
        "This file is generated by `tools/generate_voight_discriminant_data.py`.",
        "It contains only the discriminant columns.  The source tables, archive",
        "timestamps, and checksums are recorded under `inputs/voight`.",
        "-/",
        "",
        "namespace TraceEuclidean",
        "",
    ]
    for table in TABLES:
        out.extend(
            [
                f"/-- Degree-{table.degree} discriminants in Voight's `{table.filename}` table. -/",
                f"def v15VoightDiscriminants{table.lean_name} : List ℕ :=",
                f"  {format_list(data[table.degree])}",
                "",
            ]
        )
    out.extend(
        [
            "/-- The archived table selected by a degree from five through nine;",
            "degree ten has no field at root discriminant at most fourteen. -/",
            "def v15VoightDiscriminants : ℕ → List ℕ",
            "  | 5 => v15VoightDiscriminantsFive",
            "  | 6 => v15VoightDiscriminantsSix",
            "  | 7 => v15VoightDiscriminantsSeven",
            "  | 8 => v15VoightDiscriminantsEight",
            "  | 9 => v15VoightDiscriminantsNine",
            "  | _ => []",
            "",
            "/-- One native certificate checks all row counts and the sorted order",
            "of every imported discriminant column. -/",
            "theorem v15_voightDiscriminantData_certificate :",
            "    v15VoightDiscriminantsFive.length = 674 ∧",
            "    v15VoightDiscriminantsFive.Pairwise (· ≤ ·) ∧",
            "    v15VoightDiscriminantsSix.length = 827 ∧",
            "    v15VoightDiscriminantsSix.Pairwise (· ≤ ·) ∧",
            "    v15VoightDiscriminantsSeven.length = 301 ∧",
            "    v15VoightDiscriminantsSeven.Pairwise (· ≤ ·) ∧",
            "    v15VoightDiscriminantsEight.length = 164 ∧",
            "    v15VoightDiscriminantsEight.Pairwise (· ≤ ·) ∧",
            "    v15VoightDiscriminantsNine.length = 15 ∧",
            "    v15VoightDiscriminantsNine.Pairwise (· ≤ ·) := by",
            "  native_decide",
            "",
            "theorem v15_voightDiscriminantsFive_pairwise :",
            "    v15VoightDiscriminantsFive.Pairwise (· ≤ ·) :=",
            "  v15_voightDiscriminantData_certificate.2.1",
            "",
            "theorem v15_voightDiscriminantsSix_pairwise :",
            "    v15VoightDiscriminantsSix.Pairwise (· ≤ ·) :=",
            "  v15_voightDiscriminantData_certificate.2.2.2.1",
            "",
            "theorem v15_voightDiscriminantsSeven_pairwise :",
            "    v15VoightDiscriminantsSeven.Pairwise (· ≤ ·) :=",
            "  v15_voightDiscriminantData_certificate.2.2.2.2.2.1",
            "",
            "theorem v15_voightDiscriminantsEight_pairwise :",
            "    v15VoightDiscriminantsEight.Pairwise (· ≤ ·) :=",
            "  v15_voightDiscriminantData_certificate.2.2.2.2.2.2.2.1",
            "",
            "theorem v15_voightDiscriminantsNine_pairwise :",
            "    v15VoightDiscriminantsNine.Pairwise (· ≤ ·) :=",
            "  v15_voightDiscriminantData_certificate.2.2.2.2.2.2.2.2.2",
            "",
            "end TraceEuclidean",
            "",
        ]
    )
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the source tables and fail if the generated Lean file is stale",
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8")
        if current != generated:
            raise SystemExit(
                "V15VoightDiscriminantData.lean is stale; rerun the generator"
            )
        print("Voight source tables and generated Lean data: PASS")
        return
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
