import TraceEuclidean.DegreeFiveMinimumClosed
import TraceEuclidean.DegreeSevenMinimumReduction
import TraceEuclidean.DegreeSevenRolleStageThreeCompleteness
import TraceEuclidean.DegreeSevenRolleStageFourCompleteness
import TraceEuclidean.DegreeSevenLagrangeRootBound
import TraceEuclidean.DegreeSevenRolleStageFiveBridge
import TraceEuclidean.DegreeSevenRolleStageFiveCompact
import TraceEuclidean.DegreeSevenRolleStageFiveCompleteness
import TraceEuclidean.DegreeSevenRolleStageSixBridge
import TraceEuclidean.DegreeSevenRolleStageSixStrongCompactCompleteness
import TraceEuclidean.DegreeSevenRolleStageSixPiecewise
import TraceEuclidean.DegreeSevenRolleStageSixPiecewiseCompleteness
import TraceEuclidean.DegreeSevenRolleStageSixScaledCandidates
import TraceEuclidean.DegreeSevenRolleStageSevenScaled
import TraceEuclidean.DegreeSevenRolleStageSevenCompleteness
import TraceEuclidean.DegreeSevenRolleStageSevenRejected
import TraceEuclidean.DegreeSevenRolleStageSevenRejectedScaled
import TraceEuclidean.DegreeSevenRolleStageSevenPrefixBridge
import TraceEuclidean.DegreeSevenRolleStageSevenScaledCandidates
import TraceEuclidean.DegreeSevenSurvivorDiscriminants
import TraceEuclidean.DegreeSevenRows200To299SurvivorDiscriminants
import TraceEuclidean.SectionFourVoightClosed
import TraceEuclidean.PoitouAdmissibility
import TraceEuclidean.PoitouZeroStrip
import TraceEuclidean.VoightHigherCoefficientPruning

/-!
# Kernel-only  verification surface

This facade exposes the proof-bearing  endpoints without importing the
large archival replays that use compiler-native evaluation.  The accompanying
import-closure check rejects that mechanism in every project module reachable
from this file.
-/
